Low: apache: Warn user if status url can not be accessed during monitor (when monitor is not probe)

diff --git a/heartbeat/apache b/heartbeat/apache
--- a/heartbeat/apache
+++ b/heartbeat/apache
@@ -300,6 +300,9 @@ apache_monitor_10() {
 	then
 		return $OCF_SUCCESS
 	else
+		if ! ocf_is_probe; then
+			ocf_log err "Failed to access httpd status page."
+		fi
 		return $OCF_ERR_GENERIC
 	fi
 }
@@ -308,6 +311,9 @@ apache_monitor_basic() {
 	then
 		return $OCF_SUCCESS
 	else
+		if ! ocf_is_probe; then
+			ocf_log err "Failed to access httpd status page."
+		fi
 		return $OCF_ERR_GENERIC
 	fi
 }
