Fixed another little bug in apache related to handling missing configuration files if they're on a disk which isn't mounted.
CVS patchset: 9298
CVS date: 2006/04/18 20:24:01

--HG--
extra : convert_revision : 6a1389adda1690c6a237713f57889dfca2dbbe64

diff --git a/heartbeat/apache.in b/heartbeat/apache.in
--- a/heartbeat/apache.in
+++ b/heartbeat/apache.in
@@ -546,14 +546,18 @@ case "$CONFIGFILE" in
 esac
 
 if
-  [ ! -f "$CONFIGFILE" -a "X$COMMAND" = Xstop ]
+  [ ! -f "$CONFIGFILE" ]
 then
-  ocf_log warn "$CONFIGFILE not found - apache considered stopped"
-  exit $OCF_SUCCESS
+  case $COMMAND in
+    stop)	ocf_log warn "$CONFIGFILE not found - apache considered stopped"
+    		exit $OCF_SUCCESS;;
+    monitor)	exit $OCF_NOT_RUNNING;;
+    status)	exit $LSB_STATUS_STOPPED;;
+  esac
 fi
 
 if
-  GetParams $CONFIGFILE
+  [ "X$COMMAND" = Xmeta-data ] || GetParams $CONFIGFILE
 then
   : OK
 else
