High: apache: monitor operation of depth 10 for web applications (LF 2234)
Usage is explained in the README file.

Important changes supporting this feature:

- support for curl(1)
- the new parameters:
	OCF_RESKEY_client
	OCF_RESKEY_testurl
	OCF_RESKEY_testregex10
	OCF_RESKEY_testconffile
	OCF_RESKEY_testname
- add "--no-proxy --bind-address=127.0.0.1" to wget options

Also some code cleanup.

diff --git a/heartbeat/apache b/heartbeat/apache
--- a/heartbeat/apache
+++ b/heartbeat/apache
@@ -33,6 +33,11 @@
 #  OCF_RESKEY_statusurl
 #  OCF_RESKEY_options
 #  OCF_RESKEY_testregex
+#  OCF_RESKEY_client
+#  OCF_RESKEY_testurl
+#  OCF_RESKEY_testregex10
+#  OCF_RESKEY_testconffile
+#  OCF_RESKEY_testname
 #  OCF_RESKEY_envfiles
 
 
@@ -55,7 +60,12 @@ then
   HTTPDLIST="$HTTPDLIST `$MPM 2>/dev/null`"
 fi
 
-WGETOPTS="-O- -q -L"
+# default options for http clients
+# NB: We _always_ test a local resource, so it should be
+# safe to connect from the local interface.
+WGETOPTS="-O- -q -L --no-proxy --bind-address=127.0.0.1"
+CURLOPTS="-o - -Ss -L --interface lo"
+
 LOCALHOST="http://localhost"
 HTTPDOPTS="-DSTATUS"
 DEFAULT_IBMCONFIG=/opt/IBMHTTPServer/conf/httpd.conf
@@ -93,13 +103,107 @@ action:
 	monitor  return TRUE if the web server appears to be working.
                 For this to be supported you must configure mod_status
 		 and give it a server-status URL.  You have to have 
-		installed $WGET for this to work.
+		installed either curl or wget for this to work.
 
 	meta-data	show meta data message
 
 	validate-all	validate the instance parameters
 	!
   exit $1
+}
+
+#
+# run the http client
+#
+curl_func() {
+	cl_opts="$CURLOPTS $test_httpclient_opts"
+	if [ x != "x$test_user" ]; then
+		echo "-u $test_user:$test_password" |
+			curl -K - $cl_opts "$1"
+	else
+		curl $cl_opts "$1"
+	fi
+}
+wget_func() {
+	auth=""
+	cl_opts="$WGETOPTS $test_httpclient_opts"
+	[ x != "x$test_user" ] &&
+		auth="--http-user=$test_user --http-passwd=$test_password"
+	wget $auth $cl_opts "$1"
+}
+#
+# rely on whatever the user provided
+userdefined() {
+	$test_httpclient $test_httpclient_opts "$1"
+}
+
+#
+# find a good http client
+#
+findhttpclient() {
+	# prefer wget (for historical reasons)
+	if [ "x$CLIENT" != x ]; then
+		echo "$CLIENT"
+	elif which wget >/dev/null 2>&1; then
+		echo "wget"
+	elif which curl >/dev/null 2>&1; then
+		echo "curl"
+	else
+		return 1
+	fi
+}
+gethttpclient() {
+	[ -z "$test_httpclient" ] &&
+		test_httpclient=$ourhttpclient
+	case "$test_httpclient" in
+		curl|wget) echo ${test_httpclient}_func;;  #these are supported
+		*) echo userdefined;;
+	esac
+}
+
+# test configuration good?
+is_testconf_sane() {
+	if [ "x$test_regex" = x -o "x$test_url" = x ]; then
+		ocf_log err "test regular expression or test url empty"
+		return 1
+	fi
+	if [ "x$test_user$test_password" != x -a \( "x$test_user" = x -o "x$test_password" = x \) ]; then
+		ocf_log err "bad user authentication for extended test"
+		return 1
+	fi
+	return 0
+}
+#
+# read the test definition from the config
+#
+readtestconf() {
+	test_name="$1" # we look for this one or the first one if empty
+	lcnt=0
+	readdef=""
+	test_url="" test_regex=""
+	test_user="" test_password=""
+	test_httpclient="" test_httpclient_opts=""
+
+	while read key value; do
+		lcnt=$((lcnt+1))
+		if [ "$readdef" ]; then
+			case "$key" in
+			"url") test_url="$value" ;;
+			"user") test_user="$value" ;;
+			"password") test_password="$value" ;;
+			"client") test_httpclient="$value" ;;
+			"client_opts") test_httpclient_opts="$value" ;;
+			"match") test_regex="$value" ;;
+			"end") break ;;
+			"#"*|"") ;;
+			*) ocf_log err "$lcnt: $key: unknown keyword"; return 1 ;;
+			esac
+		else
+			[ "$key" = "test" ] &&
+				[ -z "$test_name" -o "$test_name" = "$value" ] &&
+				readdef=1
+		fi
+	done
 }
 
 source_envfiles() {
@@ -206,7 +310,11 @@ CheckPort() {
   ocf_is_decimal "$1" && [ $1 -gt 0 ]
 }
 
-
+buildlocalurl() {
+  [ "x$Listen" != "x" ] &&
+	echo "http://${Listen}" ||
+	echo "${LOCALHOST}:${PORT}"
+}
 #
 #	Get all the parameters we need from the Apache config file
 #
@@ -221,18 +329,17 @@ GetParams() {
     [[:alnum:]]*)	PidFile=$ServerRoot/$PidFile;;
     *)	PidFile=$HA_VARRUNDIR/${httpd_basename}.pid;;
   esac
-  if CheckPort "$PORT"; then
-	:
-  else
-	PORT=$Port
-	if CheckPort "$PORT"; then
-	    :
-	else
-	# Final resort
-	    PORT=80
-	fi
-  fi
-  
+
+  for p in "$PORT" "$Port" 80; do
+    if CheckPort "$p"; then
+      PORT="$p"
+      break
+    fi
+  done
+ 
+  echo $Listen | grep ':' >/dev/null ||  # Listen could be just port spec
+	  Listen="localhost:$Listen"
+
   #
   # It's difficult to figure out whether the server supports
   # the status operation.
@@ -242,7 +349,6 @@ GetParams() {
   #
   # For us to think status will work, we have to have the following things:
   #
-  # - $WGET has to exist and be executable
   # - The server-status handler has to be mapped to some URL somewhere
   #
   # We assume that:
@@ -256,23 +362,8 @@ GetParams() {
   if
      [ "X$STATUSURL" = "X" ]
   then
-    if
-	have_binary $WGET
-    then
       StatusURL=`FindLocationForHandler $1 server-status | tail -1`
-      if
-        [ "x$Listen" != "x" ]
-      then
-        echo $Listen | grep ':' >/dev/null ||  # Listen can be only port spec
-          Listen="localhost:$Listen"
-        STATUSURL="http://${Listen}$StatusURL"
-        case $WGET in
-          *wget*)	WGETOPTS="$WGETOPTS --no-proxy --bind-address=127.0.0.1";;
-        esac
-      else
-        STATUSURL="${LOCALHOST}:${PORT}$StatusURL"
-      fi
-    fi
+      STATUSURL="`buildlocalurl`$StatusURL"
   fi
   test "$PidFile"
 }
@@ -387,28 +478,49 @@ status_apache() {
   fi
 }
 
-monitor_apache() {
-  if 
-	! have_binary $WGET
-  then
-	ocf_log err "Monitoring not supported by $OCF_RESOURCE_INSTANCE"
-	ocf_log info "Please make sure that wget is available"
+fixtesturl() {
+	echo $test_url | grep -qs "^http" && return
+	test_url="`buildlocalurl`$test_url"
+}
+monitor_apache_extended() {
+  if [ "$TESTCONFFILE" ]; then
+    readtestconf < $TESTCONFFILE
+  else
+	test_url="$TESTURL"
+	test_regex="$TESTREGEX10"
+  fi
+  whattorun=`gethttpclient`
+  fixtesturl
+  is_testconf_sane ||
+    return $OCF_ERR_CONFIGURED
+  $whattorun "$test_url" | grep -Ei "$test_regex" > /dev/null
+}
+monitor_apache_basic() {
+  if [ -z "$STATUSURL" ]; then
+    ocf_log err "statusurl parameter empty"
 	return $OCF_ERR_CONFIGURED
-
-  elif [ -z "$STATUSURL" ]; then
-	ocf_log err "Monitoring not supported by $CONFIGFILE"
-	ocf_log info "Please set the statusurl parameter"
+  elif [ -z "$ourhttpclient" ]; then
+    ocf_log err "could not find a http client; make sure that either wget or curl is available"
 	return $OCF_ERR_CONFIGURED
   fi
-
-  if
-    silent_status
-  then
-    ocf_run sh -c "$WGET $WGETOPTS $STATUSURL | tr '\012' ' ' | grep -Ei \"$TESTREGEX\" >/dev/null"
-  else
+  ${ourhttpclient}_func "$STATUSURL" | grep -Ei "$TESTREGEX" > /dev/null
+}
+monitor_apache() {
+  silent_status
+  if [ $? -ne 0 ]; then
     ocf_log info "$CMD not running"
     return $OCF_NOT_RUNNING
   fi
+  ourhttpclient=`findhttpclient`  # we'll need one
+  monitor_apache_basic &&
+  case "$OCF_CHECK_LEVEL" in
+  ""|0) true;;
+  10) monitor_apache_extended;;
+  *)
+    ocf_log err "bad OCF_CHECK_LEVEL: $OCF_CHECK_LEVEL"
+	return $OCF_ERR_CONFIGURED
+	;;
+  esac
 }
 
 metadata_apache(){
@@ -489,10 +601,61 @@ complains about the resource being active on multiple nodes.
 <parameter name="testregex">
 <longdesc lang="en">
 Regular expression to match in the output of statusurl.
-It is case insensitive.
+Case insensitive.
 </longdesc>
 <shortdesc lang="en">monitor regular expression</shortdesc>
 <content type="string" default="exists, but impossible to show in a human readable format (try grep testregex)"/>
+</parameter>
+
+<parameter name="client">
+<longdesc lang="en">
+Client to use to query to Apache. If not specified, the RA will
+try to find one on the system. Currently, wget and curl are
+supported. For example, you can set this paramter to "curl" if
+you prefer that to wget.
+</longdesc>
+<shortdesc lang="en">http client</shortdesc>
+<content type="string" default=""/>
+</parameter>
+
+<parameter name="testurl">
+<longdesc lang="en">
+URL to test. If it does not start with "http", then it's
+considered to be relative to the Listen address.
+</longdesc>
+<shortdesc lang="en">test url</shortdesc>
+<content type="string" />
+</parameter>
+
+<parameter name="testregex10">
+<longdesc lang="en">
+Regular expression to match in the output of testurl.
+Case insensitive.
+</longdesc>
+<shortdesc lang="en">extended monitor regular expression</shortdesc>
+<content type="string" />
+</parameter>
+
+<parameter name="testconffile">
+<longdesc lang="en">
+A file which contains test configuration. Could be useful if
+you have to check more than one web application or in case sensitive
+info should be passed as arguments (passwords). Furthermore,
+using a config file is the only way to specify certain
+parameters.
+
+Please see README.webapps for examples and file description.
+</longdesc>
+<shortdesc lang="en">test configuration file</shortdesc>
+<content type="string" />
+</parameter>
+
+<parameter name="testname">
+<longdesc lang="en">
+Name of the test within the test configuration file.
+</longdesc>
+<shortdesc lang="en">test name</shortdesc>
+<content type="string" />
 </parameter>
 
 <parameter name="options">
@@ -572,7 +735,12 @@ then
   STATUSURL="$OCF_RESKEY_statusurl"
   CONFIGFILE="$OCF_RESKEY_configfile"
   OPTIONS="$OCF_RESKEY_options"
+  CLIENT=${OCF_RESKEY_client}
   TESTREGEX=${OCF_RESKEY_testregex:-'</ *body *>[[:space:]]*</ *html *>'}
+  TESTURL="$OCF_RESKEY_testurl"
+  TESTREGEX10=${OCF_RESKEY_testregex10}
+  TESTCONFFILE="$OCF_RESKEY_testconffile"
+  TESTNAME="$OCF_RESKEY_testname"
   : ${OCF_RESKEY_envfiles="/etc/apache2/envvars"}
   source_envfiles $OCF_RESKEY_envfiles
 else
