Low: asterisk: whitespace cleanup
Indent with 4 spaces.
Kill trailing whitespace.

diff --git a/heartbeat/asterisk b/heartbeat/asterisk
--- a/heartbeat/asterisk
+++ b/heartbeat/asterisk
@@ -3,15 +3,15 @@
 #
 # Asterisk
 #
-# Description:	Manages an Asterisk PBX as an HA resource
+# Description:  Manages an Asterisk PBX as an HA resource
 #
-# Authors:	Martin Gerhard Loschwitz
-#		Florian Haas
+# Authors:      Martin Gerhard Loschwitz
+#               Florian Haas
 #
-# Support:	linux-ha@lists.linux-ha.org
-# License:	GNU General Public License (GPL)
+# Support:      linux-ha@lists.linux-ha.org
+# License:      GNU General Public License (GPL)
 #
-# (c) 2011	hastexo Professional Services GmbH
+# (c) 2011      hastexo Professional Services GmbH
 #
 # This resource agent is losely derived from the MySQL resource
 # agent, which itself is made available to the public under the
@@ -42,11 +42,11 @@
 # Fill in some defaults if no values are specified
 HOSTOS=`uname`
 if [ "X${HOSTOS}" = "XOpenBSD" ]; then
-  OCF_RESKEY_user_default="_asterisk"
-  OCF_RESKEY_group_default="_asterisk"
+    OCF_RESKEY_user_default="_asterisk"
+    OCF_RESKEY_group_default="_asterisk"
 else
-  OCF_RESKEY_user_default="asterisk"
-  OCF_RESKEY_group_default="asterisk"
+    OCF_RESKEY_user_default="asterisk"
+    OCF_RESKEY_group_default="asterisk"
 fi
 OCF_RESKEY_binary_default="asterisk"
 OCF_RESKEY_canary_binary_default="astcanary"
@@ -67,23 +67,23 @@ OCF_RESKEY_maxfiles_default="8192"
 #######################################################################
 
 usage() {
-  cat <<UEND
-	usage: $0 (start|stop|validate-all|meta-data|status|monitor)
+    cat <<UEND
+        usage: $0 (start|stop|validate-all|meta-data|status|monitor)
 
-	$0 manages an Asterisk PBX as an HA resource.
+        $0 manages an Asterisk PBX as an HA resource.
 
-	The 'start' operation starts the database.
-	The 'stop' operation stops the database.
-	The 'validate-all' operation reports whether the parameters are valid
-	The 'meta-data' operation reports this RA's meta-data information
-	The 'status' operation reports whether the database is running
-	The 'monitor' operation reports whether the database seems to be working
+        The 'start' operation starts the database.
+        The 'stop' operation stops the database.
+        The 'validate-all' operation reports whether the parameters are valid
+        The 'meta-data' operation reports this RA's meta-data information
+        The 'status' operation reports whether the database is running
+        The 'monitor' operation reports whether the database seems to be working
 
 UEND
 }
 
 meta_data() {
-	cat <<END
+    cat <<END
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
 <resource-agent name="asterisk">
@@ -193,11 +193,11 @@ END
 # Convenience functions
 
 asterisk_rx() {
-        # if $HOME is set, asterisk -rx writes a .asterisk_history there
-        (
-                unset HOME
-                ocf_run $OCF_RESKEY_binary -r -s $ASTRUNDIR/asterisk.ctl -x "$1"
-        )
+    # if $HOME is set, asterisk -rx writes a .asterisk_history there
+    (
+        unset HOME
+        ocf_run $OCF_RESKEY_binary -r -s $ASTRUNDIR/asterisk.ctl -x "$1"
+    )
 }
 
 #######################################################################
@@ -210,59 +210,59 @@ asterisk_validate() {
     check_binary pgrep
 
     if [ -n "OCF_RESKEY_monitor_sipuri" ]; then
-	check_binary sipsak
+        check_binary sipsak
     fi
 
     if [ ! -f $OCF_RESKEY_config ]; then
-	ocf_log err "Config $OCF_RESKEY_config doesn't exist"
-	return $OCF_ERR_INSTALLED
+        ocf_log err "Config $OCF_RESKEY_config doesn't exist"
+        return $OCF_ERR_INSTALLED
     fi
 
     getent passwd $OCF_RESKEY_user >/dev/null 2>&1
     rc=$?
     if [ $rc -ne 0 ]; then
-	ocf_log err "User $OCF_RESKEY_user doesn't exist"
-	return $OCF_ERR_INSTALLED
+        ocf_log err "User $OCF_RESKEY_user doesn't exist"
+        return $OCF_ERR_INSTALLED
     fi
 
     getent group $OCF_RESKEY_group >/dev/null 2>&1
     rc=$?
     if [ $rc -ne 0 ]; then
-	ocf_log err "Group $OCF_RESKEY_group doesn't exist"
-	return $OCF_ERR_INSTALLED
+        ocf_log err "Group $OCF_RESKEY_group doesn't exist"
+        return $OCF_ERR_INSTALLED
     fi
 
     true
 }
 
 asterisk_status() {
-	local pid
-	local rc
+    local pid
+    local rc
 
-	if [ ! -f $ASTRUNDIR/asterisk.pid ]; then
-		ocf_log info "Asterisk PBX is not running"
-		return $OCF_NOT_RUNNING
-	fi
+    if [ ! -f $ASTRUNDIR/asterisk.pid ]; then
+        ocf_log info "Asterisk PBX is not running"
+        return $OCF_NOT_RUNNING
+    fi
 
-	pid=`cat $ASTRUNDIR/asterisk.pid`
-	ocf_run kill -s 0 $pid
-	rc=$?
+    pid=`cat $ASTRUNDIR/asterisk.pid`
+    ocf_run kill -s 0 $pid
+    rc=$?
 
-	if [ $rc -eq 0 ]; then
-	  if ocf_is_true "$OCF_RESKEY_realtime"; then
-	    astcanary_pid=`pgrep -d " " -x -f "astcanary $ASTRUNDIR/alt.asterisk.canary.tweet.tweet.tweet"`
-	    if [ ! "$astcanary_pid" ]; then
-	      ocf_log err "Asterisk PBX is running but astcanary is not although it should"
-	      return $OCF_ERR_GENERIC
-	    fi
-	  else
-	    return $OCF_SUCCESS
-	  fi
-	else
-	    ocf_log info "Asterisk PBX not running: removing old PID file"
-	    rm -f $ASTRUNDIR/asterisk.pid
-	    return $OCF_NOT_RUNNING
-	fi
+    if [ $rc -eq 0 ]; then
+        if ocf_is_true "$OCF_RESKEY_realtime"; then
+            astcanary_pid=`pgrep -d " " -x -f "astcanary $ASTRUNDIR/alt.asterisk.canary.tweet.tweet.tweet"`
+            if [ ! "$astcanary_pid" ]; then
+		ocf_log err "Asterisk PBX is running but astcanary is not although it should"
+		return $OCF_ERR_GENERIC
+            fi
+        else
+            return $OCF_SUCCESS
+        fi
+    else
+        ocf_log info "Asterisk PBX not running: removing old PID file"
+        rm -f $ASTRUNDIR/asterisk.pid
+        return $OCF_NOT_RUNNING
+    fi
 }
 
 asterisk_monitor() {
@@ -273,7 +273,7 @@ asterisk_monitor() {
 
     # If status returned an error, return that immediately
     if [ $rc -ne $OCF_SUCCESS ]; then
-	return $rc
+        return $rc
     fi
 
     # Check whether connecting to asterisk is possible
@@ -287,8 +287,8 @@ asterisk_monitor() {
 
     # Optionally check the monitor URI with sipsak
     if [ -n "OCF_RESKEY_monitor_sipuri" ]; then
-	ocf_run sipsak -v -s "$OCF_RESKEY_monitor_sipuri" \
-	    || return $OCF_ERR_GENERIC
+        ocf_run sipsak -v -s "$OCF_RESKEY_monitor_sipuri" \
+            || return $OCF_ERR_GENERIC
     fi
 
     ocf_log debug "Asterisk PBX monitor succeeded"
@@ -303,14 +303,14 @@ asterisk_start() {
     asterisk_status
     rc=$?
     if [ $rc -eq $OCF_SUCCESS ]; then
-	ocf_log info "Asterisk PBX already running"
-	return $OCF_SUCCESS
+        ocf_log info "Asterisk PBX already running"
+        return $OCF_SUCCESS
     fi
 
     # If Asterisk is not already running, make sure there is no
     # old astcanary instance when the new asterisk starts. To
     # achieve this, kill old astcanary instances belonging to
-    # this $ASTRUNDIR. 
+    # this $ASTRUNDIR.
 
     # Find out PIDs of running astcanaries
     astcanary_pid=`pgrep -d " " -x -f "astcanary $ASTRUNDIR/alt.asterisk.canary.tweet.tweet.tweet"`
@@ -322,17 +322,17 @@ asterisk_start() {
     fi
 
     for dir in $ASTRUNDIR $ASTLOGDIR $ASTLOGDIR/cdr-csv $ASTLOGDIR/cdr-custom; do
-	if [ ! -d "$dir" ]; then
-	    ocf_run install -d -o $OCF_RESKEY_user -g $OCF_RESKEY_group $dir \
-		|| exit $OCF_ERR_GENERIC
-	fi
+        if [ ! -d "$dir" ]; then
+            ocf_run install -d -o $OCF_RESKEY_user -g $OCF_RESKEY_group $dir \
+                || exit $OCF_ERR_GENERIC
+        fi
         # Regardless of whether we just created the directory or it
         # already existed, check whether it is writable by the configured
         # user
-	if ! su -s /bin/sh - $OCF_RESKEY_user -c "test -w $dir"; then
-	    ocf_log err "Directory $dir is not writable by $OCF_RESKEY_user"
-	    exit $OCF_ERR_PERM
-	fi
+        if ! su -s /bin/sh - $OCF_RESKEY_user -c "test -w $dir"; then
+            ocf_log err "Directory $dir is not writable by $OCF_RESKEY_user"
+            exit $OCF_ERR_PERM
+        fi
     done
 
     # set MAXFILES
@@ -347,25 +347,25 @@ asterisk_start() {
     fi
 
     ocf_run ${OCF_RESKEY_binary} -G $OCF_RESKEY_group -U $OCF_RESKEY_user \
-		-C $OCF_RESKEY_config \
+                -C $OCF_RESKEY_config \
                 $OCF_RESKEY_additional_parameters \
                 $asterisk_extra_params
     rc=$?
     if [ $rc -ne 0 ]; then
-	ocf_log err "Asterisk PBX start command failed: $rc"
-  	exit $OCF_ERR_GENERIC
+        ocf_log err "Asterisk PBX start command failed: $rc"
+        exit $OCF_ERR_GENERIC
     fi
 
     # Spin waiting for the server to come up.
     # Let the CRM/LRM time us out if required
     while true; do
-	asterisk_monitor
-	rc=$?
-	[ $rc -eq $OCF_SUCCESS ] && break
-	if [ $rc -ne $OCF_NOT_RUNNING ]; then
-	    ocf_log err "Asterisk PBX start failed"
-	    exit $OCF_ERR_GENERIC
-	fi
+        asterisk_monitor
+        rc=$?
+        [ $rc -eq $OCF_SUCCESS ] && break
+        if [ $rc -ne $OCF_NOT_RUNNING ]; then
+            ocf_log err "Asterisk PBX start failed"
+            exit $OCF_ERR_GENERIC
+        fi
         sleep 2
     done
 
@@ -381,8 +381,8 @@ asterisk_stop() {
     asterisk_status
     rc=$?
     if [ $rc -eq $OCF_NOT_RUNNING ]; then
-	ocf_log info "Asterisk PBX already stopped"
-	return $OCF_SUCCESS
+        ocf_log info "Asterisk PBX already stopped"
+        return $OCF_SUCCESS
     fi
 
     # do a "soft shutdown" via the asterisk command line first
@@ -401,33 +401,32 @@ asterisk_stop() {
     rc=$?
     if [ $rc -ne 0 ]; then
         ocf_log err "Asterisk PBX couldn't be stopped"
-	exit $OCF_ERR_GENERIC
+        exit $OCF_ERR_GENERIC
     fi
 
     # stop waiting
     shutdown_timeout=15
     if [ -n "$OCF_RESKEY_CRM_meta_timeout" ]; then
-	shutdown_timeout=$((($OCF_RESKEY_CRM_meta_timeout/1000)-5))
+        shutdown_timeout=$((($OCF_RESKEY_CRM_meta_timeout/1000)-5))
     fi
     count=0
-    while [ $count -lt $shutdown_timeout ]
-    do
-	asterisk_status
-	rc=$?
-	if [ $rc -eq $OCF_NOT_RUNNING ]; then
-	    break
-	fi
-	count=`expr $count + 1`
-	sleep 1
-	ocf_log debug "Asterisk PBX still hasn't stopped yet. Waiting ..."
+    while [ $count -lt $shutdown_timeout ]; do
+        asterisk_status
+        rc=$?
+        if [ $rc -eq $OCF_NOT_RUNNING ]; then
+            break
+        fi
+        count=`expr $count + 1`
+        sleep 1
+        ocf_log debug "Asterisk PBX still hasn't stopped yet. Waiting ..."
     done
 
     asterisk_status
     rc=$?
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
-	# SIGTERM didn't help either, try SIGKILL
-	ocf_log info "Asterisk PBX failed to stop after ${shutdown_timeout}s using SIGTERM. Trying SIGKILL ..."
-	ocf_run kill -s KILL $pid
+        # SIGTERM didn't help either, try SIGKILL
+        ocf_log info "Asterisk PBX failed to stop after ${shutdown_timeout}s using SIGTERM. Trying SIGKILL ..."
+        ocf_run kill -s KILL $pid
     fi
 
     # After killing asterisk, stop astcanary
@@ -445,10 +444,10 @@ asterisk_stop() {
 #######################################################################
 
 case "$1" in
-  meta-data)	meta_data
-		exit $OCF_SUCCESS;;
-  usage|help)	usage
-		exit $OCF_SUCCESS;;
+  meta-data)    meta_data
+                exit $OCF_SUCCESS;;
+  usage|help)   usage
+                exit $OCF_SUCCESS;;
 esac
 
 
@@ -462,11 +461,11 @@ ASTLOGDIR=`grep astlogdir $OCF_RESKEY_config | awk '/^astlogdir/ {print $3}'`
 
 # What kind of method was invoked?
 case "$1" in
-  start)	asterisk_start;;
-  stop)		asterisk_stop;;
-  status)	asterisk_status;;
-  monitor)	asterisk_monitor;;
-  validate-all)	;;
-  *)		usage
-		exit $OCF_ERR_UNIMPLEMENTED;;
+  start)        asterisk_start;;
+  stop)         asterisk_stop;;
+  status)       asterisk_status;;
+  monitor)      asterisk_monitor;;
+  validate-all) ;;
+  *)            usage
+                exit $OCF_ERR_UNIMPLEMENTED;;
 esac
