Add the support to validate-all action; other minor polish. Done by Sun Xun <xunsun@cn.ibm.com>
CVS patchset: 6965
CVS date: 2005/07/11 08:57:16

--HG--
extra : convert_revision : 18dfafdea4ec32b520c6d2371abf1fca3de844d5

diff --git a/heartbeat/AudibleAlarm.in b/heartbeat/AudibleAlarm.in
--- a/heartbeat/AudibleAlarm.in
+++ b/heartbeat/AudibleAlarm.in
@@ -5,7 +5,7 @@
 # author: Kirk Lawson <lklawson@heapy.com> 
 #         Horms <horms@vergenet.net>
 #
-# description: sets an audiable alarm running by beeping at a set interval
+# description: sets an audible alarm running by beeping at a set interval
 # processname: alarm
 # config: /etc/AudibleAlarm/AudibleAlarm.conf - not yet implemented
 #
@@ -31,21 +31,21 @@ PIDFILE=@localstatedir@/run/heartbeat-bell
 us=`uname -n`
 
 usage() {
-	echo "Usage: $0 {start|stop|restart|status|monitor}"
+	echo "Usage: $0 {start|stop|restart|status|monitor|meta-data|validate-all}"
 	echo "  The node list is an optional space delimited"
 	echo "  list of hosts that should never sound the alarm."
-	echo "$Id: AudibleAlarm.in,v 1.1 2004/12/20 16:19:37 sunjd Exp $";
+	echo "$Id: AudibleAlarm.in,v 1.2 2005/07/11 08:57:16 sunjd Exp $";
 }
 
 meta_data() {
 	cat <<END
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
-<resource-agent name="AudibleAlarm" version="0.9">
+<resource-agent name="AudibleAlarm">
 <version>1.0</version>
 
 <longdesc lang="en">
-Resource script for AudibleAlarm. It sets an audiable alarm running by beeping 
+Resource script for AudibleAlarm. It sets an audible alarm running by beeping 
 at a set interval. 
 </longdesc>
 <shortdesc lang="en">AudibleAlarm resource agent</shortdesc>
@@ -67,12 +67,13 @@ The node list that should never sound the alarm.
 <action name="status" depth="0" timeout="10" interval="10" start-delay="10" />
 <action name="monitor" depth="0" timeout="10" interval="10" start-delay="10" />
 <action name="meta-data" timeout="5" />
+<action name="validate-all" timeout="5" />
 </actions>
 </resource-agent>
 END
 }
 
-audiablealarm_start () {
+audiblealarm_start () {
 	ocf_log "info" "$0: Starting"
     	if [ -f $PIDFILE ]; then
         	PID=`head -n 1 $PIDFILE`
@@ -89,47 +90,52 @@ audiablealarm_start () {
 	if ! echo $! >  $PIDFILE; then
 		ocf_log "info" "$0: Could not write to pid file \"$PIDFILE\", bailing"
 		kill $!
-		return 1
+		return $OCF_ERR_GENERIC
 	fi
 
 	return $?
 }
 
-audiablealarm_stop () {
+audiblealarm_stop () {
 	ocf_log "info" "$0: Shutting down"
   	if [ -f $PIDFILE ]; then
 		PID=`head -n 1 $PIDFILE`
 		# ocf_log "info" "$0: Appears to already be running, killing [$PID]"
 		# commented by Phost, since the confusion in the log.
-		kill $PID > /dev/null
-		rm -f $PIDFILE
+
+		# Donnot remove PIDFILE in case the `kill` fails.
+		kill $PID > /dev/null && rm -f $PIDFILE
+		
 	fi
 
 	return $?
 }
 
-audiablealarm_restart () {
-	audiablealarm_stop 
-	audiablealarm_start 
+audiblealarm_restart () {
+	audiblealarm_stop 
+	audiblealarm_start 
 
 	return $?
 }
 
-audiablealarm_status () {
+audiblealarm_status () {
   	if [ -f $PIDFILE ]; then
 		echo running
 	else
 		echo stopped
 	fi
 
-	return 0
+	return $OCF_SUCCESS
 }
 
-if
-  ( [ $# -eq 0 ] || [ $# -gt 1 ] )
-then
+audiblealarm_validate_all () {
+# Is there anything to check?
+	echo "Validate OK"
+	return $OCF_SUCCESS
+}
+if [ $# -ne 1 ]; then
   usage
-  exit 1
+  exit $OCF_ERR_ARGS
 fi
 
 case "$1" in
@@ -143,19 +149,22 @@ case "$1" in
 	    if [ "$us" = "$arg" ]; then
 	      # We should not start because we are on a host
 	      # listed in our argument list.
-              exit 0
+              exit $OCF_SUCCESS
 	    fi
 	  done
-	audiablealarm_start
+	audiblealarm_start
 	;;
   stop)
-	audiablealarm_stop
+	audiblealarm_stop
 	;;
   restart)
-	audiablealarm_restart 
+	audiblealarm_restart 
 	;;
   status|monitor)
-	audiablealarm_status 
+	audiblealarm_status 
+	;;
+  validate-all)
+	audiblealarm_validate_all
 	;;
   usage)
 	usage 
@@ -164,7 +173,7 @@ case "$1" in
 
   *)
 	usage
-	exit $OCF_ERR_UNIMPLEMENTED
+	exit $OCF_ERR_ARGS
 	;;
 esac
 
diff --git a/heartbeat/Delay.in b/heartbeat/Delay.in
--- a/heartbeat/Delay.in
+++ b/heartbeat/Delay.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-#	$Id: Delay.in,v 1.2 2005/05/05 13:40:10 alan Exp $
+#	$Id: Delay.in,v 1.3 2005/07/11 09:00:24 sunjd Exp $
 #
 #	This script is a test resource for introducing delay.
 #
@@ -32,8 +32,8 @@ VLFILE="$VARLIB/rsctmp/Delay-${OCF_RESOURCE_INSTANCE}"
 
 usage() {
   cat <<-!
-	usage: $0 {start|stop|status|monitor}
-  	$Id: Delay.in,v 1.2 2005/05/05 13:40:10 alan Exp $
+	usage: $0 {start|stop|status|monitor|meta-data|validate-all}
+  	$Id: Delay.in,v 1.3 2005/07/11 09:00:24 sunjd Exp $
 	!
 }
 
@@ -41,7 +41,7 @@ meta_data() {
 	cat <<END
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
-<resource-agent name="Delay" version="0.9">
+<resource-agent name="Delay">
 <version>1.0</version>
 
 <longdesc lang="en">
@@ -84,6 +84,7 @@ Defaults to "startdelay" if unspecified.
 <action name="status" depth="0" timeout="30" interval="10" start-delay="30" />
 <action name="monitor" depth="0" timeout="30" interval="10" start-delay="30" />
 <action name="meta-data" timeout="5" />
+<action name="validate-all" timeout="5" />
 </actions>
 </resource-agent>
 END
@@ -106,6 +107,7 @@ Delay_Status() {
 }
 
 Delay_Monitor() {
+  Delay_Validate_All -q
   sleep $OCF_RESKEY_mondelay
   Delay_Status
 }
@@ -117,6 +119,7 @@ Delay_Start() {
     echo "Delay already running."
     return $OCF_SUCCESS
   else
+    Delay_Validate_All -q
     touch "$VLFILE"
     rc=$?
     sleep $OCF_RESKEY_startdelay
@@ -133,6 +136,7 @@ Delay_Stop() {
   if
     Delay_stat
   then
+    Delay_Validate_All -q
     unlink "$VLFILE"
     rc=$?
     sleep $OCF_RESKEY_stopdelay
@@ -148,9 +152,46 @@ Delay_Stop() {
   fi
 }
 
-if
-  ( [ $# -eq 0 ] || [ $# -gt 1 ] )
-then
+# Check if all the arguments are valid numbers, a string is considered valid if:
+# 1. It does not contain any character but digits and period ".";
+# 2. The period "." does not occur more than once
+
+Are_Valid_Numbers() {
+  for i in "$@"; do
+	echo $i |grep -v [^0-9.] |grep -q -v [.].*[.]
+	if test $? -ne 0; then
+	  return $OCF_ERR_ARGS
+	fi
+  done
+  return $OCF_SUCCESS
+}
+
+Delay_Validate_All() {
+# Be quiet when specified -q option _and_ validation succeded
+  getopts "q" option
+
+  if test $option = "q"; then
+	quiet=yes
+  else
+	quiet=no
+  fi
+  shift $(($OPTIND -1))
+
+  if Are_Valid_Numbers $OCF_RESKEY_startdelay $OCF_RESKEY_stopdelay \
+	$OCF_RESKEY_mondelay; then
+    if test $quiet = "no"; then
+	echo "Validate OK"
+    fi
+# _Return_ on validation success
+	return $OCF_SUCCESS
+  else
+	echo "Some of the instance parameters are invalid"
+# _Exit_ on validation failure
+	exit $OCF_ERR_ARGS
+  fi
+}
+
+if [ $# -ne 1 ]; then
   usage
   exit $OCF_ERR_ARGS
 fi
@@ -171,11 +212,13 @@ case $1 in
 			;;
   status)		Delay_Status
 			;;
+  validate-all)		Delay_Validate_All
+			;;
   usage)		usage
 			exit $OCF_SUCCESS
 			;;
   *)			usage
-			exit $OCF_ERR_UNIMPLEMENTED
+			exit $OCF_ERR_ARGS
 			;;
 esac
 exit $?
