Fixed a bug in the DB2 resource agent: Incorrect exit codes for both status and monitor operation - for the case where DB2 was stopped.  This doesn't affect R1-style configurations - since it treats all non-zero return codes as equivalent.
--HG--
extra : convert_revision : 968e8f8e995e38021edec078a58f91bcc4a1ea7f

diff --git a/heartbeat/db2.in b/heartbeat/db2.in
--- a/heartbeat/db2.in
+++ b/heartbeat/db2.in
@@ -357,11 +357,18 @@ case "$1" in
 		  exit $OCF_SUCCESS
 		else
 		  echo DB2 UDB instance $instance is stopped
-		  exit $OCF_NOT_RUNNING
+		  exit 3  # status: stopped exit code is 3
 		fi
 		;;
 
-  monitor)	db2_monitor $instance
+  monitor)	
+		if
+		  db2_status $instance
+		then
+		  db2_monitor $instance
+		else
+		  exit $OCF_NOT_RUNNING
+		fi
 		exit $?;;
 
   validate-all)	# OCF_RESKEY_instance has already checked within db2info(),
