fixed PR 1773 comments

diff --git a/heartbeat/dnsupdate.in b/heartbeat/dnsupdate.in
--- a/heartbeat/dnsupdate.in
+++ b/heartbeat/dnsupdate.in
@@ -14,9 +14,9 @@
 # Parameter defaults
 
 OCF_RESKEY_hostname_default=""
-OCF_RESKEY_cname_default=""
-OCF_RESKEY_type_default=""
+OCF_RESKEY_type_default="A"
 OCF_RESKEY_ip_default=""
+OCF_RESKEY_cname_default=""
 OCF_RESKEY_ttl_default="300"
 OCF_RESKEY_keyfile_default=""
 OCF_RESKEY_server_default=""
@@ -50,7 +50,7 @@ meta_data() {
 	cat <<END
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
-<resource-agent name="dnsupdate2" version="1.0">
+<resource-agent name="dnsupdate" version="1.0">
 <version>1.0</version>
 
 <longdesc lang="en">
@@ -69,15 +69,7 @@ or alias whose hostname will need to be updated (in case of type=CNAME).
 <content type="string" default="${OCF_RESKEY_hostname_default}" />
 </parameter>
 
-<parameter name="cname" unique="1" required="0">
-<longdesc lang="en">
-The CNAME whose hostname address will need to be updated.
-</longdesc>
-<shortdesc lang="en">CNAME to update</shortdesc>
-<content type="string" default="${OCF_RESKEY_cname_default}" />
-</parameter>
-
-<parameter name="type" unique="1" required="1">
+<parameter name="type" unique="0" required="0">
 <longdesc lang="en">
 The type of DNS record that need to be updated (A or CNAME).
 </longdesc>
@@ -91,6 +83,14 @@ IP address to set.
 </longdesc>
 <shortdesc lang="en">IP address to set</shortdesc>
 <content type="string" default="${OCF_RESKEY_ip_default}" />
+</parameter>
+
+<parameter name="cname" unique="0" required="0">
+<longdesc lang="en">
+The CNAME whose hostname address will need to be updated.
+</longdesc>
+<shortdesc lang="en">CNAME to update</shortdesc>
+<content type="string" default="${OCF_RESKEY_cname_default}" />
 </parameter>
 
 <parameter name="ttl" unique="0" required="0">
@@ -181,12 +181,12 @@ dnsupdate_status() {
 		return $OCF_NOT_RUNNING
 		;;
 	CNAME)
-	        local record=$(dig ${dig_opts} ${cname}. CNAME +short 2>/dev/null)
-	        if [ "$record" = "${hostname}." ]; then
-	                return $OCF_SUCCESS
-	        fi
-	        return $OCF_NOT_RUNNING
-        	;;
+		local record=$(dig ${dig_opts} ${cname}. CNAME +short 2>/dev/null)
+		if [ "$record" = "${hostname}." ]; then
+			return $OCF_SUCCESS
+		fi
+		return $OCF_NOT_RUNNING
+		;;
 	esac
 
 }
@@ -220,21 +220,21 @@ dnsupdate_start() {
 		;;
 
 	CNAME)
-                if dnsupdate_status ; then
-                        ocf_log info "$cname already is an alias to $hostname"
-                        return $OCF_SUCCESS
-                fi
-
-                ocf_log info "Updating DNS records for $cname"
-
-                (
-                if [ -n "$dns_server" ]; then
-                        echo "server ${dns_server} ${dns_serverport}"
-                fi
-                echo "update delete $cname CNAME"
-                echo "update add $cname ${OCF_RESKEY_ttl} CNAME $hostname"
-                echo "send"
-                ) | nsupdate ${nsupdate_opts}
+		if dnsupdate_status ; then
+			ocf_log info "$cname already is an alias to $hostname"
+			return $OCF_SUCCESS
+		fi
+		
+		ocf_log info "Updating DNS records for $cname"
+		
+		(
+		if [ -n "$dns_server" ]; then
+			echo "server ${dns_server} ${dns_serverport}"
+		fi
+		echo "update delete $cname CNAME"
+		echo "update add $cname ${OCF_RESKEY_ttl} CNAME $hostname"
+		echo "send"
+		) | nsupdate ${nsupdate_opts}
 	        ;;
 
 	esac
@@ -249,40 +249,39 @@ dnsupdate_stop() {
 	case $type in
 	A)
 		if ocf_is_true "${OCF_RESKEY_unregister_on_stop}" && dnsupdate_status ; then
-		        ocf_log info "Unregistering $hostname with $ip from DNS server"
-		        (
-		        if [ -n "$dns_server" ]; then
-		                echo "server ${dns_server} ${dns_serverport}"
-		        fi
-		        echo "update delete $hostname A $ip"
-		        echo "send"
-		        ) | nsupdate ${nsupdate_opts}
-		
-		        dnsupdate_monitor
-		        if [ $? -ne $OCF_NOT_RUNNING ]; then
-		                ocf_log warn "Unregistering failed!"
-		        fi
+			ocf_log info "Unregistering $hostname with $ip from DNS server"
+			(
+			if [ -n "$dns_server" ]; then
+				echo "server ${dns_server} ${dns_serverport}"
+			fi
+			echo "update delete $hostname A $ip"
+			echo "send"
+			) | nsupdate ${nsupdate_opts}
+			
+			dnsupdate_monitor
+			if [ $? -ne $OCF_NOT_RUNNING ]; then
+				ocf_log warn "Unregistering failed!"
+			fi
 		fi
 		return $OCF_SUCCESS
 		;;
 	CNAME)
-                if ocf_is_true "${OCF_RESKEY_unregister_on_stop}" && dnsupdate_status ; then
-                        ocf_log info "Unregistering $cname with $hostname from DNS server"
-                        (
-                        if [ -n "$dns_server" ]; then
-                                echo "server ${dns_server} ${dns_serverport}"
-                        fi
-                        echo "update delete $cname CNAME"
-                        echo "send"
-                        ) | nsupdate ${nsupdate_opts}
-
-                        dnsupdate_monitor
-                        if [ $? -ne $OCF_NOT_RUNNING ]; then
-                                ocf_log warn "Unregistering failed!"
-                        fi
-                fi
-                return $OCF_SUCCESS
-
+		if ocf_is_true "${OCF_RESKEY_unregister_on_stop}" && dnsupdate_status ; then
+			ocf_log info "Unregistering $cname with $hostname from DNS server"
+			(
+			if [ -n "$dns_server" ]; then
+				echo "server ${dns_server} ${dns_serverport}"
+			fi
+			echo "update delete $cname CNAME"
+			echo "send"
+			) | nsupdate ${nsupdate_opts}
+			
+			dnsupdate_monitor
+			if [ $? -ne $OCF_NOT_RUNNING ]; then
+				ocf_log warn "Unregistering failed!"
+			fi
+		fi
+		return $OCF_SUCCESS
 		;;
 	esac
 }
@@ -314,10 +313,10 @@ dnsupdate_validate() {
 		exit $OCF_ERR_CONFIGURED
 	fi
 	#added support for CNAME
-        if [ -z "$type" ]; then
-                ocf_log err "No TYPE specified."
-                exit $OCF_ERR_CONFIGURED
-        fi
+	if [ -z "$type" ]; then
+		ocf_log err "No TYPE specified."
+		exit $OCF_ERR_CONFIGURED
+	fi
 	#
 	if ! ocf_is_decimal $OCF_RESKEY_ttl ; then
 		ocf_log err "ttl $OCF_RESKEY_ttl is not valid"
@@ -379,5 +378,4 @@ validate-all)	# We've already run this
 		;;
 esac
 exit $?
-
 
