Major changes.  Fixed several functions that just returned true with very little checking.  Changed to using sysfs as much as possible, vs. grepping the output of the ip command. Sysfs is more reliable.

diff --git a/heartbeat/ethmonitor b/heartbeat/ethmonitor
--- a/heartbeat/ethmonitor
+++ b/heartbeat/ethmonitor
@@ -10,6 +10,8 @@
 # Copyright (c) 2011 Robert Euhus, Alexander Krauth, Lars Marowsky-Brée
 #                    All Rights Reserved.
 #
+# Major overhaul by Nik Martin 
+#
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of version 2 of the GNU General Public License as
 # published by the Free Software Foundation.
@@ -34,7 +36,7 @@
 #	OCF_RESKEY_interface
 #	OCF_RESKEY_multiplicator
 #	OCF_RESKEY_name
-#       OCF_RESKEY_repeat_count
+#  OCF_RESKEY_repeat_count
 #	OCF_RESKEY_repeat_interval
 #	OCF_RESKEY_pktcnt_timeout
 #	OCF_RESKEY_arping_count
@@ -59,20 +61,30 @@ meta_data() {
 <version>1.2</version>
 
 <longdesc lang="en">
-Monitor the vitality of a local network interface.
+Monitor the availability of a local network interface at layer 2 (link/carrier).
 
-You may setup this RA as a clone resource to monitor the network interfaces on different nodes, with the same interface name.
-This is not related to the IP adress or the network on which a interface is configured.
-You may use this RA to move resources away from a node, which has a faulty interface or prevent moving resources to such a node.
-This gives you independend control of the resources, without involving cluster intercommunication. But it requires your nodes to have more than one network interface.
+You may setup this RA as a clone resource to monitor the network interfaces on 
+different nodes, with the same interface name. This is not related to the IP 
+adress or the network on which a interface is configured.
 
-The resource configuration requires a monitor operation, because the monitor does the main part of the work.
-In addition to the resource configuration, you need to configure some location contraints, based on a CIB attribute value.
+You may use this RA to move resources away from a node which has a faulty 
+interface or link or prevent moving resources to such a node. This gives you 
+independent control of the resources, without involving cluster intercommunication,
+but it requires your nodes to have more than one network interface.
+
+The resource configuration requires a monitor operation, because the monitor 
+does the main part of the work. In addition to the resource configuration, you 
+need to configure some location contraints, based on a CIB attribute value.
 The name of the attribute value is configured in the 'name' option of this RA.
 
 Example constraint configuration:
+
 location loc_connected_node my_resource_grp \
-        rule $id="rule_loc_connected_node" -INF: ethmonitor eq 0
+        rule $id="rule_loc_connected_node" ethmonitor-eth0: defined ethmonitor-eth0
+        
+This contstraint uses the value of the attribute ethmonitor-eth0 as the test,
+so the node with the highest score wins. Make sure you have a multiplier to 
+add enough weight to the score.
 
 The ethmonitor works in 3 different modes to test the interface vitality.
 1. call ip to see if the link status is up (if link is down -> error)
@@ -93,7 +105,8 @@ The name of the network interface which should be monitored (e.g. eth0).
 
 <parameter name="name" unique="1">
 <longdesc lang="en">
-The name of the CIB attribute to set.  This is the name to be used in the constraints. Defaults to "ethmonitor-'interface_name'".
+The name of the CIB attribute to set.  This is the name to be used in the 
+constraints. Defaults to "ethmonitor-eth[interface]'".
 </longdesc>
 <shortdesc lang="en">Attribute name</shortdesc>
 <content type="string" default=""/>
@@ -101,7 +114,7 @@ The name of the CIB attribute to set.  This is the name to be used in the constr
 
 <parameter name="multiplier" unique="0" >
 <longdesc lang="en">
-Multiplier for the value of the CIB attriobute specified in parameter name. 
+Multiplier for the value of the CIB attribute specified in parameter name. 
 </longdesc>
 <shortdesc lang="en">Multiplier for result variable</shortdesc>
 <content type="integer" default="1"/>
@@ -109,10 +122,12 @@ Multiplier for the value of the CIB attriobute specified in parameter name.
 
 <parameter name="repeat_count">
 <longdesc lang="en">
-Specify how often the interface will be monitored, before the status is set to failed. You need to set the timeout of the monitoring operation to at least repeat_count * repeat_interval
+Specify how often the interface will be monitored, before the status is set to 
+failed. You need to set the timeout of the monitoring operation to at least 
+repeat_count * repeat_interval.
 </longdesc>
 <shortdesc lang="en">Monitor repeat count</shortdesc>
-<content type="integer" default="5"/>
+<content type="integer" default="1"/>
 </parameter>
 
 <parameter name="repeat_interval">
@@ -120,12 +135,13 @@ Specify how often the interface will be monitored, before the status is set to f
 Specify how long to wait in seconds between the repeat_counts.
 </longdesc>
 <shortdesc lang="en">Monitor repeat interval in seconds</shortdesc>
-<content type="integer" default="10"/>
+<content type="integer" default="5"/>
 </parameter>
 
 <parameter name="pktcnt_timeout">
 <longdesc lang="en">
-Timeout for the RX packet counter. Stop listening for packet counter changes after the given number of seconds.
+Timeout for the RX packet counter. Stop listening for packet counter changes 
+after the given number of seconds.
 </longdesc>
 <shortdesc lang="en">packet counter timeout</shortdesc>
 <content type="integer" default="5"/>
@@ -143,7 +159,8 @@ Usually one ARP REQUEST (arping) is send
 <parameter name="arping_timeout">
 <longdesc lang="en">
 Time in seconds to wait for ARP REQUESTs (all packets of arping_count).
-This is to limit the time for arp requests, to be able to send requests to more than one node, without running in the monitor operation timeout.
+This is to limit the time for arp requests, to be able to send requests to more 
+than one node, without running in the monitor operation timeout.
 </longdesc>
 <shortdesc lang="en">Timeout for arpings per IP</shortdesc>
 <content type="integer" default="1"/>
@@ -151,7 +168,8 @@ This is to limit the time for arp requests, to be able to send requests to more 
 
 <parameter name="arping_cache_entries">
 <longdesc lang="en">
-Maximum number of IPs from ARP cache list to check for ARP REQUEST (arping) answers. Newest entries are tried first.
+Maximum number of IPs from ARP cache list to check for ARP REQUEST (arping) 
+answers. Newest entries are tried first.
 </longdesc>
 <shortdesc lang="en">Number of ARP cache entries to try</shortdesc>
 <content type="integer" default="5"/>
@@ -206,45 +224,47 @@ if_init() {
 	    validate-all) ocf_log err "Interface $NIC does not exist"
                             exit $OCF_ERR_CONFIGURED;;
 	    *)   	    ocf_log warn "Interface $NIC does not exist"
-                            ## It might be a bond interface which is temporarily not available, therefore we want to continue here
+        ## It might be a bond interface which is temporarily not available, 
+        ## therefore we want to continue here
 	                    ;;
 	  esac
 	fi
 
-	: ${OCF_RESKEY_multiplier:="1"}
+	: ${OCF_RESKEY_multiplier:=1}
 	if ! ocf_is_decimal "$OCF_RESKEY_multiplier"; then
 		ocf_log err "Invalid OCF_RESKEY_multiplier [$OCF_RESKEY_multiplier]"
 		exit $OCF_ERR_CONFIGURED
 	fi
 	
-	ATTRNAME=${OCF_RESKEY_name:-"ethmonitor-$NIC"}
+	: ${OCF_RESKEY_name:="ethmonitor-$NIC"}
 	
-        REP_COUNT=${OCF_RESKEY_repeat_count:-5}
+	#we have to assign REP_COUNT, since we decrement it
+   REP_COUNT=${OCF_RESKEY_repeat_count:=1}
 	if ! ocf_is_decimal "$REP_COUNT" -o [ $REP_COUNT -lt 1 ]; then
 		ocf_log err "Invalid OCF_RESKEY_repeat_count [$REP_COUNT]"
 		exit $OCF_ERR_CONFIGURED
         fi
-	REP_INTERVAL_S=${OCF_RESKEY_repeat_interval:-10}
-	if ! ocf_is_decimal "$REP_INTERVAL_S"; then
-		ocf_log err "Invalid OCF_RESKEY_repeat_interval [$REP_INTERVAL_S]"
+	: ${OCF_RESKEY_repeat_interval:=5}
+	if ! ocf_is_decimal "$OCF_RESKEY_repeat_interval"; then
+		ocf_log err "Invalid OCF_RESKEY_repeat_interval [$OCF_RESKEY_repeat_interval]"
 		exit $OCF_ERR_CONFIGURED
 	fi
-	: ${OCF_RESKEY_pktcnt_timeout:="5"}
+	: ${OCF_RESKEY_pktcnt_timeout:=5}
 	if ! ocf_is_decimal "$OCF_RESKEY_pktcnt_timeout"; then
 		ocf_log err "Invalid OCF_RESKEY_pktcnt_timeout [$OCF_RESKEY_pktcnt_timeout]"
 		exit $OCF_ERR_CONFIGURED
 	fi
-	: ${OCF_RESKEY_arping_count:="1"}
+	: ${OCF_RESKEY_arping_count:=1}
 	if ! ocf_is_decimal "$OCF_RESKEY_arping_count"; then
 		ocf_log err "Invalid OCF_RESKEY_arping_count [$OCF_RESKEY_arping_count]"
 		exit $OCF_ERR_CONFIGURED
 	fi
-	: ${OCF_RESKEY_arping_timeout:="1"}
+	: ${OCF_RESKEY_arping_timeout:=1}
 	if ! ocf_is_decimal "$OCF_RESKEY_arping_timeout"; then
 		ocf_log err "Invalid OCF_RESKEY_arping_timeout [$OCF_RESKEY_arping_count]"
 		exit $OCF_ERR_CONFIGURED
 	fi
-	: ${OCF_RESKEY_arping_cache_entries:="5"}
+	: ${OCF_RESKEY_arping_cache_entries:=5}
 	if ! ocf_is_decimal "$OCF_RESKEY_arping_cache_entries"; then
 		ocf_log err "Invalid OCF_RESKEY_arping_cache_entries [$OCF_RESKEY_arping_cache_entries]"
 		exit $OCF_ERR_CONFIGURED
@@ -253,33 +273,49 @@ if_init() {
 }
 
 # get the link status on $NIC
-# asks ip about running (up) interfaces, returns the number of matching interface names that are up
+# asks sysfs about the operstate of interface, 0 (up) and 1 (down) 
 get_link_status () {
-	$IP2UTIL -o link show up dev "$NIC" | grep -c "$NIC"
+
+   if [[ -e "/sys/class/net/$NIC/operstate" ]]
+	   then nictest=$(cat /sys/class/net/$NIC/operstate)
+	else #interface does not exist, so it cant be up
+	   ocf_log debug "$NIC does not exist, so FAIL"
+	   return 1 
+	fi
+	
+	if [ $nictest = "down" ]
+	then 
+	   ocf_log debug "$NIC operstate is $nictest"
+	   return 1 #interface is down
+	else
+	   ocf_log debug "$NIC operstate is $nictest"
+	   return 0 #interface is up
+	 fi
+	  
 }
 
 # returns the number of received rx packets on $NIC
 get_rx_packets () {
-	ocf_log debug "$IP2UTIL -o -s link show dev $NIC"
-	$IP2UTIL -o -s link show dev "$NIC" \
-		| sed 's/.* RX: [^0-9]*[0-9]* *\([0-9]*\) .*/\1/'
-		# the first number after RX: ist the # of bytes ,
-		# the second is the # of packets received
+   rx_pkts=$(cat /sys/class/net/$NIC/statistics/rx_packets)
+	echo "$rx_pkts"
 }
 
 # watch for packet counter changes for max. OCF_RESKEY_pktcnt_timeout seconds
-# returns immedeately with return code 0 if any packets were received
+# returns immediately with return code 0 if any packets were received
 # otherwise 1 is returned
 watch_pkt_counter () {
+   ocf_log debug "in watch_pkt_counter"
 	local RX_PACKETS_NEW
 	local RX_PACKETS_OLD
-	RX_PACKETS_OLD="`get_rx_packets`"
-	for n in `seq $(( $OCF_RESKEY_pktcnt_timeout * 10 ))`; do
+	RX_PACKETS_OLD=$(get_rx_packets)
+	for n in `seq $(( $OCF_RESKEY_pktcnt_timeout * 10 ))`
+	do
 		sleep 0.1
-		RX_PACKETS_NEW="`get_rx_packets`"
-		ocf_log debug "RX_PACKETS_OLD: $RX_PACKETS_OLD    RX_PACKETS_NEW: $RX_PACKETS_NEW"
-		if [ "$RX_PACKETS_OLD" -ne "$RX_PACKETS_NEW" ]; then
-			ocf_log debug "we received some packets."
+		RX_PACKETS_NEW=$(get_rx_packets)
+		if [[ $RX_PACKETS_OLD -ne $RX_PACKETS_NEW ]]
+		then
+			ocf_log debug "we received some packets"
+			ocf_log debug "RX_PACKETS_OLD:$RX_PACKETS_OLD RX_PACKETS_NEW:$RX_PACKETS_NEW"
 			return 0
 		fi
 	done
@@ -322,10 +358,10 @@ do_arping () {
 # the tests for higher check levels are run.
 #
 if_check () {
-	# always check link status first
-	link_status="`get_link_status`"
-	ocf_log debug "link_status: $link_status (1=up, 0=down)"
-        [ $link_status -eq 0 ] && return $OCF_NOT_RUNNING
+	
+	#check if you have a link
+	ocf_log debug "check link_status"
+	get_link_status && return $OCF_SUCCESS
 
 	# watch for packet counter changes
 	ocf_log debug "watch for packet counter changes" 
@@ -337,37 +373,28 @@ if_check () {
 		do_arping $ip && return $OCF_SUCCESS
 	done
 
-	# watch for packet counter changes in promiscios mode
-#	ocf_log debug "watch for packet counter changes in promiscios mode" 
-	# be sure switch off promiscios mode in any case
-	# TODO: check first, wether promisc is already on and leave it untouched.
-#	trap "$IP2UTIL link set dev $NIC promisc off; exit" INT TERM EXIT
-#		$IP2UTIL link set dev $NIC promisc on
-#		watch_pkt_counter && return $OCF_SUCCESS
-#		$IP2UTIL link set dev $NIC promisc off
-#	trap - INT TERM EXIT
-
 	# looks like it's not working (for whatever reason)
-	return $OCF_NOT_RUNNING
+	return $OCF_ERR_GENERIC
 }
 
-#######################################################################
 
 if_usage() {
 	cat <<END
 usage: $0 {start|stop|status|monitor|validate-all|meta-data}
-
+crm_simulate -S -L -VVV
 Expects to have a fully populated OCF RA-compliant environment set.
 END
 }
 
 set_cib_value() {
-    local score=`expr $1 \* $OCF_RESKEY_multiplier`
-    attrd_updater -n $ATTRNAME -v $score -q
+    
+    let score=$1*$OCF_RESKEY_multiplier
+    
+    attrd_updater -n $OCF_RESKEY_name -v $score -q
     local rc=$?
     case $rc in
-        0) ocf_log debug "attrd_updater: Updated $ATTRNAME = $score" ;;
-        *) ocf_log warn "attrd_updater: Could not update $ATTRNAME = $score: rc=$rc";;
+        0) ocf_log debug "attrd_updater: Updated $OCF_RESKEY_name = $score" ;;
+        *) ocf_log warn "attrd_updater: Could not update $OCF_RESKEY_name = $score: rc=$rc";;
     esac
     return $rc
 }
@@ -387,14 +414,14 @@ if_monitor() {
     local sleep_time
     while [ $mon_rc -ne $OCF_SUCCESS -a $REP_COUNT -gt 0 ]
     do
-      start_time=`date +%s%N`
+      start_time=$(date +%s%N)
       if_check
       mon_rc=$?
-      REP_COUNT=$(( $REP_COUNT - 1 ))
+      (( REP_COUNT-- ))
       if [ $mon_rc -ne $OCF_SUCCESS -a $REP_COUNT -gt 0 ]; then
         ocf_log warn "Monitoring of $OCF_RESOURCE_INSTANCE failed, $REP_COUNT retries left."
 	end_time=`date +%s%N`
-	sleep_time=`echo "scale=9; ( $start_time + ( $REP_INTERVAL_S * 1000000000 ) - $end_time ) / 1000000000" | bc -q 2> /dev/null`
+	sleep_time=`echo "scale=9; ( $start_time + ( $OCF_RESKEY_repeat_interval * 1000000000 ) - $end_time ) / 1000000000" | bc -q 2> /dev/null`
         sleep $sleep_time 2> /dev/null
         runs=$(($runs + 1))
       fi
@@ -414,8 +441,10 @@ if_monitor() {
       attr_rc=$?
     fi
 
-    ## The resource should not fail, if the interface is down. It should fail, if the update of the CIB variable has errors.
-    ## To react on the interface failure you must use constraints based on the CIB variable value, not on the resource itself.
+    ## The resource should not fail, if the interface is down. It should fail, 
+    ## if the update of the CIB variable has errors. To react on the interface 
+    ## failure you must use constraints based on the CIB variable value, not on 
+    ## the resource itself.
     exit $attr_rc
 }
 
@@ -439,7 +468,7 @@ case $__OCF_ACTION in
 start)		ha_pseudo_resource $OCF_RESOURCE_INSTANCE start
 		exit $?
 		;;
-stop)		attrd_updater -D -n $ATTRNAME
+stop)		attrd_updater -D -n $OCF_RESKEY_name
                 ha_pseudo_resource $OCF_RESOURCE_INSTANCE stop
 		exit $?
 		;;
@@ -452,3 +481,4 @@ validate-all)	exit $?
 		exit $OCF_ERR_UNIMPLEMENTED
 		;;
 esac
+
