Medium: exportfs: cleanup exportfs cache on stop (bnc#770210)

diff --git a/heartbeat/exportfs b/heartbeat/exportfs
--- a/heartbeat/exportfs
+++ b/heartbeat/exportfs
@@ -239,6 +239,20 @@ exportfs_start ()
 	return $OCF_SUCCESS
 }
 
+cleanup_export_cache() {
+	# see if the cache is blocking unexport
+	local contentfile=/proc/net/rpc/nfsd.export/content
+	local fsid_re="fsid=$OCF_RESKEY_fsid,"
+	local i=1
+	while :; do
+		fgrep -q "$fsid_re" $contentfile ||
+			break
+		ocf_log info "Cleanup export cache ... (try $i)"
+		ocf_run exportfs -f
+		sleep 0.5
+		let i=$i+1
+	done
+}
 exportfs_stop ()
 {
 	exportfs_monitor
@@ -280,12 +294,13 @@ exportfs_stop ()
 	fi
 
 	if [ $rc -eq 0 ]; then
+		cleanup_export_cache
 		ocf_log info "Un-exported file system"
 		return $OCF_SUCCESS
+	else
+		ocf_log err "Failed to un-export file system"
+		exit $OCF_ERR_GENERIC
 	fi
-
-	ocf_log err "Failed to un-export file system"
-	exit $OCF_ERR_GENERIC
 }
 
 exportfs_validate ()
