Clarified certain parameter error conditions with better messages. Also fixed the bug where it called findif all the time.
CVS patchset: 10068
CVS date: 2006/07/10 20:08:16

--HG--
extra : convert_revision : e6d27abe8352ecd564765a9fb3971b0ae1eaac74

diff --git a/heartbeat/IPaddr.in b/heartbeat/IPaddr.in
--- a/heartbeat/IPaddr.in
+++ b/heartbeat/IPaddr.in
@@ -216,36 +216,58 @@ ip_init() {
 		ocf_log err "You must be root for $__OCF_ACTION operation."
 		exit $OCF_ERR_PERM
 	fi
+	case $OCF_RESKEY_ip in
+	  "")	ocf_log err "Required parameter OCF_RESKEY_ip is missing"
+		exit $OCF_ERR_CONFIGURED;;
+          [0-9]*.*.*.*[0-9])		: OK;;
+	  *)	ocf_log err "Parameter OCF_RESKEY_ip [$OCF_RESKEY_ip] not an IP address"
+		exit $OCF_ERR_CONFIGURED;;
+        esac
+        case $__OCF_ACTION in
 
-        #
-        # $FINDIF can NOT deal with the condition of empty intermediate parameters.
-        #
-	if
-          [ ! -z "$OCF_RESKEY_netmask" -a -z "$OCF_RESKEY_cidr_netmask" ]
-        then
-          OCF_RESKEY_cidr_netmask=$OCF_RESKEY_netmask
-        fi
-	IFCMD="$FINDIF -C $OCF_RESKEY_ip"
-	if [ -n "$OCF_RESKEY_cidr_netmask" ]; then
-	    IFCMD="$IFCMD/$OCF_RESKEY_cidr_netmask"
-	    if [ -n "$OCF_RESKEY_nic" ]; then
-		IFCMD="$IFCMD/$OCF_RESKEY_nic"
-		if [ -n "$OCF_RESKEY_broadcast" ]; then
-		    IFCMD="$IFCMD/$OCF_RESKEY_broadcast"
+	  start)
+
+		IFCMD="$FINDIF -C $OCF_RESKEY_ip"
+		#
+		# $FINDIF can NOT deal with the condition of empty intermediate parameters.
+		#
+		if
+		  [ ! -z "$OCF_RESKEY_netmask" -a -z "$OCF_RESKEY_cidr_netmask" ]
+		then
+		  OCF_RESKEY_cidr_netmask=$OCF_RESKEY_netmask
 		fi
-	    fi
-	fi
+		IFCMD="$FINDIF -C $OCF_RESKEY_ip"
+		if
+		  [ -n "$OCF_RESKEY_cidr_netmask" ]
+		then
+		  IFCMD="$IFCMD/$OCF_RESKEY_cidr_netmask"
+		  if
+		    [ -n "$OCF_RESKEY_nic" ]
+		  then
+		    IFCMD="$IFCMD/$OCF_RESKEY_nic"
+		    if
+	              [ -n "$OCF_RESKEY_broadcast" ]
+		    then
+		      IFCMD="$IFCMD/$OCF_RESKEY_broadcast"
+		    fi
+		  fi
+		fi
 
-        NICINFO=`$IFCMD`
+		NICINFO=`$IFCMD`
+		rc=$?
 
-	if [ $? -eq 0 ]; then
-            OCF_RESKEY_nic=`echo "$NICINFO" | cut -f1`
-	    OCF_RESKEY_cidr_netmask=`echo "$NICINFO" | cut -f2 | cut -d ' ' -f2`
-	    OCF_RESKEY_broadcast=`echo "$NICINFO" | cut -f3 | cut -d ' ' -f2`
-	else
-	    ocf_log err "Failed: $IFCMD . Parameter error."
-  	    exit $OCF_ERR_GENERIC
-	fi
+		if
+		  [ $rc -eq 0 ]
+		then
+		  OCF_RESKEY_nic=`echo "$NICINFO" | cut -f1`
+		  OCF_RESKEY_cidr_netmask=`echo "$NICINFO" | cut -f2 | cut -d ' ' -f2`
+		  OCF_RESKEY_broadcast=`echo "$NICINFO" | cut -f3 | cut -d ' ' -f2`
+		else
+		  ocf_log err "$IFCMD failed [$rc]."
+		  exit $OCF_ERR_GENERIC
+		fi
+		;;
+	esac
 
 	LVS_SUPPORT=0
 	if [ $SYSTYPE = "Linux" -o $SYSTYPE = "SunOS" ]; then
@@ -276,7 +298,7 @@ ip_init() {
 	    : Directory $VLDIR now exists
 	else
 	    ocf_log err "Could not create \"$VLDIR/\"."
-  	    exit $OCF_ERR_GENERIC
+	    exit $OCF_ERR_GENERIC
 	fi
 }
 
@@ -351,11 +373,11 @@ find_interface_generic() {
 		$IFCONFIG | grep "$ipaddr" -B20 | grep "UP," | tail -n 1 | cut -d ":" -f 1
 		return 0;;
       *)
-    		: "comparing $ipaddr to $addr (from ifconfig)"
+		: "comparing $ipaddr to $addr (from ifconfig)"
 		case $addr in
 		  addr:$ipaddr)	echo $ifname; return $OCF_SUCCESS;;
 		  $ipaddr)	echo $ifname; return $OCF_SUCCESS;;
-    		esac
+		esac
 		continue;;
     esac
 
@@ -373,10 +395,10 @@ find_interface() {
     ipaddr="$1"
     case $SYSTYPE in
 	SunOS)
-	 	NIC=`find_interface_solaris $ipaddr`
+		NIC=`find_interface_solaris $ipaddr`
         ;;
       *)
-	 	NIC=`find_interface_generic $ipaddr`
+		NIC=`find_interface_generic $ipaddr`
        ;;
        esac
 
@@ -547,7 +569,7 @@ add_interface () {
 	  CMD="$IFCONFIG $iface inet $ipaddr netmask 255.255.255.255 alias"
 	  ;;
     *)		
-    	  CMD="$IFCONFIG $iface $ipaddr $netmask_text $broadcast"
+	  CMD="$IFCONFIG $iface $ipaddr $netmask_text $broadcast"
 	  ;;
   esac
 
@@ -611,7 +633,7 @@ ip_stop() {
 
   if test -f "$SENDARPPIDFILE"
   then
-  	cat "$SENDARPPIDFILE" | xargs kill
+	cat "$SENDARPPIDFILE" | xargs kill
 	rm -f "$SENDARPPIDFILE"
   fi
 
@@ -626,8 +648,8 @@ ip_stop() {
 
 	Linux|SunOS)
 		if [ -z "$NIC" ]; then
-    			: Requested interface not in use
-    			exit $OCF_SUCCESS
+			: Requested interface not in use
+			exit $OCF_SUCCESS
 
 		elif [ ${LVS_SUPPORT} = 1 ]; then 
 		    case $NIC in
@@ -636,12 +658,12 @@ ip_stop() {
 			    exit $OCF_SUCCESS
 			    ;;
 		    esac
-  		fi;;
+		fi;;
 	*)
 		if [ -z "$NIC" ]; then
-    			: Requested interface not in use
-    			exit $OCF_SUCCESS
-  		fi;;
+			: Requested interface not in use
+			exit $OCF_SUCCESS
+		fi;;
   esac
 
   if [ ! -z "${OCF_RESKEY_local_stop_script}" ]; then
@@ -666,10 +688,10 @@ ip_stop() {
   esac
 
   case $rc in
-    	0) 
+	0) 
 		ocf_log info "IP Address $OCF_RESKEY_ip released"
 		;;
-    	*) 	
+	*)	
 		ocf_log warn "IP Address $OCF_RESKEY_ip NOT released"
 		;;
   esac
@@ -699,14 +721,14 @@ ip_start() {
     SENDARPPIDFILE="$SENDARPPIDDIR/send_arp-$OCF_RESKEY_ip"
 
     if [ -n "$NIC_unique" ]; then
-  	: OK got interface [$NIC_unique] for $OCF_RESKEY_ip 
+	: OK got interface [$NIC_unique] for $OCF_RESKEY_ip 
     else
-  	exit $OCF_ERR_GENERIC
+	exit $OCF_ERR_GENERIC
     fi
     
     # This logic is mostly to support LVS (If I understand it correctly)
     if [ ${LVS_SUPPORT} = 1 ]; then
-       	case $NIC_unique in
+	case $NIC_unique in
 	    lo*) 
 		if [ x"$NIC_unique" = x"$NIC_current" ]; then
 		    # Its already "running" and not moving, nothing to do.
@@ -714,7 +736,7 @@ ip_start() {
 		    exit $OCF_ERR_GENERIC
 		fi;;
 	    *)   remove_conflicting_loopback "$OCF_RESKEY_ip" "$NIC_current";;
-    	esac
+	esac
     fi
     if [ ! -z "${OCF_RESKEY_local_start_script}" ]; then
 	if [ -x "${OCF_RESKEY_local_start_script}" ]; then
@@ -882,14 +904,13 @@ fi
   esac
 
 case $1 in
-  start)	ip_init; ip_start ;;
-  stop)	ip_init; ip_stop ;;
-  status)	ip_init; ip_status ;;
-  monitor)	ip_init; ip_monitor ;;
-  validate-all)	ip_init; ip_validate_all;;
   meta-data)	meta_data;;
-  usage)	usage; exit $OCF_SUCCESS;;
-  *)		usage
- 		exit $OCF_ERR_ARGS
+  start)	ip_init	&&	ip_start;;
+  stop)		ip_init	&&	ip_stop;;
+  status)	ip_init	&&	ip_status;;
+  monitor)	ip_init	&&	ip_monitor;;
+  validate-all)	ip_init	&&	ip_validate_all;;
+  usage)	usage;		exit $OCF_SUCCESS;;
+  *)		usage;		exit $OCF_ERR_ARGS
 		;;
 esac
