Medium: IPaddr2: really send arps in background if requested

diff --git a/heartbeat/IPaddr2 b/heartbeat/IPaddr2
--- a/heartbeat/IPaddr2
+++ b/heartbeat/IPaddr2
@@ -647,7 +647,7 @@ run_send_arp() {
 	fi
 	ocf_log info "$SENDARP $ARGS"
 	if ocf_is_true $OCF_RESKEY_arp_bg; then
-		($SENDARP $ARGS || ocf_log err "Could not send gratuitous arps" &) >&2
+		($SENDARP $ARGS || ocf_log err "Could not send gratuitous arps")& >&2
 	else
 		$SENDARP $ARGS || ocf_log err "Could not send gratuitous arps"
 	fi
@@ -669,7 +669,7 @@ run_send_ib_arp() {
 	ARGS="-q -c $OCF_RESKEY_arp_count -U -I $NIC $OCF_RESKEY_ip"
 	ocf_log info "ipoibarping $ARGS"
 	if ocf_is_true $OCF_RESKEY_arp_bg; then
-		(ipoibarping $ARGS || ocf_log err "Could not send gratuitous arps" &) >&2
+		(ipoibarping $ARGS || ocf_log err "Could not send gratuitous arps")& >&2
 	else
 		ipoibarping $ARGS || ocf_log err "Could not send gratuitous arps"
 	fi
