Linux Foundation bug 1505: Findif parsing is all screwed up unless all the parameters are passed, not defaulted.
I changed findif to use the OCF parameters that are passed to
both IPaddr and IPaddr2, which got rid of a bunch of ugly code
at the same time as fixing this bug.  Sounds like a win to me.

In the process I had to make IPaddr and IPaddr2 somewhat more consistent
than they had been - but not in an incompatible way, and this is also
a good thing.

--HG--
extra : convert_revision : 187c17c0769e7c659d519944b0821ea4939cd515

diff --git a/heartbeat/IPaddr2.in b/heartbeat/IPaddr2.in
--- a/heartbeat/IPaddr2.in
+++ b/heartbeat/IPaddr2.in
@@ -1,5 +1,6 @@
 #!/bin/sh
 #
+#	$Id: IPaddr2.in,v 1.24 2006/08/09 13:01:54 lars Exp $
 #
 #       OCF Resource Agent compliant IPaddr2 script.
 #
@@ -81,10 +82,13 @@ meta_data() {
 <version>1.0</version>
 
 <longdesc lang="en">
-OCF Resource Agent compliant IPaddr2 script.
-Implements Cluster Alias IP functionality.
+This Linux-specific resource manages IP alias IP addresses.
+It can add an IP alias, or remove one.
+In addition, it can implement Cluster Alias IP functionality
+if invoked as a clone resource.
 </longdesc>
-<shortdesc lang="en">OCF Resource Agent compliant IPaddr2 script.</shortdesc>
+
+<shortdesc lang="en">Manages virtual IPv4 addresses</shortdesc>
 
 <parameters>
 <parameter name="ip" unique="1" required="1">
@@ -268,10 +272,13 @@ ip_init() {
 	BASEIP="$OCF_RESKEY_ip"
 	BRDCAST="$OCF_RESKEY_broadcast"
 	NIC="$OCF_RESKEY_nic"
+        # Note: We had a version out there for a while which used
+        # netmask instead of cidr_netmask. Don't remove this aliasing code!
         if
           [ ! -z "$OCF_RESKEY_netmask" -a -z "$OCF_RESKEY_cidr_netmask" ]
         then
-          OCF_RESKEY_cidr_netmask=$OCF_RESKEY_netmask
+	  OCF_RESKEY_cidr_netmask=$OCF_RESKEY_netmask
+	  export OCF_RESKEY_cidr_netmask
         fi
 	NETMASK="$OCF_RESKEY_cidr_netmask"
 	IFLABEL="$OCF_RESKEY_iflabel"
@@ -303,20 +310,19 @@ ip_init() {
 
 	  
 	# Validation is performed in ip_validate()...
-
 	#
-	# $FINDIF can deal with the condition of empty intermediate parameters.
+	# $FINDIF now takes its parameters from the environment
 	#
-	NICINFO=`$FINDIF -C "$BASEIP/$NETMASK/$NIC/$BRDCAST"`
-
-	if [ $? -eq 0 ]; then
+	if
+	  NICINFO=`$FINDIF -C`
+        then
 	    NICINFO=`echo $NICINFO | sed -e 's/netmask\ //;s/broadcast\ //'`
 	    NIC=`echo "$NICINFO" | cut -d" " -f1`
 	    NETMASK=`echo "$NICINFO" | cut -d" " -f2`
 	    BRDCAST=`echo "$NICINFO" | cut -d" " -f3`
 	else
-	    ocf_log err "Failed: $FINDIF $BASEIP/$NETMASK/$NIC/$BRDCAST . Parameter error."
-  	    exit $OCF_ERR_GENERIC
+	    ocf_log err "[$FINDIF -C] failed"
+  	    exit $OCF_ERR_ARGS
 	fi
 	
 	SENDARPPIDFILE="$SENDARPPIDDIR/send_arp-$BASEIP"
