IPaddr2: support IPoIB gratuitous arps
This patch allows the configuration of a heartbeat based NFS export of
CXFS clients on a cluster using NFS/IPoIB.

It sends gratuitous arps usin IPoIB by using ipoibarping instead of
send_arp, which relies on libnet and doesn't know IB.

Signed-off-by: Ivan Rayner <ivanr@sgi.com>
Signed-off-by: Anibal Monsalve Salazar <anibal@sgi.com>

--HG--
extra : convert_revision : 6ec2b3fe81431eba46c776e46c2ba642515ff0a6

diff --git a/heartbeat/IPaddr2 b/heartbeat/IPaddr2
--- a/heartbeat/IPaddr2
+++ b/heartbeat/IPaddr2
@@ -522,6 +522,29 @@ run_send_arp() {
 	esac
 }
 
+#
+# Run ipoibarping to note peers about new Infiniband address
+#
+run_send_ib_arp() {
+	SENDIBARP="/sbin/ipoibarping"
+
+	if [ ! -x $SENDIBARP ] ; then
+		ocf_log err "Could not send gratuitous Infiniband arps: file not found: $SENDIBPARP"
+		return
+	fi
+
+	ARGS="-q -c  $ARP_REPEAT -U -I $NIC $BASEIP"
+	ocf_log info "$SENDIBARP $ARGS"
+	case $ARP_BACKGROUND in
+	yes)
+		($SENDIBARP $ARGS || ocf_log err "Could not send gratuitous arps" &) >&2
+		;;
+	*)
+		$SENDIBARP $ARGS || ocf_log err "Could not send gratuitous arps"
+		;;
+	esac
+}
+
 # Do we already serve this IP address?
 #
 # returns:
@@ -630,6 +653,9 @@ ip_start() {
 	case $NIC in
 	lo*)
 		: no need to run send_arp on loopback
+		;;
+	ib*)
+		run_send_ib_arp
 		;;
 	*)
 	    if [ -x $SENDARP ]; then
