Medium: iscsi: add try_recovery parameter
Loop in monitor in case the session exists, but is currently not
operational.

Thanks to Leandro Santinelli <liandrosg@gmail.com> for raising
this issue and contributing code (see
https://github.com/ClusterLabs/resource-agents/issues/103 for
more details).

diff --git a/heartbeat/iscsi b/heartbeat/iscsi
--- a/heartbeat/iscsi
+++ b/heartbeat/iscsi
@@ -32,6 +32,7 @@
 #	OCF_RESKEY_target: the iSCSI target (required)
 #	OCF_RESKEY_iscsiadm: iscsiadm program path (optional)
 #	OCF_RESKEY_discovery_type: discovery type (optional; default: sendtargets)
+#	OCF_RESKEY_try_recovery: wait for iSCSI recovery in monitor (optional; default: false)
 #
 # Initialization:
 
@@ -42,6 +43,7 @@
 OCF_RESKEY_udev_default="yes"
 OCF_RESKEY_iscsiadm_default="iscsiadm"
 OCF_RESKEY_discovery_type_default="sendtargets"
+OCF_RESKEY_try_recovery_default="false"
 
 : ${OCF_RESKEY_udev=${OCF_RESKEY_udev_default}}
 : ${OCF_RESKEY_iscsiadm=${OCF_RESKEY_iscsiadm_default}}
@@ -123,6 +125,19 @@ until a timeout occurs.
 </longdesc>
 <shortdesc lang="en">udev</shortdesc>
 <content type="string" default="${OCF_RESKEY_udev_default}" />
+</parameter>
+
+<parameter name="try_recovery" unique="0" required="0">
+<longdesc lang="en">
+If the iSCSI session exists but is currently inactive/broken,
+which is most probably due to network problems, the iSCSI layer
+will try to recover. If this parameter is set to true, we'll wait
+for the recovery to succeed. In that case the monitor operation
+can only time out so you should set the monitor op timeout
+attribute appropriately.
+</longdesc>
+<shortdesc lang="en">on error wait for iSCSI recovery in monitor</shortdesc>
+<content type="boolean" default="${OCF_RESKEY_try_recovery_default}" />
 </parameter>
 
 </parameters>
@@ -272,22 +287,33 @@ open_iscsi_remove() {
 open_iscsi_status() {
 	local target="$1"
 	local session_id conn_state outp
+	local msg_logged
 	session_id=`open_iscsi_get_session_id "$target"`
 	[ -z "$session_id" ] &&
 		return 1
-	outp=`$iscsiadm -m session -r $session_id -P 1` ||
-		return 2
-	conn_state=`echo "$outp" | sed -n '/Connection State/s/.*: //p'`
-	# some drivers don't return connection state, in that case
-	# we'll assume that we're still connected
-	case "$conn_state" in
-		"LOGGED IN") return 0;;
-		"Unknown"|"") return 0;; # this is also probably OK
-		*) # failed
-			ocf_log err "iscsiadm output: $outp"
+	while :; do
+		outp=`$iscsiadm -m session -r $session_id -P 1` ||
 			return 2
-		;;
-	esac
+		conn_state=`echo "$outp" | sed -n '/Connection State/s/.*: //p'`
+		# some drivers don't return connection state, in that case
+		# we'll assume that we're still connected
+		case "$conn_state" in
+			"LOGGED IN") return 0;;
+			"Unknown"|"") return 0;; # this is also probably OK
+			*) # failed
+				if [ "$__OCF_ACTION" = monitor ] && ocf_is_true $OCF_RESKEY_try_recovery; then
+					if [ -z "$msg_logged" ]; then
+						ocf_log warning "connection state $conn_state, waiting for recovery..."
+						msg_logged=1
+					fi
+					sleep 1
+				else
+					ocf_log err "iscsiadm output: $outp"
+					return 2
+				fi
+			;;
+		esac
+	done
 }
 
 disk_discovery() {
