separate lio and lio-t start

diff --git a/heartbeat/iSCSITarget b/heartbeat/iSCSITarget
--- a/heartbeat/iSCSITarget
+++ b/heartbeat/iSCSITarget
@@ -263,23 +263,15 @@ iSCSITarget_start() {
 		    --user=${OCF_RESKEY_incoming_username} || exit $OCF_ERR_GENERIC
 	    fi
 	    ;;
-	lio | lio-t)
+	lio)
 	    # lio distinguishes between targets and target portal
 	    # groups (TPGs). We will always create one TPG, with the
 	    # number 1. In lio, creating a network portal
 	    # automatically creates the corresponding target if it
 	    # doesn't already exist.
 	    for portal in ${OCF_RESKEY_portals}; do
-                if [ "$OCF_RESKEY_implementation" == "lio" ] ; then
-                    ocf_run lio_node --addnp ${OCF_RESKEY_iqn} 1 \
-                        ${portal} || exit $OCF_ERR_GENERIC
-                else
-                    ocf_run targetcli /iscsi create ${OCF_RESKEY_iqn} || exit $OCF_ERR_GENERIC
-                    if [ $portal != ${OCF_RESKEY_portals_default} ] ; then
-                        IFS=':' read -a sep_portal <<< "$portal"
-                        ocf_run targetcli /iscsi/${OCF_RESKEY_iqn}/tpg1/portals create "${sep_portal[0]}" "${sep_portal[1]}" || exit $OCF_ERR_GENERIC
-                    fi
-                fi
+		ocf_run lio_node --addnp ${OCF_RESKEY_iqn} 1 \
+		    ${portal} || exit $OCF_ERR_GENERIC
 	    done
 	    # in lio, we can set target parameters by manipulating
 	    # the appropriate configfs entries
@@ -297,41 +289,67 @@ iSCSITarget_start() {
 	    # this, we need to switch the target to "permissive mode".
 	    if [ -n "${OCF_RESKEY_allowed_initiators}" ]; then
 		for initiator in ${OCF_RESKEY_allowed_initiators}; do
-                    if [ "$OCF_RESKEY_implementation" == "lio" ] ; then
-                        ocf_run lio_node --addnodeacl ${OCF_RESKEY_iqn} 1 \
-                            ${initiator} || exit $OCF_ERR_GENERIC
-                    else
-                        ocf_run targetcli /iscsi/${OCF_RESKEY_iqn}/tpg1/acls create ${initiator} || exit $OCF_ERR_GENERIC
-                    fi
+		    ocf_run lio_node --addnodeacl ${OCF_RESKEY_iqn} 1 \
+			${initiator} || exit $OCF_ERR_GENERIC
 		done
 	    else
-                if [ "$OCF_RESKEY_implementation" == "lio" ] ; then
-                    ocf_run lio_node --permissive ${OCF_RESKEY_iqn} 1 || exit $OCF_ERR_GENERIC
-
-                    # permissive mode enables read-only access by default,
-                    # so we need to change that to RW to be in line with
-                    # the other implementations.
-                    echo 0 > "/sys/kernel/config/target/iscsi/${OCF_RESKEY_iqn}/tpgt_1/attrib/demo_mode_write_protect"
-                    if [ `cat /sys/kernel/config/target/iscsi/${OCF_RESKEY_iqn}/tpgt_1/attrib/demo_mode_write_protect` -ne 0 ]; then
-                        ocf_log err "Failed to disable write protection for target ${OCF_RESKEY_iqn}."
-                        exit $OCF_ERR_GENERIC
-                    fi
-                else
-                    ocf_run targetcli /iscsi/${OCF_RESKEY_iqn}/tpg1/ set attribute authentication=0 demo_mode_write_protect=0 generate_node_acls=1 cache_dynamic_acls=1 || exit $OCF_ERR_GENERIC
-                fi
+		ocf_run lio_node --permissive ${OCF_RESKEY_iqn} 1 || exit $OCF_ERR_GENERIC
+		# permissive mode enables read-only access by default,
+		# so we need to change that to RW to be in line with
+		# the other implementations.
+		echo 0 > "/sys/kernel/config/target/iscsi/${OCF_RESKEY_iqn}/tpgt_1/attrib/demo_mode_write_protect"
+		if [ `cat /sys/kernel/config/target/iscsi/${OCF_RESKEY_iqn}/tpgt_1/attrib/demo_mode_write_protect` -ne 0 ]; then
+		    ocf_log err "Failed to disable write protection for target ${OCF_RESKEY_iqn}."
+		    exit $OCF_ERR_GENERIC
+		fi
 	    fi
 	    # TODO: add CHAP authentication support when it gets added
 	    # back into LIO
-            if [ "$OCF_RESKEY_implementation" == "lio" ] ; then
-                ocf_run lio_node --disableauth ${OCF_RESKEY_iqn} 1 || exit $OCF_ERR_GENERIC
-                # Finally, we need to enable the target to allow
-                # initiators to connect
-                ocf_run lio_node --enabletpg=${OCF_RESKEY_iqn} 1 || exit $OCF_ERR_GENERIC
-            else
-                ocf_run targetcli /iscsi/${OCF_RESKEY_iqn}/tpg1/ set attribute authentication=0 || exit $OCF_ERR_GENERIC
-#               ocf_run targetcli /iscsi 
-            fi
+	    ocf_run lio_node --disableauth ${OCF_RESKEY_iqn} 1 || exit $OCF_ERR_GENERIC
+	    # Finally, we need to enable the target to allow
+	    # initiators to connect
+	    ocf_run lio_node --enabletpg=${OCF_RESKEY_iqn} 1 || exit $OCF_ERR_GENERIC
 	    ;;
+    esac
+        lio-t)
+            # lio distinguishes between targets and target portal
+            # groups (TPGs). We will always create one TPG, with the
+            # number 1. In lio, creating a network portal
+            # automatically creates the corresponding target if it
+            # doesn't already exist.
+            for portal in ${OCF_RESKEY_portals}; do
+                ocf_run targetcli /iscsi create ${OCF_RESKEY_iqn} || exit $OCF_ERR_GENERIC
+                if [ $portal != ${OCF_RESKEY_portals_default} ] ; then
+                    IFS=':' read -a sep_portal <<< "$portal"
+                    ocf_run targetcli /iscsi/${OCF_RESKEY_iqn}/tpg1/portals create "${sep_portal[0]}" "${sep_portal[1]}" || exit $OCF_ERR_GENERIC
+                fi
+            done
+            # in lio, we can set target parameters by manipulating
+            # the appropriate configfs entries
+            for param in ${OCF_RESKEY_additional_parameters}; do
+                name=${param%=*}
+                value=${param#*=}
+                configfs_path="/sys/kernel/config/target/iscsi/${OCF_RESKEY_iqn}/tpgt_1/param/${name}"
+                if [ -e ${configfs_path} ]; then
+                    echo ${value} > ${configfs_path} || exit $OCF_ERR_GENERIC
+                else
+                    ocf_log warn "Unsupported iSCSI target parameter ${name}: will be ignored."
+                fi
+            done
+            # lio does per-initiator filtering by default. To disable
+            # this, we need to switch the target to "permissive mode".
+            if [ -n "${OCF_RESKEY_allowed_initiators}" ]; then
+                for initiator in ${OCF_RESKEY_allowed_initiators}; do
+                    ocf_run targetcli /iscsi/${OCF_RESKEY_iqn}/tpg1/acls create ${initiator} || exit $OCF_ERR_GENERIC
+                done
+            else
+                ocf_run targetcli /iscsi/${OCF_RESKEY_iqn}/tpg1/ set attribute authentication=0 demo_mode_write_protect=0 generate_node_acls=1 cache_dynamic_acls=1 || exit $OCF_ERR_GENERIC
+            fi
+            # TODO: add CHAP authentication support when it gets added
+            # back into LIO
+            ocf_run targetcli /iscsi/${OCF_RESKEY_iqn}/tpg1/ set attribute authentication=0 || exit $OCF_ERR_GENERIC
+#               ocf_run targetcli /iscsi 
+            ;;
     esac
 
     return $OCF_SUCCESS
