Low: iSCSITarget, iSCSILogicalUnit: fix probe behavior
Check for ocf_is_probe during validate, so only limited validation is
performed during probes.

--HG--
extra : rebase_source : 52ccbfa6e9f667e832e13dc426ff4c2c0692fada

diff --git a/heartbeat/iSCSILogicalUnit b/heartbeat/iSCSILogicalUnit
--- a/heartbeat/iSCSILogicalUnit
+++ b/heartbeat/iSCSILogicalUnit
@@ -357,20 +357,11 @@ iSCSILogicalUnit_validate() {
 	fi
     done
 
-    # Do we have all required binaries?
+    # Is the configured implementation supported?
     case $OCF_RESKEY_implementation in
-	iet)
-	    check_binary ietadm
-	    ;;
-	tgt)
-	    check_binary tgtadm
-	    ;;
-	lio)
-	    check_binary tcm_node
-	    check_binary lio_node
+	iet|tgt|lio)
 	    ;;
 	*)
-	    # and by the way, is the implementation supported?
 	    ocf_log error "Unsupported iSCSI target implementation \"$OCF_RESKEY_implementation\"!"
 	    exit $OCF_ERR_CONFIGURED
     esac
@@ -413,20 +404,6 @@ iSCSILogicalUnit_validate() {
 	    ;;
     esac
 
-    # Is the required kernel functionality available?
-    case $OCF_RESKEY_implementation in
-	iet)
-	    [ -d /proc/net/iet ]
-	    if [ $? -ne 0 ]; then
-		ocf_log err "/proc/net/iet does not exist or is not a directory -- check if required modules are loaded."
-		exit $OCF_ERR_INSTALLED
-	    fi
-	    ;;
-	tgt)
-	    # tgt is userland only
-	    ;;
-    esac
-
     # Do we have any configuration parameters that the current
     # implementation does not support?
     local unsupported_params
@@ -452,6 +429,36 @@ iSCSILogicalUnit_validate() {
 		"and will be ignored."
 	fi
     done
+
+    if ! ocf_is_probe; then
+    # Do we have all required binaries?
+	case $OCF_RESKEY_implementation in
+	    iet)
+		check_binary ietadm
+		;;
+	    tgt)
+		check_binary tgtadm
+		;;
+	    lio)
+		check_binary tcm_node
+		check_binary lio_node
+		;;
+	esac
+
+        # Is the required kernel functionality available?
+	case $OCF_RESKEY_implementation in
+	    iet)
+		[ -d /proc/net/iet ]
+		if [ $? -ne 0 ]; then
+		    ocf_log err "/proc/net/iet does not exist or is not a directory -- check if required modules are loaded."
+		    exit $OCF_ERR_INSTALLED
+		fi
+		;;
+	    tgt)
+	        # tgt is userland only
+		;;
+	esac
+    fi
 
     return $OCF_SUCCESS
 }
diff --git a/heartbeat/iSCSITarget b/heartbeat/iSCSITarget
--- a/heartbeat/iSCSITarget
+++ b/heartbeat/iSCSITarget
@@ -484,47 +484,13 @@ iSCSITarget_validate() {
 	fi
     done
 
-    # Do we have all required binaries?
+    # Is the configured implementation supported?
     case $OCF_RESKEY_implementation in
-	iet)
-	    check_binary ietadm
-	    ;;
-	tgt)
-	    check_binary tgtadm
-	    ;;
-	lio)
-	    check_binary tcm_node
-	    check_binary lio_node
+	iet|tgt|lio)
 	    ;;
 	*)
-	    # and by the way, is the implementation supported?
 	    ocf_log error "Unsupported iSCSI target implementation \"$OCF_RESKEY_implementation\"!"
 	    exit $OCF_ERR_CONFIGURED
-    esac
-
-    # Is the required kernel functionality available?
-    case $OCF_RESKEY_implementation in
-	iet)
-	    [ -d /proc/net/iet ]
-	    if [ $? -ne 0 ]; then
-		ocf_log err "/proc/net/iet does not exist or is not a directory -- check if required modules are loaded."
-		exit $OCF_ERR_INSTALLED
-	    fi
-	    ;;
-	tgt)
-	    # tgt is userland only
-	    ;;
-	lio)
-	    # lio needs configfs to be mounted
-	    if ! grep -Eq "^.*/sys/kernel/config[[:space:]]+configfs" /proc/mounts; then
-		ocf_log err "configfs not mounted at /sys/kernel/config -- check if required modules are loaded."
-		exit $OCF_ERR_INSTALLED
-	    fi
-	    # check for configfs entries created by target_core_mod
-	    if [ ! -d /sys/kernel/config/target ]; then
-		ocf_log err "/sys/kernel/config/target does not exist or is not a directory -- check if required modules are loaded."
-	    fi
-	    ;;
     esac
 
     # Do we have any configuration parameters that the current
@@ -552,6 +518,47 @@ iSCSITarget_validate() {
 		"and will be ignored."
 	fi
     done
+
+    if ! ocf_is_probe; then
+    # Do we have all required binaries?
+	case $OCF_RESKEY_implementation in
+	    iet)
+		check_binary ietadm
+		;;
+	    tgt)
+		check_binary tgtadm
+		;;
+	    lio)
+		check_binary tcm_node
+		check_binary lio_node
+		;;
+	esac
+
+    # Is the required kernel functionality available?
+	case $OCF_RESKEY_implementation in
+	    iet)
+		[ -d /proc/net/iet ]
+		if [ $? -ne 0 ]; then
+		    ocf_log err "/proc/net/iet does not exist or is not a directory -- check if required modules are loaded."
+		    exit $OCF_ERR_INSTALLED
+		fi
+		;;
+	    tgt)
+	        # tgt is userland only
+		;;
+	    lio)
+	        # lio needs configfs to be mounted
+		if ! grep -Eq "^.*/sys/kernel/config[[:space:]]+configfs" /proc/mounts; then
+		    ocf_log err "configfs not mounted at /sys/kernel/config -- check if required modules are loaded."
+		    exit $OCF_ERR_INSTALLED
+		fi
+	        # check for configfs entries created by target_core_mod
+		if [ ! -d /sys/kernel/config/target ]; then
+		    ocf_log err "/sys/kernel/config/target does not exist or is not a directory -- check if required modules are loaded."
+		fi
+		;;
+	esac
+    fi
 
     return $OCF_SUCCESS
 }
