Dev: iscsi: simplify discovery code

diff --git a/heartbeat/iscsi b/heartbeat/iscsi
--- a/heartbeat/iscsi
+++ b/heartbeat/iscsi
@@ -212,7 +212,6 @@ open_iscsi_setup() {
  
 open_iscsi_discovery() {
 	local output
-	local severity=err
 	local discovery_variant="discovery"
 	local options=""
 	local cmd
@@ -225,11 +224,10 @@ open_iscsi_discovery() {
 			options="-D"
 	fi
 	cmd="$iscsiadm -m $discovery_variant -p $OCF_RESKEY_portal -t $discovery_type $options"
-	ocf_is_probe && severity=info
 	output=`$cmd`
 	if [ $? -ne 0 -o x = "x$output" ]; then
 		[ x != "x$output" ] && {
-			ocf_log $severity "$cmd FAILED"
+			ocf_log err "$cmd FAILED"
 			echo "$output"
 		}
 		return 3
@@ -246,7 +244,7 @@ open_iscsi_discovery() {
 	case `echo "$PORTAL" | wc -w` in
 	0) #target not found
 		echo "$output"
-		ocf_log $severity "target $OCF_RESKEY_target not found at portal $OCF_RESKEY_portal"
+		ocf_log err "target $OCF_RESKEY_target not found at portal $OCF_RESKEY_portal"
 		return 1
 	;;
 	1) #we're ok
@@ -323,27 +321,10 @@ disk_discovery() {
 	$discovery  # discover and setup the real portal string (address)
 	case $? in
 	0) ;;
-	1) [ "$__OCF_ACTION" = stop ] && exit $OCF_SUCCESS
-	   [ "$__OCF_ACTION" = monitor ] && exit $OCF_NOT_RUNNING
-	   [ "$__OCF_ACTION" = status ] && exit $LSB_STATUS_STOPPED
-	   exit $OCF_ERR_GENERIC
-	;;
-	2) [ "$__OCF_ACTION" = stop ] && {
-		iscsi_monitor || exit $OCF_SUCCESS
-	   }
-	   ocf_is_probe && {
-		iscsi_monitor; exit
-	   }
-	   exit $OCF_ERR_GENERIC
-	;;
-	3) ocf_is_probe && exit $OCF_NOT_RUNNING
-	   [ "$__OCF_ACTION" = stop ] && {
-		iscsi_monitor || exit $OCF_SUCCESS
-	   }
-	   if ! is_iscsid_running; then
+	1|2) exit $OCF_ERR_GENERIC ;;
+	3) if ! is_iscsid_running; then
 			[ $setup_rc -eq 1 ] &&
 				ocf_log warning "iscsid.startup probably not correctly set in /etc/iscsi/iscsid.conf"
-			[ "$__OCF_ACTION" = stop ] && exit $OCF_SUCCESS
 			exit $OCF_ERR_INSTALLED
 	   fi
 	   exit $OCF_ERR_GENERIC
