High: RA: iSCSITarget, iSCSILogicalUnit: add support for tgt

diff --git a/heartbeat/iSCSILogicalUnit b/heartbeat/iSCSILogicalUnit
--- a/heartbeat/iSCSILogicalUnit
+++ b/heartbeat/iSCSILogicalUnit
@@ -36,6 +36,8 @@ LANG="C"
 # Set a default implementation based on software installed
 if have_binary ietadm; then
     OCF_RESKEY_implementation_default="iet"
+elif have_binary tgtadm; then
+    OCF_RESKEY_implementation_default="tgt"
 fi
 : ${OCF_RESKEY_implementation=${OCF_RESKEY_implementation_default}}
 #######################################################################
@@ -151,6 +153,12 @@ iSCSILogicalUnit_start() {
 		--lun=${OCF_RESKEY_lun} \
 		--params Path=${OCF_RESKEY_path} && return $OCF_SUCCESS
 	    ;;
+	tgt)
+	    do_cmd tgtadm --lld iscsi --op new --mode logicalunit \
+		--tid=${OCF_RESKEY_tid} \
+		--lun=${OCF_RESKEY_lun} \
+	    	--backing-store ${OCF_RESKEY_path} && return $OCF_SUCCESS
+	    ;;
     esac
     return $OCF_ERR_GENERIC
 }
@@ -160,9 +168,24 @@ iSCSILogicalUnit_stop() {
     if [ $? =  $OCF_SUCCESS ]; then
 	case $OCF_RESKEY_implementation in
 	    iet)
+		# IET allows us to remove LUs while they are in use
 		do_cmd ietadm --op delete \
 		    --tid=${OCF_RESKEY_tid} \
 		    --lun=${OCF_RESKEY_lun} && return $OCF_SUCCESS
+		;;
+	    tgt)
+		# tgt will fail to remove an LU while it is in use,
+		# but at the same time does not allow us to
+		# selectively shut down a connection that is using a
+		# specific LU. Thus, we need to loop here until tgtd
+		# decides that the LU is no longer in use, or we get
+		# timed out by the LRM.
+		while ! do_cmd tgtadm --lld iscsi --op delete --mode logicalunit \
+		    --tid ${OCF_RESKEY_tid} \
+		    --lun=${OCF_RESKEY_lun}; do
+		    sleep 1
+		done
+		return $OCF_SUCCESS
 		;;
 	esac
     else
@@ -177,6 +200,12 @@ iSCSILogicalUnit_monitor() {
 	    # FIXME: this looks for a matching LUN and path, but does
 	    # not actually test for the correct target ID.
 	    grep -E -q "[[:space:]]+lun:${OCF_RESKEY_lun}.*path:${OCF_RESKEY_path}" /proc/net/iet/volume && return $OCF_SUCCESS
+	    ;;
+	tgt)
+	    # This only looks for the backing store, but does not test
+	    # for the correct target ID and LUN.
+	    tgtadm --lld iscsi --op show --mode target \
+		| grep -E -q "[[:space:]]+Backing store: ${OCF_RESKEY_path}" && return $OCF_SUCCESS
 	    ;;
     esac
     
@@ -197,6 +226,9 @@ iSCSILogicalUnit_validate() {
     case $OCF_RESKEY_implementation in
 	iet)
 	    check_binary ietadm || return $OCF_ERR_INSTALLED
+	    ;;
+	tgt)
+	    check_binary tgtadm || return $OCF_ERR_INSTALLED
 	    ;;
 	*)
 	    # and by the way, is the implementation supported?
@@ -238,6 +270,23 @@ iSCSILogicalUnit_validate() {
 		    ;;
 	    esac
 	    ;;
+	tgt)
+	    # tgt reserves LUN 0 for its own purposes
+	    [ $OCF_RESKEY_lun -ge 1 ]
+	    case $? in
+		0)
+	            # OK
+		    ;;
+		1)
+		    ocf_log err "Invalid LUN $OCF_RESKEY_lun (must be greater than 0)."
+		    return $OCF_ERR_CONFIGURED
+		    ;;
+		*)
+		    ocf_log err "Invalid LUN $OCF_RESKEY_lun (must be an integer)."
+		    return $OCF_ERR_CONFIGURED
+		    ;;
+	    esac
+	    ;;
     esac
 
     # Is the required kernel functionality available?
@@ -248,6 +297,9 @@ iSCSILogicalUnit_validate() {
 		ocf_log err "/proc/net/iet does not exist or is not a directory -- check if required modules are loaded."
 		return $OCF_ERR_INSTALLED
 	    fi
+	    ;;
+	tgt)
+	    # tgt is userland only
 	    ;;
     esac
 
