High: LVM: Retry exclusive activation after deactivating vg cluster-wide

diff --git a/heartbeat/LVM b/heartbeat/LVM
--- a/heartbeat/LVM
+++ b/heartbeat/LVM
@@ -205,27 +205,68 @@ get_activate_options()
 	echo $options
 }
 
+##
+# Attempt to deactivate vg cluster wide and then start the vg exclusively
+##
+retry_exclusive_start()
+{
+	local vgchange_options=$(get_activate_options)
+
+	# Deactivate each LV in the group one by one cluster wide
+	set -- $(lvs -o name,attr --noheadings $OCF_RESKEY_volgrpname 2> /dev/null)
+	while [ $# -ge 2 ]; do
+		case $2 in
+		????ao*)
+			# open LVs cannot be deactivated.
+			return $OCF_ERR_GENERIC;;
+		*)
+			if ! lvchange -an $OCF_RESKEY_volgrpname/$1; then
+				ocf_log err "Unable to perform required deactivation of $OCF_RESKEY_volgrpname/$1 before starting"
+				return $OCF_ERR_GENERIC
+			fi
+			;;
+		esac
+		shift 2
+	done
+
+	return ocf_run vgchange $vgchange_options $OCF_RESKEY_volgrpname
+}
+
 #
 #	Enable LVM volume
 #
 LVM_start() {
 	local vgchange_options=$(get_activate_options)
+	local vg=$1
 
 	# TODO: This MUST run vgimport as well
-	ocf_log info "Activating volume group $1"
+	ocf_log info "Activating volume group $vg"
 	if [ "$LVM_MAJOR" -eq "1" ]; then
-		ocf_run vgscan $1
+		ocf_run vgscan $vg
 	else
 		ocf_run vgscan
 	fi
 
-	ocf_run vgchange $vgchange_options $1 || return $OCF_ERR_GENERIC
+	if ! ocf_run vgchange $vgchange_options $vg; then
+		if ! ocf_is_true "$OCF_RESKEY_exclusive"; then
+			return $OCF_ERR_GENERIC
+		fi
 
-	if LVM_status $1; then
-		: OK Volume $1 activated just fine!
+		# Failure to exclusively activate cluster vg.:
+		# This could be caused by a remotely active LV, Attempt
+		# to disable volume group cluster wide and try again.
+		# Allow for some settling
+		sleep 5
+		if ! retry_exclusive_start; then
+			return $OCF_ERR_GENERIC
+		fi
+	fi
+
+	if LVM_status $vg; then
+		: OK Volume $vg activated just fine!
 		return $OCF_SUCCESS 
 	else
-		ocf_log err "LVM: $1 did not activate correctly"
+		ocf_log err "LVM: $vg did not activate correctly"
 		return $OCF_NOT_RUNNING
 	fi
 }
