High: LVM: Exclusive activation without clvmd using filtering with tags.

diff --git a/heartbeat/LVM b/heartbeat/LVM
--- a/heartbeat/LVM
+++ b/heartbeat/LVM
@@ -74,7 +74,12 @@ The name of volume group.
 </parameter>
 <parameter name="exclusive" unique="0" required="0">
 <longdesc lang="en">
-If set, the volume group will be activated exclusively.
+If set, the volume group will be activated exclusively.  This option works one of
+two ways.  If the volume group has the cluster attribute set, then the volume group
+will be activated exclusively using clvmd across the cluster.  If the cluster attribute
+is not set, the volume group will be activated exclusively using a tag and the volume_list 
+filter. When the tag option is in use, the volume_list in lvm.con must be initialized. This 
+can be as simple as setting 'volume_list = []' depending on your setup.
 </longdesc>
 <shortdesc lang="en">Exclusive activation</shortdesc>
 <content type="boolean" default="false" />
@@ -121,6 +126,131 @@ LVM_methods() {
 EOF
 }
 
+##
+# returns mode
+#
+# 0 = normal (non-exclusive) local activation
+# 1 = tagged-exclusive activation
+# 2 = clvm-exclusive activation
+##
+VG_MODE=
+get_vg_mode()
+{
+	if [ -n "$VG_MODE" ]; then
+		echo "$VG_MODE"
+		return
+	fi
+
+	VG_MODE=0
+	if ocf_is_true "$OCF_RESKEY_exclusive"; then
+		case $(vgs -o attr --noheadings $OCF_RESKEY_volgrpname | tr -d ' ') in
+		?????c*)
+			VG_MODE=2 ;;
+		*)
+			VG_MODE=1 ;;
+		esac
+	fi
+
+	echo "$VG_MODE"
+}
+
+##
+# Verify tags setup
+##
+verify_tags_environment()
+{
+	##
+	# The volume_list must be initialized to something in order to
+	# guarantee our tag will be filtered on startup
+	##
+	if ! lvm dumpconfig activation/volume_list; then
+		ocf_log err "LVM: Improper setup detected"
+		ocf_log err "The volume_list filter must be initialized in lvm.conf for exclusive activation without clvmd"
+		return $OCF_ERR_GENERIC
+	fi
+
+	##
+	# Our tag must _NOT_ be in the volume_list.  This agent
+	# overrides the volume_list during activation using the
+	# special tag reserved for cluster activation
+	##
+	if lvm dumpconfig activation/volume_list | grep -e "\"@$OUR_TAG\"" -e "\"${OCF_RESKEY_volgrpname}\""; then
+		ocf_log err "LVM:  Improper setup detected"
+		ocf_log err "The volume_list in lvm.conf must not contain the cluster tag, \"$OUR_TAG\", or volume group, $OCF_RESKEY_volgrpname"
+		return $OCF_ERR_GENERIC
+	fi
+
+	return $OCF_SUCCESS
+}
+
+##
+# does this vg have our tag
+##
+check_tags()
+{
+	local owner=`vgs -o tags --noheadings $OCF_RESKEY_volgrpname | tr -d ' '`
+
+	if [ -z "$owner" ]; then
+		# No-one owns this VG yet
+		return 1
+	fi
+
+	if [ "$OUR_TAG" = "$owner" ]; then
+		# yep, this is ours
+		return 0
+	fi
+
+	# some other tag is set on this vg
+	return 2
+}
+
+strip_tags()
+{
+	local i
+
+	for i in `vgs --noheadings -o tags $OCF_RESKEY_volgrpname | sed s/","/" "/g`; do
+		ocf_log info "Stripping tag, $i"
+
+		# LVM version 2.02.98 allows changing tags if PARTIAL
+		vgchange --deltag $i $OCF_RESKEY_volgrpname
+	done
+
+	if [ ! -z `vgs -o tags --noheadings $OCF_RESKEY_volgrpname | tr -d ' '` ]; then
+		ocf_log err "Failed to remove ownership tags from $OCF_RESKEY_volgrpname"
+		return $OCF_ERR_GENERIC
+	fi
+
+	return $OCF_SUCCESS
+}
+
+set_tags()
+{
+	check_tags
+	case $? in
+	0)
+		# we already own it.
+		return $OCF_SUCCESS
+		;;
+	2)
+		# other tags are set, strip them before setting
+		if ! strip_tags; then
+			return $OCF_ERR_GENERIC
+		fi
+		;;
+	*)
+		: ;;
+	esac
+
+	vgchange --addtag $OUR_TAG $OCF_RESKEY_volgrpname
+	if [ $? -ne 0 ]; then
+		ocf_log err "Failed to add ownership tag to $OCF_RESKEY_volgrpname"
+		return $OCF_ERR_GENERIC
+	fi
+
+	ocf_log info "New tag \"$OUR_TAG\" added to $OCF_RESKEY_volgrpname"
+	return $OCF_SUCCESS
+}
+
 #
 #	Return LVM status (silently)
 #
@@ -150,6 +280,25 @@ LVM_status() {
 
 	if [ $rc -ne 0 ]; then
 		ocf_log $loglevel "LVM Volume $1 is not available (stopped)"
+		rc=$OCF_NOT_RUNNING
+	else
+		case $(get_vg_mode) in
+		1) # exclusive with tagging.
+			# If vg is running, make sure the correct tag is present. Otherwise we
+			# can not guarantee exclusive activation.
+			if ! check_tags; then
+				ocf_log err "WARNING: $OCF_RESKEY_volgrpname is active without the cluster tag, \"$OUR_TAG\""
+				rc=$OCF_ERR_GENERIC
+			fi
+
+			# make sure the environment for tags activation is still valid
+			if ! verify_tags_environment; then
+				rc=$OCF_ERR_GENERIC
+			fi
+			;;
+		*)
+			: ;;
+		esac
 	fi
 
 	if [ "X${2}" = "X" ]; then
@@ -166,31 +315,15 @@ LVM_status() {
 	return $rc
 }
 
-#
-#	Monitor the volume - does it really seem to be working?
-#
-#
-LVM_monitor() {
-	if
-		LVM_status $1
-	then
-		: OK
-	else
-		ocf_log info "LVM Volume $1 is offline"
-		return $OCF_NOT_RUNNING
-	fi
-
-	return $OCF_SUCCESS
-}
-
 get_activate_options()
 {
 	local options="-a"
-	if ocf_is_true "$OCF_RESKEY_exclusive" ; then
-		options="${options}ey"
-	else
-		options="${options}ly"
-	fi
+
+	case $(get_vg_mode) in
+	0) options="${options}ly";;
+	1) options="${options}y --config activation{volume_list=[\"@${OUR_TAG}\"]}";;
+	2) options="${options}ey";;
+	esac
 
 	if ocf_is_true "$OCF_RESKEY_partial_activation" ; then
 		options="${options} --partial"
@@ -201,7 +334,7 @@ get_activate_options()
 	if ocf_is_clone; then
 		options="$options --monitor y"
 	fi
-
+	
 	echo $options
 }
 
@@ -238,6 +371,7 @@ retry_exclusive_start()
 LVM_start() {
 	local vgchange_options=$(get_activate_options)
 	local vg=$1
+	local clvmd=0
 
 	# TODO: This MUST run vgimport as well
 	ocf_log info "Activating volume group $vg"
@@ -247,8 +381,21 @@ LVM_start() {
 		ocf_run vgscan
 	fi
 
+	case $(get_vg_mode) in
+	2)
+		clvmd=1
+		;;
+	1)
+		if ! set_tags; then
+			return $OCF_ERR_GENERIC
+		fi
+		;;
+	*)
+		: ;;
+	esac
+
 	if ! ocf_run vgchange $vgchange_options $vg; then
-		if ! ocf_is_true "$OCF_RESKEY_exclusive"; then
+		if [ $clvmd -eq 0 ]; then
 			return $OCF_ERR_GENERIC
 		fi
 
@@ -275,34 +422,51 @@ LVM_start() {
 #	Disable the LVM volume
 #
 LVM_stop() {
-	local res
-	vgdisplay "$1" 2>&1 | grep 'Volume group .* not found' >/dev/null && {
-		ocf_log info "Volume group $1 not found"
+	local res=$OCF_ERR_GENERIC
+	local vgchange_options="-aln"
+	local vg=$1
+
+	if ! vgs $vg > /dev/null 2>&1; then
+		ocf_log info "Volume group $vg not found"
 		return $OCF_SUCCESS
-	}
-	ocf_log info "Deactivating volume group $1"
+	fi
+
+	ocf_log info "Deactivating volume group $vg"
+
+	case $(get_vg_mode) in
+		1) vgchange_options="-an" ;;
+	esac
 
 	for i in $(seq 10)
 	do
-		ocf_run vgchange -a ln $1
+		ocf_run vgchange $vgchange_options $vg
 		res=$?
-		if LVM_status $1; then
-			ocf_log err "LVM: $1 did not stop correctly"
+		if LVM_status $vg; then
+			ocf_log err "LVM: $vg did not stop correctly"
 			res=1
 		fi
 
 		if [ $res -eq 0 ]; then
-			return $OCF_SUCCESS
+			break
 		fi
 
-		ocf_log warn "$1 still Active"
-		ocf_log info "Retry deactivating volume group $1"
+		res=$OCF_ERR_GENERIC
+		ocf_log warn "$vg still Active"
+		ocf_log info "Retry deactivating volume group $vg"
 		sleep 1
 		which udevadm > /dev/null 2>&1 && udevadm settle --timeout=5
 	done
 
-	# TODO: This MUST run vgexport as well
-	return $OCF_ERR_GENERIC 
+	case $(get_vg_mode) in
+	1)
+		if [ $res -eq 0 ]; then
+			strip_tags
+			res=$?
+		fi
+		;;
+	esac
+
+	return $res
 }
 
 #
@@ -353,19 +517,23 @@ LVM_validate_all() {
 	# Make sure the cluster attribute is set and clvmd is up when exclusive
 	# activation is enabled. Otherwise we can't exclusively activate the volume group.
 	##
-	case $(vgs -o attr --noheadings $OCF_RESKEY_volgrpname 2>/dev/null | tr -d ' ') in
-	?????c*)
-		# Is clvmd running?
+	case $(get_vg_mode) in
+	1)  # exclusive activation using tags
+		if ! verify_tags_environment; then
+			exit $OCF_ERR_GENERIC
+		fi
+		;;
+	2)  # exclusive activation with clvmd
+		##
+		# verify is clvmd running
+		##
 		if ! ps -C clvmd > /dev/null 2>&1; then
 			ocf_log err "$OCF_RESKEY_volgrpname has the cluster attribute set, but 'clvmd' is not running"
 			exit $OCF_ERR_GENERIC
 		fi
-		return $OCF_SUCCESS
 		;;
 	*)
-		ocf_log err "Unable to exclusively activate $OCF_RESKEY_volgrpname becaues it is not a clusted volume group"
-		exit $OCF_ERR_GENERIC
-		;;
+		: ;;
 	esac
 
 	return $OCF_SUCCESS
@@ -431,6 +599,12 @@ LVM_MAJOR="${LVM_VERSION%%.*}"
 
 VOLUME=$OCF_RESKEY_volgrpname
 OP_METHOD=$1
+
+OUR_TAG="pacemaker"
+if [ -n "$OCF_RESKEY_tag" ]; then
+	OUR_TAG=$OCF_RESKEY_tag
+fi
+
 # What kind of method was invoked?
 case "$1" in
 
@@ -445,7 +619,7 @@ case "$1" in
 	status)	LVM_status $VOLUME $1
 		exit $?;;
 
-	monitor)	LVM_monitor $VOLUME
+	monitor)	LVM_status $VOLUME
 		exit $?;;
 
 	validate-all)	LVM_validate_all
