( Done by Sun Xun <xunsun@cn.ibm.com> ) * validate-all (bug 417) * incorporated Horm's patch dealing with different LVM versions * do not require OCF_RESKEY_volgrpname when doing "meta-data", "methods", "usage"
CVS patchset: 7109
CVS date: 2005/07/27 08:10:40

--HG--
extra : convert_revision : a5f31291e9ebd34983e34a7c3862b44479a30f15

diff --git a/heartbeat/LVM.in b/heartbeat/LVM.in
--- a/heartbeat/LVM.in
+++ b/heartbeat/LVM.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: LVM.in,v 1.4 2005/07/15 09:28:21 sunjd Exp $
+# $Id: LVM.in,v 1.5 2005/07/27 08:10:40 sunjd Exp $
 # 
 # LVM
 #
@@ -35,11 +35,10 @@ prefix=@prefix@
 exec_prefix=@exec_prefix@
 
 usage() {
-  methods=`LVM_methods | grep -v methods`
+  methods=`LVM_methods`
   methods=`echo $methods | tr ' ' '|'`
   cat <<-! >&1
-	usage: $0 <LVM-configuration file> ($methods)
-	usage: $0 methods
+	usage: $0 $methods
 
 	$0 manages an  Linux Volume Manager volume (LVM) as an HA resource
 
@@ -47,9 +46,10 @@ usage() {
 	The 'stop' operation takes the given volume offline
 	The 'status' operation reports whether the volume is available
 	The 'monitor' operation reports whether the volume seems present
+	The 'validate-all' operation checks whether the OCF parameters are valid
 	The 'methods' operation reports on the methods $0 supports
 
-	$Id: LVM.in,v 1.4 2005/07/15 09:28:21 sunjd Exp $
+	$Id: LVM.in,v 1.5 2005/07/27 08:10:40 sunjd Exp $
 	!
   exit $OCF_ERR_GENERIC 
 
@@ -59,7 +59,7 @@ meta_data() {
 	cat <<END
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
-<resource-agent name="LVM" version="0.9">
+<resource-agent name="LVM">
 <version>1.0</version>
 
 <longdesc lang="en">
@@ -85,6 +85,7 @@ The name of volume group.
 <action name="monitor" depth="0" timeout="30" interval="10" start-delay="10" />
 <action name="methods" timeout="5" />
 <action name="meta-data" timeout="5" />
+<action name="validate-all" timeout="5" />
 </actions>
 </resource-agent>
 END
@@ -130,6 +131,7 @@ LVM_methods() {
 	status
 	monitor
 	methods
+	validate-all
 	usage
 	!
 }
@@ -139,7 +141,15 @@ LVM_methods() {
 #
 LVM_status() {
 
-  vgdisplay $1 | grep -i 'Status.*available' >/dev/null
+  if 
+    [ "$LVM_MAJOR" -eq "1" ]
+  then
+	vgdisplay $1 | grep -i 'Status.*available' >/dev/null
+	return $?
+  else
+	vgdisplay -v $1 | grep -i 'Status[ \t]*available' >/dev/null
+	return $?
+  fi
   
 }
 
@@ -148,15 +158,27 @@ LVM_status() {
 #
 LVM_report_status() {
 
-  VGOUT=`vgdisplay $1 2>&1`
+  if 
+    [ "$LVM_MAJOR" -eq "1" ]
+  then
+	VGOUT=`vgdisplay $1 2>&1`
+	echo "$VGOUT" | grep -i 'Status.*available' >/dev/null
+	rc=$?
+  else
+	VGOUT=`vgdisplay -v $1 2>&1`
+	echo "$VGOUT" | grep -i 'Status[ \t]*available' >/dev/null
+	rc=$?
+  fi
+
   if
-    echo "$VGOUT" | grep -i 'Status.*available' >/dev/null
+    [ $rc -eq 0 ]
   then
     : Volume $1 is available
   else
     ocf_log debug "LVM Volume $1 is not available (stopped)"
     return $OCF_NOT_RUNNING
   fi
+
   if
     echo "$VGOUT" | grep -i 'Access.*read/write' >/dev/null
   then
@@ -194,8 +216,16 @@ LVM_monitor() {
 LVM_start() {
 
   ocf_log info "Activating volume group $1"
-  run vgscan $1
-  run vgchange -a y $1 || return 1
+
+  if 
+    [ "$LVM_MAJOR" -eq "1" ]
+  then
+	run vgscan $1
+  else
+	run vgscan
+  fi
+
+  run vgchange -a y $1 || return $OCF_ERR_GENERIC
 
   if
     LVM_status $1
@@ -225,34 +255,98 @@ LVM_stop() {
   return $OCF_SUCCESS
 }
 
+#
+#	Check whether the OCF instance parameters are valid
+#
+LVM_validate_all() {
+#	Off-the-shelf tests...  
+  vgck "$VOLUME" >/dev/nulll 2>&1
+  
+  if [ $? -ne 0 ]; then
+	ocf_log err "Volume group [$VOLUME] does not exist or contains error!"
+	exit $OCF_ERR_GENERIC
+  fi
 
+#	Double-check
+  if 
+    [ "$LVM_MAJOR" -eq "1" ]
+  then
+	vgdisplay "$VOLUME" >/dev/null 2>&1
+  else
+	vgdisplay -v "$VOLUME" >/dev/null 2>&1
+  fi
+
+  if [ $? -ne 0 ]; then
+	ocf_log err "Volume group [$VOLUME] does not exist or contains error!"
+	exit $OCF_ERR_GENERIC
+  fi
+
+  return $OCF_SUCCESS
+}
 #
 #	'main' starts here...
 #
 
 if
-  ( [ $# -eq 0 ] || [ $# -gt 1 ] )
+  ( [ $# -ne 1 ] )
 then
   usage
-  exit $OCF_ERR_GENERIC 
+  exit $OCF_ERR_ARGS 
 fi
+
+case $1 in
+  meta-data)	meta_data
+		exit $OCF_SUCCESS;;
+
+  methods)	LVM_methods
+		exit $?;;
+
+  usage)	usage
+		exit $OCF_SUCCESS;;
+  *)		;;
+esac
 
 if 
   [ -z "$OCF_RESKEY_volgrpname" ]
 then
-  echo "You must identify the volume group name!"
+#  echo "You must identify the volume group name!"
   ocf_log err "You must identify the volume group name!"
-  usage
+#  usage
   exit $OCF_ERR_ARGS 
 fi
+
+# Get the LVM version number, for this to work we assume(thanks to panjiam):
+# 
+# LVM1 outputs like this
+#
+#	# vgchange --version
+#	vgchange: Logical Volume Manager 1.0.3
+#	Heinz Mauelshagen, Sistina Software  19/02/2002 (IOP 10)
+#
+# LVM2 and higher versions output in this format
+#
+#	# vgchange --version
+#	LVM version:     2.00.15 (2004-04-19)
+#	Library version: 1.00.09-ioctl (2004-03-31)
+#	Driver version:  4.1.0
+
+LVM_VERSION=`vgchange --version 2>&1 | \
+	awk --source '/Logical Volume Manager/ {print $5"\n"; exit; } '\
+	    --source '/LVM version:/ {printf $3"\n"; exit;}'`
+rc=$?
+
+if
+  ( [ $rc -ne 0 ] || [ -z "$LVM_VERSION" ] )
+then
+  ha_log err "LVM: $1 could not determine LVM version. Try 'vgchange --version' manually and modify $0 ?"
+  exit $OCF_ERR_GENERIC
+fi
+LVM_MAJOR="${LVM_VERSION%%.*}"
 
 VOLUME=$OCF_RESKEY_volgrpname
 
 # What kind of method was invoked?
 case "$1" in
-
-  meta-data)	meta_data
-		exit $OCF_SUCCESS;;
 
   start)	LVM_start $VOLUME
 		exit $?;;
@@ -266,13 +360,9 @@ case "$1" in
   monitor)	LVM_monitor $VOLUME
 		exit $?;;
 
-  methods)	LVM_methods
-		exit $?;;
-
-  usage)	usage
-		exit exit $OCF_SUCCESS;;
+  validate-all)	LVM_validate_all
+		;;
 
   *)		usage
 		exit $OCF_ERR_AEGS;;
 esac
-
