lxc: various changes after mailing list review

diff --git a/heartbeat/lxc b/heartbeat/lxc
--- a/heartbeat/lxc
+++ b/heartbeat/lxc
@@ -41,55 +41,26 @@
 #	OCF_RESKEY_LXC_CNAME_default="test1"
 #	OCF_RESKEY_LXC_BCP_default="/etc/lxc"
 #	OCF_RESKEY_LXC_BRP_default="/srv/lxc"
-#	OCF_RESKEY_LXC_CF_FILENAME="config"
+#	OCF_RESKEY_LXC_CF_FILENAME_default="config"
 #	: ${OCF_RESKEY_LXC_CNAME=${OCF_RESKEY_LXC_CNAME_default}}
 #	: ${OCF_RESKEY_LXC_BCP=${OCF_RESKEY_LXC_BCP_default}}
 #	: ${OCF_RESKEY_LXC_BRP=${OCF_RESKEY_LXC_BRP_default}}
-#	: ${OCF_RESKEY_LXC_CF_FILENAME=${OCF_RESKEY_LXC_CF_FILENAME}}
+#	: ${OCF_RESKEY_LXC_CF_FILENAME=${OCF_RESKEY_LXC_CF_FILENAME_default}}
 #	OCF_ROOT="/usr/lib/ocf"
-#	OCF_RESKEY_CRM_meta_globally_unique="true"
-#	OCF_RESKEY_stop_timeout=30000
+#	: OCF_FUNCTIONS_DIR=${OCF_ROOT}/resource.d/heartbeat
 #
-
 
 # Initialization:
 : ${OCF_FUNCTIONS_DIR=${OCF_ROOT}/lib/heartbeat}
 . ${OCF_FUNCTIONS_DIR}/ocf-shellfuncs
 
-# Set default trans_res_state (temporary file to "flag" if resource was stated but not stopped)
-trans_res_state="${HA_RSCTMP}/LXC_${OCF_RESKEY_LXC_CNAME}-${OCF_RESOURCE_INSTANCE}.state"
+# Set default TRANS_RES_STATE (temporary file to "flag" if resource was stated but not stopped)
+TRANS_RES_STATE="${HA_RSCTMP}/LXC_${OCF_RESKEY_LXC_CNAME}-${OCF_RESOURCE_INSTANCE}.state"
 
 # It would be "Bad" if the container were to be run on more than one node, using lock file in shared configration directory to prevent it.
 LOCKFILE="${OCF_RESKEY_LXC_BCP}/${OCF_RESKEY_LXC_CNAME}/${OCF_RESKEY_LXC_CNAME}.lock"
 ## ocf_release_lock_on_exit $LOCKFILE # does not work as I would expect ti too :-( #
 
-# put this here as it's so long it gets messy later!!!
-STARTCMD="screen -dmS ${OCF_RESKEY_LXC_CNAME} lxc-start -f ${OCF_RESKEY_LXC_CF_FILENAME} -n ${OCF_RESKEY_LXC_CNAME}"
-
-# confirm cgroup_mounted
-	# Various possible overrides to cgroup mount point.
-	# If kernel supplies cgroup mount point, prefer it.
-	CGROUP_MOUNT_POINT=/var/run/lxc/cgroup
-	CGROUP_MOUNT_NAME=lxc
-	CGROUP_MOUNTED=false
-	[[ -d /sys/fs/cgroup ]] && CGROUP_MOUNT_POINT=/sys/fs/cgroup CGROUP_MOUNT_NAME=cgroup
-	# If cgroup already mounted, use it no matter where it is.
-	# If multiple cgroup mounts, prefer the one named lxc if any.
-	eval `awk 'BEGIN{P="";N=""}END{print("cgmp="P" cgmn="N)}($3=="cgroup"){N=$1;P=$2;if($1="lxc")exit}' /proc/mounts`
-	[[ "$cgmn" && "$cgmp" && -d "$cgmp" ]] && CGROUP_MOUNT_POINT=$cgmp CGROUP_MOUNT_NAME=$cgmn CGROUP_MOUNTED=true
-	CGROUP_RELEASE_AGENT="/usr/sbin/lxc_cgroup_release_agent"
-	$CGROUP_MOUNTED || {
-		[[ -d $CGROUP_MOUNT_POINT ]] || mkdir -p $CGROUP_MOUNT_POINT
-		mount -t cgroup $CGROUP_MOUNT_NAME $CGROUP_MOUNT_POINT
-	}
-	echo 1 >${CGROUP_MOUNT_POINT}/notify_on_release
-
-# don't exit on TERM, the lrmd should handle that
-#trap sigterm_handler TERM
-#sigterm_handler() {
-#	ocf_log info "Cluster resource detected TERM signal, Please use cluster resource manager to control resources"
-#	return
-#}
 
 meta_data() {
 cat <<END
@@ -150,82 +121,117 @@ LXC_usage() {
 END
 }
 
+cgroup_mounted() {
+# test cgroup_mounted, mount if required
+	# Various possible overrides to cgroup mount point.
+	# If kernel supplies cgroup mount point, prefer it.
+	CGROUP_MOUNT_POINT=/var/run/lxc/cgroup
+	CGROUP_MOUNT_NAME=lxc
+	CGROUP_MOUNTED=false
+	[[ -d /sys/fs/cgroup ]] && CGROUP_MOUNT_POINT=/sys/fs/cgroup CGROUP_MOUNT_NAME=cgroup
+	# If cgroup already mounted, use it no matter where it is.
+	# If multiple cgroup mounts, prefer the one named lxc if any.
+	eval `awk 'BEGIN{P="";N=""}END{print("cgmp="P" cgmn="N)}($3=="cgroup"){N=$1;P=$2;if($1="lxc")exit}' /proc/mounts`
+	[[ "$cgmn" && "$cgmp" && -d "$cgmp" ]] && CGROUP_MOUNT_POINT=$cgmp CGROUP_MOUNT_NAME=$cgmn CGROUP_MOUNTED=true
+	CGROUP_RELEASE_AGENT="/usr/sbin/lxc_cgroup_release_agent"
+	$CGROUP_MOUNTED || {
+		[[ -d $CGROUP_MOUNT_POINT ]] || mkdir -p $CGROUP_MOUNT_POINT
+		mount -t cgroup $CGROUP_MOUNT_NAME $CGROUP_MOUNT_POINT
+	}
+	echo 1 >${CGROUP_MOUNT_POINT}/notify_on_release
+	return 0
+}
+
 LXC_start() {
-	if LXC_validate ; then
-		if ! LXC_status ; then
-#			ocf_take_lock $LOCKFILE # does not work as I would expect ti too :-( #
-			if [ -f $LOCKFILE ] ; then
-				ocf_log err "Starting of" ${OCF_RESKEY_LXC_CNAME} "aborted as there is already a lock file!"
-				ocf_log info "If you are SURE that this resource is not running elswhere, just delete the file" $LOCKFILE
-				exit ${OCF_ERR_GENERIC}
+	# put this here as it's so long it gets messy later!!!
+	STARTCMD="screen -dmS ${OCF_RESKEY_LXC_CNAME} lxc-start -f ${OCF_RESKEY_LXC_CF_FILENAME} -n ${OCF_RESKEY_LXC_CNAME}"
+	cgroup_mounted
+	ret=$?
+	if [ $ret ]; then
+		if LXC_validate ; then
+			if ! LXC_monitor ; then
+#				ocf_take_lock $LOCKFILE # does not work as I would expect ti too :-( #
+				if [ -f $LOCKFILE ] ; then
+					ocf_log err "Starting of" ${OCF_RESKEY_LXC_CNAME} "aborted as there is already a lock file!"
+					ocf_log info "If you are SURE that this resource is not running elswhere, just delete the file" $LOCKFILE
+					exit ${OCF_ERR_GENERIC}
+				else
+					touch $LOCKFILE
+		   			touch $TRANS_RES_STATE
+					ocf_log info "Starting" ${OCF_RESKEY_LXC_CNAME} 
+					cd ${OCF_RESKEY_LXC_BCP}/${OCF_RESKEY_LXC_CNAME}/
+		        		ocf_run ${STARTCMD} || exit $OCF_ERR_GENERIC 
+				fi
 			else
-				touch $LOCKFILE
-	   			touch $trans_res_state
-				ocf_log info "Starting" ${OCF_RESKEY_LXC_CNAME} 
-				cd ${OCF_RESKEY_LXC_BCP}/${OCF_RESKEY_LXC_CNAME}/
-	        		ocf_run ${STARTCMD} || exit $OCF_ERR_GENERIC 
+				# If already running, consider start successful
+				ocf_log debug ${OCF_RESOURCE_INSTANCE}: ${OCF_RESKEY_LXC_CNAME} "is already running"
+				return $OCF_SUCCESS
 			fi
-		else
-			# If already running, consider start successful
-			ocf_log debug ${OCF_RESOURCE_INSTANCE}: ${OCF_RESKEY_LXC_CNAME} "is already running"
 			return $OCF_SUCCESS
+		else
+			ret=$?
+			return $ret
 		fi
-		return $OCF_SUCCESS
 	else
-		ret=$?
-		return $ret
+		return $OCF_ERR_GENERIC
 	fi
 }
 
 
 
 LXC_stop() {
-	# If the container is running "init" and is able to perform and orderly shutdown, then it should be done. 
-	typeset -i PID=0
-	lxc-ps -C init -opid |while read CN PID ;do
-		[[ $PID -gt 1 ]] || continue
-		[[ "$CN" = "${OCF_RESKEY_LXC_CNAME}" ]] || continue
-	grep -q 'p0::powerfail:/sbin/init 0' ${OCF_RESKEY_LXC_BRP}/${OCF_RESKEY_LXC_CNAME}/etc/inittab || continue
-	kill -PWR $PID
-        if [ -n "$OCF_RESKEY_stop_timeout" ]
-        then
-                # Allow 2/3 of the stop timeout for the orderly shutdown
-                # (The origin unit is ms, hence the conversion)
-                stop_timeout=$((OCF_RESKEY_stop_timeout/1500))
-        elif [ -n "$OCF_RESKEY_CRM_meta_timeout" ]; then
-                # Allow 2/3 of the action timeout for the orderly shutdown
-                # (The origin unit is ms, hence the conversion)
-                stop_timeout=$((OCF_RESKEY_CRM_meta_timeout/1500))
-        else
-                stop_timeout=10
-        fi
-	sleep $stop_timeout 
-	done
-	# If the container is still running, it will be stopped now. regardless of state!
-	lxc-stop -n ${OCF_RESKEY_LXC_CNAME}
-	if [ -f $LOCKFILE ]; then	
-		rm $LOCKFILE 
-	fi
-	if [ -f $trans_res_state ]; then	
-		rm $trans_res_state
+	cgroup_mounted
+	ret=$?
+	if [ $ret ]; then
+		# If the container is running "init" and is able to perform and orderly shutdown, then it should be done. 
+		typeset -i PID=0
+		lxc-ps -C init -opid |while read CN PID ;do
+			[[ $PID -gt 1 ]] || continue
+			[[ "$CN" = "${OCF_RESKEY_LXC_CNAME}" ]] || continue
+		grep -q 'p0::powerfail:/sbin/init 0' ${OCF_RESKEY_LXC_BRP}/${OCF_RESKEY_LXC_CNAME}/etc/inittab || continue
+		kill -PWR $PID
+	        if [ -n "$OCF_RESKEY_stop_timeout" ]
+	        then
+	                # Allow 2/3 of the stop timeout for the orderly shutdown
+	                # (The origin unit is ms, hence the conversion)
+	                stop_timeout=$((OCF_RESKEY_stop_timeout/1500))
+	        elif [ -n "$OCF_RESKEY_CRM_meta_timeout" ]; then
+	                # Allow 2/3 of the action timeout for the orderly shutdown
+	                # (The origin unit is ms, hence the conversion)
+	                stop_timeout=$((OCF_RESKEY_CRM_meta_timeout/1500))
+	        else
+	                stop_timeout=10
+	        fi
+		sleep $stop_timeout 
+		done
+		# If the container is still running, it will be stopped now. regardless of state!
+		lxc-stop -n ${OCF_RESKEY_LXC_CNAME}
+		if [ -f $LOCKFILE ]; then	
+			rm $LOCKFILE 
+		fi
+		if [ -f $TRANS_RES_STATE ]; then	
+			rm $TRANS_RES_STATE
+		else
+			ocf_log err "Dolt!" ${OCF_RESKEY_LXC_CNAME} "does not seem to be started!"
+			return ${OCF_ERR_GENERIC}
+		fi
+		return $OCF_SUCCESS
 	else
-		ocf_log err "Dolt!" ${OCF_RESKEY_LXC_CNAME} "does not seem to be started!"
-		return ${OCF_ERR_GENERIC}
+		return $OCF_ERR_GENERIC
 	fi
-	return $OCF_SUCCESS
 }
 
 LXC_monitor() {
         S=`lxc-info -n ${OCF_RESKEY_LXC_CNAME}`
 	ocf_log info "$S"
 	if [[ "${S##* }" = "RUNNING" ]] ; then 
-		if [ -f $trans_res_state ]; then
+		if [ -f $TRANS_RES_STATE ]; then
 			return $OCF_SUCCESS
 		else
 			return $OCF_ERR_GENERIC
 		fi
 	else
-		if [ -f $trans_res_state ]; then
+		if [ -f $TRANS_RES_STATE ]; then
 			ocf_log err "Dolt!" ${OCF_RESKEY_LXC_CNAME} "should be running!"
 			return $OCF_ERR_GENERIC
 		fi
@@ -243,16 +249,31 @@ LXC_validate() {
 	if [ -z "${OCF_RESKEY_LXC_BCP}" ]; then
 		ocf_log err "LXC configuration directory not set!"
 		exit $OCF_ERR_CONFIGURED
+	else
+		if ! [ -d "${OCF_RESKEY_LXC_BCP}"/"${OCF_RESKEY_LXC_CNAME}" ]; then
+			ocf_log err "LXC configuration directory "${OCF_RESKEY_LXC_BCP}"/"${OCF_RESKEY_LXC_CNAME}" is not present on this node!"
+			exit $OCF_ERR_INSTALLED
+		fi
 	fi
 	if [ -z "${OCF_RESKEY_LXC_BRP}" ]; then
 		ocf_log err "LXC container root filesystem directory not set!"
 		exit $OCF_ERR_CONFIGURED
+	else
+		if ! [ -d "${OCF_RESKEY_LXC_BRP}"/"${OCF_RESKEY_LXC_CNAME}" ]; then
+			ocf_log err "LXC container root filesystem directory "${OCF_RESKEY_LXC_BRP}${OCF_RESKEY_LXC_CNAME}" is not present on this node!"
+			exit $OCF_ERR_INSTALLED
+		fi
 	fi
 	if [ -z "${OCF_RESKEY_LXC_CF_FILENAME}" ]; then
 		ocf_log err "LXC configuration filename name not set!"
 		exit $OCF_ERR_CONFIGURED
+	else
+		if ! [ -f "${OCF_RESKEY_LXC_BCP}"/"${OCF_RESKEY_LXC_CNAME}"/"${OCF_RESKEY_LXC_CF_FILENAME}" ]; then
+			ocf_log err "LXC configuration file "${OCF_RESKEY_LXC_BCP}"/"${OCF_RESKEY_LXC_CNAME}"/"${OCF_RESKEY_LXC_CF_FILENAME}" missing or not found!"
+			exit $OCF_ERR_INSTALLED
+		fi
 	fi
-	# Quick that CGROUPS are corrrectly mounted
+	# Quick check that CGROUPS are corrrectly mounted
  	if ! [ -f ${CGROUP_MOUNT_POINT}/notify_on_release ]; then
 		exit $OCF_ERR_INSTALLED
 	fi
