fix for missing lxc-ps command in ocf:heartbeat:lxc
since beginning of 2014 the lxc-ps command isn't available anymore
(see:
 https://lists.linuxcontainers.org/pipermail/lxc-devel/2014-January/007433.html)
so it is using now lxc-info to determine the PID of a container and "ps"
to get the command name of it.

diff --git a/heartbeat/lxc b/heartbeat/lxc
--- a/heartbeat/lxc
+++ b/heartbeat/lxc
@@ -189,21 +189,34 @@ LXC_stop() {
 	# If the container is running "init" and is able to perform and orderly shutdown, then it should be done.
 	# It is 'assumed' that the 'init' system will do an orderly shudown if presented with a 'kill -PWR' signal.
 	# On a 'sysvinit' this would require the container to have an inittab file containing "p0::powerfail:/sbin/init 0"
-	typeset -i PID=0
+	declare -i PID=0
+	PID=$(lxc-info --name "${OCF_RESKEY_container}" -p -H)
+
+	# If there is no PID the container seems to be down which
+	# shouldn't happen.
+	if [ $PID -eq 0 ]; then
+		ocf_log err "${OCF_RESKEY_container} seems to run, but has no PID."
+		exit $OCF_ERR_GENERIC
+	fi
+
+	# Rescue me.
+	if [ $PID -eq 1 ]; then
+		ocf_log err "${OCF_RESKEY_container} seems to run with PID 1 which cannot be."
+	fi
+
+	CMD=$(ps -o comm= -p $PID)
+
 	# This should work for traditional 'sysvinit' and 'upstart'
-	lxc-ps --name "${OCF_RESKEY_container}" -- -C init -o pid,comm |while read CN PID CMD ;do
-		[ $PID -gt 1 ] || continue
-		[ "$CMD" = "init" ] || continue
+	if [ "$CMD" = "init" ]; then
 		ocf_log info "Sending \"OS shut down\" instruction to" ${OCF_RESKEY_container} "as it was found to be using \"sysV init\" or \"upstart\""
 		kill -PWR $PID
-	done
+	fi
+
 	# This should work for containers using 'systemd' instead of 'init'
-	lxc-ps --name "${OCF_RESKEY_container}" -- -C systemd -o pid,comm |while read CN PID CMD ;do
-		[ $PID -gt 1 ] || continue
-		[ "$CMD" = "systemd" ] || continue
+	if [ "$CMD" = "systemd" ]; then
 		ocf_log info "Sending \"OS shut down\" instruction to" ${OCF_RESKEY_container} "as it was found to be using \"systemd\""
 		kill -PWR $PID
-	done
+	fi
 	# The "shutdown_timeout" we use here is the operation
 	# timeout specified in the CIB, minus 5 seconds
 	now=$(date +%s)
