lxc: fix validation
Test for the configuration file's existence only during
non-probes. Also, remove the test for whether cgroup is mounted, as
cgroup_mounted() tests and mounts if necessary, anyway.

diff --git a/heartbeat/lxc b/heartbeat/lxc
--- a/heartbeat/lxc
+++ b/heartbeat/lxc
@@ -217,22 +217,22 @@ LXC_validate() {
 	if [ -z "${OCF_RESKEY_config}" ]; then
 		ocf_log err "LXC configuration filename name not set!"
 		exit $OCF_ERR_CONFIGURED
-	else
-		if ! [ -f "${OCF_RESKEY_config}" ]; then
-			ocf_log err "LXC configuration file \"${OCF_RESKEY_config}\" missing or not found!"
-			exit $OCF_ERR_INSTALLED
-		fi
 	fi
-	# Quick check that CGROUPS are corrrectly mounted
- 	if ! [ -f ${CGROUP_MOUNT_POINT}/notify_on_release ]; then
-		exit $OCF_ERR_INSTALLED
-	fi
+
 	# Quick check that required executables are present
  	check_binary lxc-start
  	check_binary lxc-stop
 	check_binary lxc-ps
 	check_binary lxc-info
 	check_binary screen
+
+	# Tests that apply only to non-probes
+	if ! ocf_is_probe; then
+	    if ! [ -f "${OCF_RESKEY_config}" ]; then
+		ocf_log err "LXC configuration file \"${OCF_RESKEY_config}\" missing or not found!"
+		exit $OCF_ERR_INSTALLED
+	    fi
+	fi
 	return $OCF_SUCCESS
 }
 
