Low: mysql-proxy: Update configuration per feedback of Dejan Muhamedagic

diff --git a/heartbeat/mysql-proxy b/heartbeat/mysql-proxy
--- a/heartbeat/mysql-proxy
+++ b/heartbeat/mysql-proxy
@@ -281,6 +281,8 @@ isRunning()
 
 mysqlproxy_status()
 {
+    local PID
+
     if [ -f "${pidfile}" ]; then
     # MySQL Proxy is probably running
         PID=`head -n 1 "${pidfile}"`
@@ -296,6 +298,10 @@ mysqlproxy_status()
 
 mysqlproxy_start()
 {
+    local PARAM_PREFIX OPTIONS
+    local p pa pba proba
+    local pid_dir socket_dir
+
     # if MySQL Proxy is running return success
     if mysqlproxy_status ; then
         ocf_log info "MySQL Proxy already running."
@@ -390,7 +396,7 @@ mysqlproxy_start()
     ret=$?
 
     if [ $ret -ne 0 ]; then
-        ocf_log err "MySQL Proxy returned error." $ret
+        ocf_log err "MySQL Proxy returned error: " $ret
         return $OCF_ERR_GENERIC
     fi
 
@@ -402,13 +408,16 @@ mysqlproxy_start()
 
 mysqlproxy_stop()
 {
+    local ret
+    local pa
+
     if mysqlproxy_status ; then
         #start-stop-daemon --stop --quiet --retry 3 --exec $binary --pidfile $pidfile
         /bin/kill `cat "${pidfile}"`
         ret=$?
 
         if [ $ret -ne 0 ]; then
-            ocf_log err "MySQL Proxy returned an error while stopping." $ret
+            ocf_log err "MySQL Proxy returned an error while stopping: " $ret
             return $OCF_ERR_GENERIC
         fi
 
@@ -439,6 +448,10 @@ mysqlproxy_stop()
 
 mysqlproxy_reload()
 {
+    # @TODO check if pidfile is empty
+    # PID=`head -n 1 "${pidfile}"`
+    #    if [ ! -z "$PID" ] ; then
+
     if mysqlproxy_status; then
         ocf_log info "Reloading MySQL Proxy."
         kill -s HUP `cat ${pidfile}`
@@ -448,8 +461,6 @@ mysqlproxy_reload()
 mysqlproxy_monitor()
 {
     local rc
-    local mysql_options pa
-    local mysql_server_parameter mysql_server_host mysql_server_port
 
     if [ "${OCF_RESKEY_CRM_meta_interval:-0}" -eq "0" ]; then
         # in case of probe, monitor operation is surely treated as
@@ -466,6 +477,8 @@ mysqlproxy_monitor()
 
     if [ $OCF_CHECK_LEVEL -eq 20 ]; then
         mysqlproxy_monitor_20
+        rc=$?
+        [ $rc -ne 0 ] && return $rc
     fi
 
     return $OCF_SUCCESS
@@ -473,9 +486,13 @@ mysqlproxy_monitor()
 
 mysqlproxy_monitor_20()
 {
+    local rc
+    local mysql_options pa
+    local mysql_server_parameter mysql_server_host mysql_server_port
+
     if [ -z "$OCF_RESKEY_test_table" -o -z "$OCF_RESKEY_test_user" -a -z "$OCF_RESKEY_test_passwd" ]; then
         ocf_log warn "Missing proper configuration for OCF_CHECK_LEVEL=20 (test_table=[$OCF_RESKEY_test_table] test_user=[$OCF_RESKEY_test_user] test_password=[$OCF_RESKEY_test_passwd]). Not running in-depth monitoring."
-        return
+        return $OCF_SUCCESS
     fi
 
     mysql_options="--connect_timeout=10 --user=$OCF_RESKEY_test_user --password=$OCF_RESKEY_test_passwd"
@@ -510,10 +527,12 @@ mysqlproxy_monitor_20()
         rc=$?
 
         if [ $rc -ne 0 ]; then
-            ocf_log err "Failed to select from $OCF_RESKEY_test_table"
+            ocf_log err "Failed to select from $OCF_RESKEY_test_table: " $rc
             return $OCF_ERR_GENERIC
         fi
     done
+
+    return $OCF_SUCCESS
 }
 
 mysqlproxy_validate_all()
