High: nfsserver: Enable file locking daemon when systemd is being used

diff --git a/heartbeat/nfsserver b/heartbeat/nfsserver
--- a/heartbeat/nfsserver
+++ b/heartbeat/nfsserver
@@ -226,7 +226,7 @@ set_exec_mode()
 	# Last of all, attempt systemd.
 	##
 	if which systemctl > /dev/null 2>&1; then
-		if systemctl list-unit-files | grep nfs-server > /dev/null; then
+		if systemctl list-unit-files | grep nfs-server > /dev/null && systemctl list-unit-files | grep nfs-lock > /dev/null; then
 			EXEC_MODE=2
 			return 0
 		fi
@@ -234,6 +234,33 @@ set_exec_mode()
 
 	ocf_log err "No init script or systemd unit file detected for nfs server"
 	exit $OCF_ERR_INSTALLED
+}
+
+nfs_systemd_exec()
+{
+	local cmd=$1
+	local server_res
+	local lock_res
+
+	if [ "$cmd" = "stop" ]; then
+		systemctl $cmd nfs-server.service
+		server_res=$?
+		systemctl $cmd nfs-lock.service
+		lock_res=$?
+	else
+		systemctl $cmd nfs-lock.service
+		lock_res=$?
+		systemctl $cmd nfs-server.service
+		server_res=$?
+	fi
+
+	if [ $lock_res -ne $server_res ]; then
+		# If one is running and the other isn't, or for whatever other reason
+		# the return code's aren't the same, this is bad.
+		ocf_log err "Systemd services nfs-lock and nfs-server are not in the same state after attempting $cmd command"
+		return $OCF_ERR_GENERIC
+	fi
+	return $server_res
 }
 
 ##
@@ -246,7 +273,7 @@ nfs_exec()
 
 	case $EXEC_MODE in 
 		1) ${OCF_RESKEY_nfs_init_script} $cmd;;
-		2) systemctl $cmd nfs-server.service;;
+		2) nfs_systemd_exec $cmd;;
 	esac
 }
 
