Medium: nfsserver: make the retry time for sm-notify configurable

diff --git a/heartbeat/nfsserver b/heartbeat/nfsserver
--- a/heartbeat/nfsserver
+++ b/heartbeat/nfsserver
@@ -66,6 +66,18 @@ Keeps sm-notify running in the foreground.
 <content type="boolean" default="$DEFAULT_NOTIFY_FOREGROUND" />
 </parameter>
 
+<parameter name="nfs_notify_retry_time" unique="0" required="0">
+<longdesc lang="en">
+Specifies the length of sm-notify retry time, in minutes, to continue retrying notifications to unresponsive hosts.  
+If this option is not specified, sm-notify attempts to send notifications for 15 minutes. Specifying a value of 0 
+causes sm-notify to continue sending notifications to unresponsive peers until it is manually killed.
+</longdesc>
+<shortdesc lang="en">
+Specifies the length of sm-notify retry time(minutes).
+</shortdesc>
+<content type="integer" default="" />
+</parameter>
+
 <parameter name="nfs_shared_infodir" unique="0" required="1">
 <longdesc lang="en">
 The nfsserver resource agent will save nfs related information in this specific directory.
@@ -237,6 +249,14 @@ nfsserver_start ()
 	# run in foreground, if requested
 	if ocf_is_true "$OCF_RESKEY_nfs_notify_foreground"; then
 		opts="-d $opts"
+	fi
+	# add option for notify_retry_time, if set
+	if [ -n "$OCF_RESKEY_nfs_notify_retry_time" ]; then
+		if ! ocf_is_decimal "$OCF_RESKEY_nfs_notify_retry_time"; then
+			ocf_log err "Invalid OCF_RESKEY_nfs_notify_retry_time [$OCF_RESKEY_nfs_notify_retry_time]"
+			return $OCF_ERR_CONFIGURED
+		fi
+		opts="-m $OCF_RESKEY_nfs_notify_retry_time $opts"
 	fi
 
 	echo $OCF_RESKEY_nfs_notify_cmd | grep -qws rpc.statd &&
