Volume re-attaching, v3 API, get hostname from corosync

diff --git a/heartbeat/openstack-cinder-volume b/heartbeat/openstack-cinder-volume
--- a/heartbeat/openstack-cinder-volume
+++ b/heartbeat/openstack-cinder-volume
@@ -37,6 +37,8 @@
 # Defaults
 OCF_RESKEY_openstackcli_default="/usr/bin/openstack"
 
+export attached_server_id=""
+
 : ${OCF_RESKEY_openstackcli=${OCF_RESKEY_openstackcli_default}}
 
 #######################################################################
@@ -104,7 +106,23 @@ END
 }
 
 osvol_validate() {
+	local node_id
+	local crm_node
+
 	check_binary "$OCF_RESKEY_openstackcli"
+	check_binary "awk"
+	check_binary "tr"
+	
+	crm_node=$(crm_node -n)
+
+	node_id=$(${HA_SBIN_DIR}/attrd_updater --query -n openstack_id -N $crm_node \
+		| tr ' ' '\n' \
+		| awk -F= '/value=/ {gsub("\"","");print $NF}')
+	
+	if [ -z "$node_id" ] ; then
+		ocf_exit_reason "openstack_id attribute must be set for node $crm_node"
+		return $OCF_ERR_CONFIGURED
+	fi
 
 	if [ -z "$OCF_RESKEY_openrc" ]; then
 		ocf_exit_reason "openrc parameter not set"
@@ -128,8 +146,8 @@ osvol_validate() {
 
 osvol_monitor() {
 	local result
-	local attached_server_id
 	local node_id
+	local crm_node
 
 	# Is the volue attached?
 	result=$($OCF_RESKEY_openstackcli volume show \
@@ -138,14 +156,18 @@ osvol_monitor() {
 		--format value \
 		$OCF_RESKEY_volume_id)
 
+	crm_node=$(crm_node -n)
+
 	if [[ "$result" =~ "available" ]] ; then
 		ocf_log warn "$OCF_RESKEY_volume_id is not attached to any instance"
 		return $OCF_NOT_RUNNING
 	else
-		attached_server_id=$(echo $result|head -n1|awk -F "'" '{print $4}')
+		export attached_server_id=$(echo $result|head -n1|awk -F "'" '{print $4}')
 		ocf_log info "$OCF_RESKEY_volume_id is attached to instance $attached_server_id"
-		node_id=$(${HA_SBIN_DIR}/attrd_updater --query -n openstack_id -N $HOSTNAME \
-			| awk '{gsub("value=","") ; gsub("\"","") ; print $NF}')
+
+		node_id=$(${HA_SBIN_DIR}/attrd_updater --query -n openstack_id -N $crm_node \
+			| tr ' ' '\n' \
+			| awk -F= '/value=/ {gsub("\"","");print $NF}')
 
 		if [ "$node_id" != "$attached_server_id" ] ; then
 			return $OCF_NOT_RUNNING
@@ -157,6 +179,7 @@ osvol_monitor() {
 
 osvol_stop() {
 	local node_id
+	local crm_node
 
 	osvol_monitor
 	if [ $? = $OCF_NOT_RUNNING ]; then
@@ -164,8 +187,12 @@ osvol_stop() {
 		return $OCF_SUCCESS
 	fi
 
-	node_id=$(${HA_SBIN_DIR}/attrd_updater --query -n openstack_id -N $HOSTNAME \
-		| awk '{gsub("value=","") ; gsub("\"","") ; print $NF}')
+	crm_node=$(crm_node -n)
+
+	node_id=$(${HA_SBIN_DIR}/attrd_updater --query -n openstack_id -N $crm_node \
+		| tr ' ' '\n' \
+		| awk -F= '/value=/ {gsub("\"","");print $NF}')
+
 	if ! $OCF_RESKEY_openstackcli server remove volume $node_id $OCF_RESKEY_volume_id ; then
 		ocf_log error "Couldn't remove volume $OCF_RESKEY_volume_id from instance $node_id"
 		return $OCF_ERR_GENERIC
@@ -177,6 +204,7 @@ osvol_stop() {
 
 osvol_start() {
 	local node_id
+	local crm_node
 
 	osvol_monitor
 	if [ $? = $OCF_SUCCESS ]; then
@@ -184,8 +212,20 @@ osvol_start() {
 		return $OCF_SUCCESS
 	fi
 
-	node_id=$(${HA_SBIN_DIR}/attrd_updater --query -n openstack_id -N $HOSTNAME \
-		| awk '{gsub("value=","") ; gsub("\"","") ; print $NF}')
+	if [ ! -z $attached_server_id ] ; then
+		if ! $OCF_RESKEY_openstackcli server remove volume $attached_server_id $OCF_RESKEY_volume_id ; then
+			ocf_log error "Couldn't remove volume $OCF_RESKEY_volume_id from instance $attached_server_id"
+			return $OCF_ERR_GENERIC
+		fi
+	fi
+
+	export $attached_server_id=""
+	crm_node=$(crm_node -n)
+	
+	node_id=$(${HA_SBIN_DIR}/attrd_updater --query -n openstack_id -N $crm_node \
+		| tr ' ' '\n' \
+		| awk -F= '/value=/ {gsub("\"","");print $NF}')
+
 	$OCF_RESKEY_openstackcli server add volume $node_id $OCF_RESKEY_volume_id
 	if [ $? != $OCF_SUCCESS ]; then
 		ocf_log error "Couldn't add volume $OCF_RESKEY_volume_id to instance $node_id"
