fix as commented by Dejan and fghaas

diff --git a/heartbeat/sg_persist b/heartbeat/sg_persist
--- a/heartbeat/sg_persist
+++ b/heartbeat/sg_persist
@@ -32,12 +32,13 @@
 # OCF instance parameters
 #    OCF_RESKEY_sg_persist_resource
 #    OCF_RESKEY_config_file
+#    OCF_RESKEY_sg_persist_binary
 #    OCF_RESKEY_devs
 #    OCF_RESKEY_required_devs_nof
 #    OCF_RESKEY_reservation_type
 #    OCF_RESKEY_master_score_base
 #    OCF_RESKEY_master_score_dev_factor
-#
+#    OCF_RESKEY_master_score_delay
 #
 # TODO
 # 
@@ -50,13 +51,21 @@
 
 : ${OCF_FUNCTIONS_DIR=${OCF_ROOT}/lib/heartbeat}
 . ${OCF_FUNCTIONS_DIR}/ocf-shellfuncs
-#######################################################################
 
-
-# uncomment the next line for debugging messages
-# HA_debug=1
+# set default values
+    : ${config_file="/etc/sg_persist.conf"} # config file full path
+    : ${sg_persist_binary="sg_persist"}     # binary name for the resource
+    : ${devs=""}                            # device list
+    : ${required_devs_nof=1}                # number of required devices
+    : ${reservation_type=1}                 # reservation type
+    : ${master_score_base=0}                # master score base 
+    : ${master_score_dev_factor=100}        # device factor for master score
+    : ${master_score_delay=30}              # delay for master score
 
 RESOURCE="$OCF_RESKEY_sg_persist_resource"
+
+#######################################################################
+
 
 meta_data() {
     cat <<END
@@ -81,6 +90,14 @@ The name of the sg_persist resource.
 </longdesc>
 <shortdesc lang="en">sg_persist resource name</shortdesc>
 <content type="string"/>
+</parameter>
+
+<parameter name="binary" unique="0">
+<longdesc lang="en">
+The name of the binary that manages the resource
+</longdesc>
+<shortdesc>the binay name of the resource</shortdesc>
+<content type="string" default="sg_persist"/>
 </parameter>
 
 <parameter name="config_file" unique="1" required="0">
@@ -185,26 +202,6 @@ END
     exit $OCF_SUCCESS
 }
 
-sg_persist_do_cmd() {
-    local cmd="$*"
-    
-    local cmd_out
-    cmd_out=$($cmd)
-    ret=$?
-    
-    if [ $ret -ne 0 ]; then
-        ocf_log err "$RESOURCE: Exit code $ret"
-        ocf_log err "$RESOURCE: Command output: $cmd_out"
-    else
-        ocf_log debug "$RESOURCE: Exit code $ret"
-        ocf_log debug "$RESOURCE: Command output: $cmd_out"
-    fi
-    
-    echo $cmd_out
-    
-    return $ret
-}
-
 sg_persist_init() {
     
     if ! ocf_is_root ; then
@@ -212,7 +209,7 @@ sg_persist_init() {
         exit $OCF_ERR_PERM
     fi 
 
-    : ${SG_PERSIST:=sg_persist}
+    : ${SG_PERSIST:="$sg_persist_binary"}
     check_binary $SG_PERSIST
     
     ROLE=$OCF_RESKEY_CRM_meta_role
@@ -221,7 +218,7 @@ sg_persist_init() {
     MASTER_SCORE_VAR_NAME="master-${OCF_RESOURCE_INSTANCE}"
     PENDING_VAR_NAME="pending-$MASTER_SCORE_VAR_NAME"
     
-    #only works with corocync ???
+    #only works with corocync 
     CRM_NODE="${HA_SBIN_DIR}/crm_node"
     if [ -z "$RESOURCE" ]; then
         ocf_log err "sg_persist_resource not defined."
@@ -247,27 +244,7 @@ sg_persist_init() {
 
     ocf_log debug "$RESOURCE: NODE:$NODE, ROLE:$ROLE, NODE_ID DEC:$NODE_ID_DEC HEX:$NODE_ID_HEX"
 
-    # default configure file path
-    SG_PERSIST_CONF="${OCF_RESKEY_config_file:=/etc/sg_persist.conf}"
-
-    # no default value for device list
-    devs=""
-
-    # default number of required devices
-    required_devs_nof=1
-
-    # default reservation type
-    reservation_type=1
-
-    # default master score base 
-    master_score_base=0
-
-    # default device factor for master score
-    master_score_dev_factor=100
-
-    # default delay for master score
-    master_score_delay=30
-
+    SG_PERSIST_CONF="${OCF_RESKEY_config_file:=$config_file}"
     if [ -f "$SG_PERSIST_CONF" ]
     then
         sg_persist_read_config
@@ -302,7 +279,7 @@ sg_persist_init() {
 sg_persist_read_config() {
     
     if [ -O $SG_PERSIST_CONF ]; then
-	. $SG_PERSIST_CONF
+        . $SG_PERSIST_CONF
     else
         ocf_log err "resource configuration file \"$SG_PERSIST_CONF\" not owned by \"root\""
         exit $OCF_ERR_INSTALLED
@@ -334,14 +311,14 @@ sg_persist_get_status() {
     
     for dev in ${EXISTING_DEVS[*]}
     do
-        READ_KEYS=`sg_persist_do_cmd $SG_PERSIST --in --read-keys $dev`
+        READ_KEYS=`ocf_run $SG_PERSIST --in --read-keys $dev`
         if [ $? -eq 0 ]; then 
             WORKING_DEVS+=($dev)
             echo $READ_KEYS | $GREP $NODE_ID_HEX >/dev/null
             if [ $? -eq 0 ]; then 
                 REGISTERED_DEVS+=($dev)
 
-                READ_RESERVATION=`sg_persist_do_cmd $SG_PERSIST --in --read-reservation $dev`
+                READ_RESERVATION=`ocf_run $SG_PERSIST --in --read-reservation $dev`
                 if [ $? -eq 0 ]; then
                     echo $READ_RESERVATION | $GREP $NODE_ID_HEX >/dev/null
                     if [ $? -eq 0 ]; then 
@@ -411,50 +388,6 @@ sg_persist_get_reservation_key() {
     echo ""
 }
 
-sg_persist_action_start() {
-
-    sg_persist_do_cmd $MASTER_SCORE_ATTRIBUTE --update=$MASTER_SCORE
-    sg_persist_do_cmd $PENDING_ATTRIBUTE --update=""
-    
-    if [ $WORKING_DEVS_NOF -lt $REQUIRED_DEVS_NOF ]; then 
-        ocf_log err "$RESOURCE: Number of working devices=$WORKING_DEVS_NOF less then required_devs_nof=$REQUIRED_DEVS_NOF"
-        exit $OCF_ERR_GENERIC
-    fi
-
-    for dev in ${WORKING_DEVS[*]}
-    do
-        if sg_persist_is_registered $dev ; then
-            : OK
-        else
-            sg_persist_do_cmd $SG_PERSIST --out --register --param-rk=0 --param-sark=$NODE_ID_HEX $dev
-            if [ $? -ne 0 ]
-            then
-                return $OCF_ERR_GENERIC
-            fi
-        fi
-    done
-
-    return $OCF_SUCCESS
-}
-
-sg_persist_action_stop() {
-
-    if [ ${#REGISTERED_DEVS[*]} -eq 0 ]; then
-        ocf_log debug "$RESOURCE stop: already no registrations"
-    else
-        # Clear preference for becoming master
-        sg_persist_do_cmd $MASTER_SCORE_ATTRIBUTE --delete
-        sg_persist_do_cmd $PENDING_ATTRIBUTE --delete
-
-        for dev in ${REGISTERED_DEVS[*]}
-        do
-            sg_persist_do_cmd $SG_PERSIST --out --register --param-rk=$NODE_ID_HEX --param-sark=0 $dev
-        done
-    fi
-
-    return $OCF_SUCCESS
-}
-
 sg_persist_echo_array() {
     str_count=0
     arr_str=""
@@ -495,12 +428,59 @@ sg_persist_new_pending() {
     NEW_PENDING=$1
 }
 
+
+# Functions invoked by resource manager actions
+
+sg_persist_action_start() {
+
+    ocf_run $MASTER_SCORE_ATTRIBUTE --update=$MASTER_SCORE
+    ocf_run $PENDING_ATTRIBUTE --update=""
+
+    if [ $WORKING_DEVS_NOF -lt $REQUIRED_DEVS_NOF ]; then
+        ocf_log err "$RESOURCE: Number of working devices=$WORKING_DEVS_NOF less then required_devs_nof=$REQUIRED_DEVS_NOF"
+        exit $OCF_ERR_GENERIC
+    fi
+
+    for dev in ${WORKING_DEVS[*]}
+    do
+        if sg_persist_is_registered $dev ; then
+            : OK
+        else
+            ocf_run $SG_PERSIST --out --register --param-rk=0 --param-sark=$NODE_ID_HEX $dev
+            if [ $? -ne 0 ]
+            then
+                return $OCF_ERR_GENERIC
+            fi
+        fi
+    done
+
+    return $OCF_SUCCESS
+}
+
+sg_persist_action_stop() {
+
+    if [ ${#REGISTERED_DEVS[*]} -eq 0 ]; then
+        ocf_log debug "$RESOURCE stop: already no registrations"
+    else
+        # Clear preference for becoming master
+        ocf_run $MASTER_SCORE_ATTRIBUTE --delete
+        ocf_run $PENDING_ATTRIBUTE --delete
+
+        for dev in ${REGISTERED_DEVS[*]}
+        do
+            ocf_run $SG_PERSIST --out --register --param-rk=$NODE_ID_HEX --param-sark=0 $dev
+        done
+    fi
+
+    return $OCF_SUCCESS
+}
+
 sg_persist_action_monitor() {
 
-    ACT_MASTER_SCORE=`sg_persist_do_cmd $MASTER_SCORE_ATTRIBUTE --query --quiet`
+    ACT_MASTER_SCORE=`ocf_run $MASTER_SCORE_ATTRIBUTE --query --quiet`
     ocf_log debug "$RESOURCE monitor: ACT_MASTER_SCORE=$ACT_MASTER_SCORE"
     
-    ACT_PENDING=`sg_persist_do_cmd $PENDING_ATTRIBUTE --query --quiet`
+    ACT_PENDING=`ocf_run $PENDING_ATTRIBUTE --query --quiet`
     ocf_log debug "$RESOURCE monitor: ACT_PENDING=$ACT_PENDING"
 
     sg_persist_parse_act_pending
@@ -516,7 +496,7 @@ sg_persist_action_monitor() {
         if [ $ACT_MASTER_SCORE -eq $MASTER_SCORE ]; then
             sg_persist_clear_pending
         else
-	        case $ROLE in
+            case $ROLE in
             Master)  
                 if [ $MASTER_SCORE -lt $ACT_MASTER_SCORE ]; then
                     if [ -n "$ACT_PENDING" ] 
@@ -568,11 +548,11 @@ sg_persist_action_monitor() {
     fi
 
     if [ $DO_MASTER_SCORE_UPDATE == "YES" ]; then
-        sg_persist_do_cmd $MASTER_SCORE_ATTRIBUTE --update=$NEW_MASTER_SCORE
+        ocf_run $MASTER_SCORE_ATTRIBUTE --update=$NEW_MASTER_SCORE
     fi
 
     if [ $DO_PENDING_UPDATE == "YES" ]; then
-        sg_persist_do_cmd $PENDING_ATTRIBUTE --update=$NEW_PENDING
+        ocf_run $PENDING_ATTRIBUTE --update=$NEW_PENDING
     fi
 
     if [ ${#REGISTERED_DEVS[*]} -eq 0 ]; then
@@ -614,12 +594,12 @@ sg_persist_action_promote() {
         case $RESERVATION_TYPE in
         1|3|5|6)        
             if [ -z "$reservation_key" ]; then
-                sg_persist_do_cmd $SG_PERSIST --out --reserve --param-rk=$NODE_ID_HEX --prout-type=$RESERVATION_TYPE $dev
+                ocf_run $SG_PERSIST --out --reserve --param-rk=$NODE_ID_HEX --prout-type=$RESERVATION_TYPE $dev
                 if [ $? -ne 0 ]; then
                     return $OCF_ERR_GENERIC
                 fi
             else
-                sg_persist_do_cmd $SG_PERSIST --out --preempt --param-sark=$reservation_key --param-rk=$NODE_ID_HEX --prout-type=$RESERVATION_TYPE $dev
+                ocf_run $SG_PERSIST --out --preempt --param-sark=$reservation_key --param-rk=$NODE_ID_HEX --prout-type=$RESERVATION_TYPE $dev
                 if [ $? -ne 0 ]; then
                     return $OCF_ERR_GENERIC
                 fi
@@ -628,7 +608,7 @@ sg_persist_action_promote() {
 
         7|8) 
             if [ -z "$reservation_key" ]; then
-                sg_persist_do_cmd $SG_PERSIST --out --reserve --param-rk=$NODE_ID_HEX --prout-type=$RESERVATION_TYPE $dev
+                ocf_run $SG_PERSIST --out --reserve --param-rk=$NODE_ID_HEX --prout-type=$RESERVATION_TYPE $dev
                 if [ $? -ne 0 ]
                 then
                     return $OCF_ERR_GENERIC
@@ -659,7 +639,7 @@ sg_persist_action_demote() {
 
         for dev in ${RESERVED_DEVS[*]}
         do
-            sg_persist_do_cmd $SG_PERSIST --out --release --param-rk=$NODE_ID_HEX --prout-type=$RESERVATION_TYPE $dev
+            ocf_run $SG_PERSIST --out --release --param-rk=$NODE_ID_HEX --prout-type=$RESERVATION_TYPE $dev
             if [ $? -ne 0 ]; then
                return $OCF_ERR_GENERIC
             fi
@@ -674,7 +654,7 @@ sg_persist_action_demote() {
 
         for dev in ${REGISTERED_DEVS[*]}
         do
-            sg_persist_do_cmd $SG_PERSIST --out --register --param-rk=$NODE_ID_HEX --param-sark=0 $dev
+            ocf_run $SG_PERSIST --out --register --param-rk=$NODE_ID_HEX --param-sark=0 $dev
             if [ $? -ne 0 ]; then
                return $OCF_ERR_GENERIC
             fi
@@ -707,12 +687,12 @@ sg_persist_action_notify() {
 sg_persist_action_validate_all () {
     if [ -n "$SG_PERSIST_CONF" ] && [ ! -f "$SG_PERSIST_CONF" ]; then
         ocf_log err "Configuration file does not exist: $SG_PERSIST_CONF"
-        return $OCF_ERR_CONFIGURED
+        return $OCF_ERR_INSTALLED
     fi
 
     if [ -z "$RESOURCE" ]; then
         ocf_log err "No resource name specified!"
-        return $OCF_ERR_ARGS
+        return $OCF_ERR_CONFIGURED
     fi
     
     if [ "$OCF_RESKEY_CRM_meta_master_max" != "1" ] && [ "$RESERVATION_TYPE"  != "7" ] && [ "$RESERVATION_TYPE" != "8" ]; then
