sshtunnel RA now fully tested an operational

diff --git a/heartbeat/sshtunnel b/heartbeat/sshtunnel
--- a/heartbeat/sshtunnel
+++ b/heartbeat/sshtunnel
@@ -26,7 +26,7 @@ OCF_RESKEY_tunnel_cluster_nodes_default="yes"
 OCF_RESKEY_tunnel_server_list_default=""
 OCF_RESKEY_pid_dir_default="/var/run/resource-agents"
 OCF_RESKEY_default_user_default="root"
-OCF_RESKEY_tunnel_stop_timeout="5"
+OCF_RESKEY_tunnel_stop_timeout_default="5"
 [ -z "$OCF_RESKEY_crm_mode_binary" ] && OCF_RESKEY_crm_node_binary=$OCF_RESKEY_crm_node_binary_default
 [ -z "$OCF_RESKEY_ssh_binary" ] && OCF_RESKEY_ssh_binary=$OCF_RESKEY_ssh_binary_default
 [ -z "$OCF_RESKEY_ssh_port" ] && OCF_RESKEY_ssh_port=$OCF_RESKEY_ssh_port_default
@@ -35,7 +35,7 @@ OCF_RESKEY_tunnel_stop_timeout="5"
 [ -z "$OCF_RESKEY_tunnel_server_list" ] && OCF_RESKEY_tunnel_server_list=$OCF_RESKEY_tunnel_server_list_default
 [ -z "$OCF_RESKEY_tunnel_pid_dir" ] && OCF_RESKEY_pid_dir=$OCF_RESKEY_pid_dir_default
 [ -z "$OCF_RESKEY_default_user" ] && OCF_RESKEY_default_user=$OCF_RESKEY_default_user_default
-[ -z "$OCF_RESKEY_tunnel_stop_timeout" ] && OCF_RESKEY_stop_timeout=$OCF_RESKEY_stop_timeout
+[ -z "$OCF_RESKEY_tunnel_stop_timeout" ] && OCF_RESKEY_stop_timeout=$OCF_RESKEY_stop_timeout_default
 
 #########################################
 #########################################
@@ -46,72 +46,36 @@ sshtunnel_start()
 	# exit immediately if configuration is not valid
 	sshtunnel_validate_all || exit $?
 
-	# is our tunnel between all nodes in the cluster?
-	if ocf_is_true $OCF_RESKEY_tunnel_cluster_nodes
-	then
-		oldIFS=$IFS
-		IFS=$' \t\n'
-		for node in $( obtain_nodes )
-		do
-			# do nothing if local node
-			[ "$node" == "`uname -n`" ] && continue
-			local pid_file=$OCF_RESKEY_pid_dir/sshtunnel_${node}.pid
+	oldIFS=$IFS
+	IFS=$' \t\n' # we need to set this to get the for loop working fine
+	for node in $( get_server_list )
+	do
+		# do nothing if local node
+		[ "$node" == "`uname -n`" ] && continue
 
-			# do nothing if already started
-			[ -e "$pid_file" ] && is_running `cat $pid_file` \
-				&& ocf_log info "Tunnel to [${node}] already started." && continue
+		# do nothing if already started
+		local pid_file=$OCF_RESKEY_pid_dir/sshtunnel_${node}.pid
+		[ -e "$pid_file" ] && [ ! -z "`cat $pid_file`" ] \
+			&& is_running `cat $pid_file` \
+			&& { ocf_log info "Tunnel to [${node}] already started." ; continue ; }
 
-			# start the tunnel otherwise
-			$OCF_RESKEY_ssh_binary ${OCF_RESKEY_ssh_parametes} -p $OCF_RESKEY_ssh_port ${OCF_RESKEY_default_user}@${node} >/dev/null 2>/dev/null &
-			local pid=$!
-			echo $pid > $pid_file \
-				|| { ocf_log err "Unable to store the tunnel PID to host [${node}] in \"$pid_file\"." ; exit $OCF_ERR_GENERIC ; }
+		# start the tunnel otherwise
+		$OCF_RESKEY_ssh_binary ${OCF_RESKEY_ssh_parameters} -p $OCF_RESKEY_ssh_port ${OCF_RESKEY_default_user}@${node} >/dev/null 2>/dev/null &
+		local pid=$!
+		echo $pid > $pid_file \
+			|| { ocf_log err "Unable to store the tunnel PID to host [${node}] in \"$pid_file\"." ; exit $OCF_ERR_GENERIC ; }
 
-			# try if the start proccess was fine
-			if is_running $pid
-			then
-				ocf_log info "Tunnel to [${node}] created."
-			else
-				ocf_log err "Unable to create the tunnel to [${node}]."
-				exit $OCF_ERR_GENERIC
-			fi
-		done
-		IFS=$oldIFS
-	fi
-	# is our tunnel between a server in server_list ?
-	if [ ! -z "$OCF_RESKEY_tunnel_server_list" ]
-	then
-		oldIFS=$IFS
-		IFS=$' \t\n'
-		for node in $OCF_RESKEY_tunnel_server_list
-		do
-			# validating IPv4, IPv6 and FQDN
-			is_ipv4_valid $node || is_ipv6_valid $node \
-				|| is_fqdn_valid $node \
-				|| { ocf_log warn "Detected invalid address in \"tunnel_server_list\" : [${node}]." ; continue ; }
+		# try if the start proccess was fine
+		if is_running $pid
+		then
+			ocf_log info "Tunnel to [${node}] created."
+		else
+			ocf_log err "Unable to create the tunnel to [${node}]."
+			exit $OCF_ERR_GENERIC
+		fi
+	done
+	IFS=$oldIFS
 
-			# do nothing if already started
-			local pid_file=$OCF_RESKEY_pid_dir/sshtunnel_${node}.pid
-			[ -e "$pid_file" ] && is_running `cat $pid_file` \
-				&& ocf_log info "Tunnel to [$node] already started." && continue
-
-			# start the tunnel otherwise
-			$OCF_RESKEY_ssh_binary ${OCF_RESKEY_ssh_parameters} -p $OCF_RESKEY_ssh_port ${OCF_RESKEY_default_user}@${node} >/dev/null 2>/dev/null &
-			local pid=$!
-			echo $pid > $pid_file \
-				|| { ocf_log err "Unable to store the tunnel PID to host [${node}] in \"$pid_file\"." ; exit $OCF_ERR_GENERIC ; }
-
-			# check if the start operation was fine
-			if is_running $pid
-			then
-				ocf_log info "Tunnel to [${node}] created."
-			else
-				ocf_log err "Unable to create the tunnel to [${node}]."
-				exit $OCF_ERR_GENERIC
-			fi
-		done
-		IFS=$oldIFS
-	fi
 	return $OCF_SUCCESS
 }
 
@@ -122,54 +86,34 @@ sshtunnel_monitor()
 
 	local flag_not_running=0
 
-	# is our tunnel build between all nodes in the cluster?
-	if ocf_is_true $OCF_RESKEY_tunnel_cluster_nodes
+	# If no server configured (empty list), nothing is running
+	server_list=$( get_server_list )
+	if [[ $server_list =~ ^[[:space:]]$ ]]
 	then
+		flag_not_running=1
+	else
 		oldIFS=$IFS
-		IFS=$' \t\n'
-		for node in $( obtain_nodes )
-		do
-			local pid_file=$OCF_RESKEY_pid_dir/sshtunnel_${node}.pid
+		IFS=$' \t\n' # we need to set this to get the for loop working fine
 
+		for node in $server_list
+		do
 			# check nothing if local node
-			[ $node == "`uname -n`" ] && continue
+			[ "$node" == "`uname -n`" ] && continue
 
 			# checking if $pid_file is running
-			[ -r $pid_file ] \
-				&& is_running `cat $pid_file` && continue
-
-			# if this point is reached, the node desn't have a tunnel
-			ocf_log warn "Tunnel to [${node}] found not running. Possible ssh or network problem."
-			flag_not_running=1
-			break
-		done
-		IFS=$oldIFS
-	fi
-
-	# is our tunnel build also between a server in server_list?
-	if [ ! -z "$OCF_RESKEY_tunnel_server_list" ]
-	then
-		oldIFS=$IFS
-		IFS=$' \t\n'
-		for node in $OCF_RESKEY_tunnel_server_list
-		do
-			# validating IPv4, IPv6 and FQDN
 			local pid_file=$OCF_RESKEY_pid_dir/sshtunnel_${node}.pid
-			is_ipv4_valid $node || is_ipv6_valid $node \
-				|| is_fqdn_valid $node \
-				|| { ocf_log warn "Detected invalid address in \"tunnel_server_list\" : [${node}]." ; continue ; }
-
-			# checking if $pid_file is running
-			[ -r $pid_file ] \
-				&& is_running `cat $pid_file` && continue
+			[ -r $pid_file ] && local pid=`cat $pid_file`
+			[ ! -z "$pid" ] && is_running $pid && continue
 
 			# if this point is reached, the remote server desn't have a tunnel
-			ocf_log warn "Tunnel to [${node}] found not running. Possible ssh or network problem."
+			ocf_log warn "Tunnel to [${node}] found not running. Possible causes: ssh or network problem, a node failover/failback or bad config."
 			flag_not_running=1
 			break
 		done
 		IFS=$oldIFS
 	fi
+
+	# if one connection isn't running, return NOT_RUNNING, otherwise SUCCESS
 	ocf_is_true $flag_not_running && return $OCF_NOT_RUNNING
 	return $OCF_SUCCESS
 }
@@ -183,7 +127,7 @@ sshtunnel_stop()
 	kill_all || exit $OCF_ERR_GENERIC
 
 	# log and exit
-	ocf_log info "All tunnels where stopped successfully."
+	ocf_log info "All tunnels where successfully stopped."
 	return $OCF_SUCCESS
 }
 
@@ -192,7 +136,8 @@ sshtunnel_validate_all()
 	have_binary $OCF_RESKEY_crm_node_binary || { ocf_log err "\"crm_node_binary\" binary not found at [${OCF_RESKEY_crm_node_binary}]." ; return $OCF_ERR_INSTALLED ; }
 	have_binary $OCF_RESKEY_ssh_binary || { ocf_log err "\"ssh_binary\" binary not found at [${OCF_RESKEY_ssh_binary}]." ; return $OCF_ERR_INSTALLED ; }
 	have_binary uname || { ocf_log err "The binary \"uname\" was not found." ; return $OCF_ERR_INSTALLED ; }
-	have_binary dig || { ocf_log err "The binary \"dig\" was not found." ; return $OCF_ERR_INSTALLED ; }
+	have_binary kill || { ocf_log err "The binary \"kill\" was not found." ; return $OCF_ERR_INSTALLED ; }
+	have_binary ps || { ocf_log err "The binary \"ps\" was not found." ; return $OCF_ERR_INSTALLED ; }
 	[ -z "$OCF_RESKEY_ssh_port" ] && { ocf_log err "The parameter \"ssh_port\" is not set." ; return $OCF_ERR_CONFIGURED ; }
 	[[ $OCF_RESKEY_ssh_port =~ ^[0-9]*$ ]] || { ocf_log err "The parameter \"ssh_port\" is not an integer. Expected a possitive integer between 1-35536" ; return $OCF_ERR_CONFIGURED ; }
 	[ "$OCF_RESKEY_ssh_port" -ge 1 ] || { ocf_log err "The parameter \"ssh_port\" is out of range. Needed >= 1." ; return $OCF_ERR_CONFIGURED ; }
@@ -238,6 +183,7 @@ Full IPv6 support is expected.
 			</longdesc>
 			<shortdesc lang="en">ssh client options.</shortdesc>
 			<content type="string" default="-n -N -M" />
+		</parameter>
 		<parameter name="ssh_port" unique="0" required="0">
 			<longdesc lang="en">
 				TCP port for using in connections with all other nodes.
@@ -315,10 +261,9 @@ kill_all()
 
 	ocf_log info "Killing all tunnels..."
 
-	local flag_all_tunnel_killed=0
+	local flag_error_killing_connection=0
 
-	# First, kill all nodes used by the cluster (pacemaker nodes)
-	oldIFS=$IFS ; IFS=$' \t\n'
+	oldIFS=$IFS ; IFS=$' \t\n' # we need to set this to get the for loop working fine
 	for node in $( get_server_list )
 	do
 		# check if any server is obtained from get_server_list(). Break if no.
@@ -332,13 +277,14 @@ kill_all()
 		if [ -w $pid_file ]
 		then
 			local pid=`cat $pid_file`
+
 			# if an empty pid file was found, remove it (We know it belongs to this RA because the name)
 			[ -z "$pid" ] \
-				&& rm -r $pid_file && continue
+				&& { rm -r $pid_file ; continue ; }
 
-			# Actually shut down the connection. Finally...
+			# Finally shut down the connection.
 			kill_tunnel $pid \
-				|| { ocf_log warn "Unable to kill tunnel to [$node]..." ; flag_all_tunnel_killed=1 ; }
+				|| { ocf_log warn "Unable to kill tunnel to [$node]..." ; flag_error_killing_connection=1 ; }
 
 			# And remove the pid file of the connection we just stoped
 			rm -f $pid_file 2>/dev/null || ocf_log warn "Unable to delete pid file \"$pid_file\"..."
@@ -346,13 +292,12 @@ kill_all()
 			ocf_log info "Not killing connection to [${node}] because it seems that doesn't exist (no readable/writable PID file)..."
 		fi
 	done
-	IFS=$oldIFS
 
 	# Finally, remove all remaining data belonging to us
-	oldIFS=$IFS ; IFS=$' \t\n'
 	for pid_file in $( ls $OCF_RESKEY_pid_dir/ | grep sshtunnel )
 	do
 		# check the pid file obtained from the dir
+		local pid_file=$OCF_RESKEY_pid_dir/${pid_file}
 		if [ -w $pid_file ]
 		then
 			local pid=`cat $pid_file`
@@ -378,7 +323,8 @@ kill_all()
 	done
 	IFS=$oldIFS
 
-	return $flag_all_tunnel_killed
+	# return != 0 if any connection was impossible to kill
+	return $flag_error_killing_connection
 }
 
 # int kill_tunnel(pid)
@@ -416,7 +362,12 @@ kill_tunnel()
 # in just one space separated list
 get_server_list()
 {
-	echo "$( obtain_nodes ) ${OCF_RESKEY_tunnel_server_list}" || return 1
+	if ocf_is_true $OCF_RESKEY_tunnel_cluster_nodes
+	then
+		echo "$( obtain_nodes ) ${OCF_RESKEY_tunnel_server_list}" || return 1
+	else
+		echo "${OCF_RESKEY_tunnel_server_list}" || return 1
+	fi
 	return 0
 }
 
@@ -443,53 +394,6 @@ is_running() #int pid
 		[ $? -eq 0 ] && return 0
 	fi
 	return 1
-}
-
-# int is_ipv4_valid(string ip)
-# used to know if a given IP is a valid IPv4
-is_ipv4_valid()
-{
-        local retval=1
-        if [ ! -z $1 ]
-        then
-                egrep '^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[0-9]{1,2})(\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[0-9]{1,2})){3}$' <<< $1 > /dev/null
-                if [ $? -eq 0 ]
-                then
-                        retval=0
-                fi
-        fi
-        return $retval
-}
-
-# int is_ipv6_valid(string ip)
-# used to know if a given IP is a valid IPv6
-is_ipv6_valid()
-{
-        local retval=1
-        if [ ! -z $1 ]
-        then
-		egrep -E '^\s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])(.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])(.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])(.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])(.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])(.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])(.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])(.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])){3}))|:)))(%.+)?\s*$' <<< $1 > /dev/null
-                if [ $? -eq 0 ]
-                then
-                        retval=0
-                fi
-        fi
-        return $retval
-}
-
-# int is_fqdn_valid(string fqdn)
-# used to know if a given FQDN is valid (we can get the corresponding ip)
-is_fqdn_valid()
-{
-        local retval=1
-        if [ ! -z $1 ]
-        then
-                if [ `dig +short $1 | wc -l` -ne 0 ] > /dev/null
-                then
-                        retval=0
-                fi
-        fi
-        return $retval
 }
 
 
@@ -533,6 +437,5 @@ case $__OCF_ACTION in
 esac
 rc=$?
 
-# The resource agent may optionally log a debug message
 ocf_log debug "${OCF_RESOURCE_INSTANCE} $__OCF_ACTION returned $rc"
 exit $rc
