Parameter to save running VM's configuration
When save_config_on_stop_default is set to 1 the RA will dump the running VM's config to "config" during resource stop.

diff --git a/heartbeat/VirtualDomain b/heartbeat/VirtualDomain
--- a/heartbeat/VirtualDomain
+++ b/heartbeat/VirtualDomain
@@ -22,12 +22,14 @@ OCF_RESKEY_autoset_utilization_cpu_default="true"
 OCF_RESKEY_autoset_utilization_hv_memory_default="true"
 OCF_RESKEY_migrateport_default=$(( 49152 + $(ocf_maybe_random) % 64 ))
 OCF_RESKEY_CRM_meta_timeout_default=90000
+OCF_RESKEY_save_config_on_stop_default=0
 
 : ${OCF_RESKEY_force_stop=${OCF_RESKEY_force_stop_default}}
 : ${OCF_RESKEY_autoset_utilization_cpu=${OCF_RESKEY_autoset_utilization_cpu_default}}
 : ${OCF_RESKEY_autoset_utilization_hv_memory=${OCF_RESKEY_autoset_utilization_hv_memory_default}}
 : ${OCF_RESKEY_migrateport=${OCF_RESKEY_migrateport_default}}
 : ${OCF_RESKEY_CRM_meta_timeout=${OCF_RESKEY_CRM_meta_timeout_default}}
+: ${OCF_RESKEY_save_config_on_stop=${OCF_RESKEY_save_config_on_stop_default}}
 #######################################################################
 
 ## I'd very much suggest to make this RA use bash,
@@ -147,6 +149,15 @@ into the hv_memory utilization of the resource when the monitor is executed.
 This port will be used in the qemu migrateuri. If unset, the port will be a random highport.
 </longdesc>
 <shortdesc lang="en">Port for migrateuri</shortdesc>
+<content type="integer" />
+</parameter>
+
+<parameter name="save_config_on_stop" unique="0" required="0">
+<longdesc lang="en">
+Changes to a running VM's config are normally lost on stop. 
+This parameter instructs the RA to save the configuration back to the xml file provided in the "config" parameter.
+</longdesc>
+<shortdesc lang="en">Save running VM's config back to its config file</shortdesc>
 <content type="integer" />
 </parameter>
 
@@ -439,6 +450,25 @@ VirtualDomain_Stop() {
 				else
 					ocf_log error "Failed to save snapshot state of ${DOMAIN_NAME} on stop"
 				fi
+			fi
+
+			# save config if needed
+			if [ "$OCF_RESKEY_save_config_on_stop" = 1 ]; then	
+				CFGTMP=$(mktemp -t vmcfgsave.XXX)
+				virsh $VIRSH_OPTIONS dumpxml ${DOMAIN_NAME} > ${CFGTMP}
+				if [ -s ${CFGTMP} ]; then	
+					if virt-xml-validate ${CFGTMP} domain 2>/dev/null ;	then
+						ocf_log info "Saving domain $DOMAIN_NAME to ${OCF_RESKEY_config}. Please make sure it's present on all nodes."
+						if ! mv ${CFGTMP} ${OCF_RESKEY_config} ; then	
+							ocf_log warn "Moving ${CFGTMP} to ${OCF_RESKEY_config} failed."
+						fi
+					else
+						ocf_log warn "Domain $DOMAIN_NAME config failed to validate after dump. Skipping config update."
+					fi
+				else
+					ocf_log warn "Domain $DOMAIN_NAME config has 0 size. Skipping config update."
+				fi
+				rm -f ${CFGTMP}
 			fi
 
 			# issue the shutdown if save state didn't shutdown for us
