High: VirtualDomain: Support saving and restoring virtual machine snapshot state files

diff --git a/heartbeat/VirtualDomain b/heartbeat/VirtualDomain
--- a/heartbeat/VirtualDomain
+++ b/heartbeat/VirtualDomain
@@ -149,6 +149,19 @@ This port will be used in the qemu migrateuri. If unset, the port will be a rand
 <content type="integer" />
 </parameter>
 
+<parameter name="snapshot">
+<longdesc lang="en">
+Path to the snapshot directory where the virtual machine image will be stored.  When this 
+parameter is set, the virtual machine's RAM state will be saved to a file in the snapshot
+directory when stopped.  If on start a state file is present for the domain, the domain
+will be restored to the same state it was in right before it stopped last.
+</longdesc>
+<shortdesc lang="en">
+Restore state on start/stop
+</shortdesc>
+<content type="string" default=""/>
+</parameter>
+
 </parameters>
 
 <actions>
@@ -282,9 +295,22 @@ VirtualDomain_Status() {
 }
 
 VirtualDomain_Start() {
+	local snapshotimage
+
 	if VirtualDomain_Status; then
 		ocf_log info "Virtual domain $DOMAIN_NAME already running."
 		return $OCF_SUCCESS
+	fi
+
+	snapshotimage="$OCF_RESKEY_snapshot/${DOMAIN_NAME}.state"
+	if [ -n "$OCF_RESKEY_snapshot" -a -f "$snapshotimage" ]; then
+		virsh restore $snapshotimage
+		if [ $? -eq 0 ]; then
+			rm -f $snapshotimage
+			return $OCF_SUCCESS
+		fi
+		ocf_log error "Failed to restore ${DOMAIN_NAME} from state file in ${OCF_RESKEY_snapshot} directory."
+		return $OCF_ERR_GENERIC
 	fi
 
 	virsh $VIRSH_OPTIONS start ${DOMAIN_NAME}
@@ -305,44 +331,62 @@ VirtualDomain_Stop() {
 	local status
 	local shutdown_timeout
 	local out ex
+	local needshutdown=1
 
 	VirtualDomain_Status
 	status=$?
 
 	case $status in
 		$OCF_SUCCESS)
-			if ! ocf_is_true $OCF_RESKEY_force_stop; then
-				# Issue a graceful shutdown request
-				ocf_log info "Issuing graceful shutdown request for domain ${DOMAIN_NAME}."
-				virsh $VIRSH_OPTIONS shutdown ${DOMAIN_NAME}
-				# The "shutdown_timeout" we use here is the operation
-				# timeout specified in the CIB, minus 5 seconds
-				shutdown_timeout=$(( $NOW + ($OCF_RESKEY_CRM_meta_timeout/1000) -5 ))
-				# Loop on status until we reach $shutdown_timeout
-				while [ $NOW -lt $shutdown_timeout ]; do
-					VirtualDomain_Status
-					status=$?
-					case $status in
-						$OCF_NOT_RUNNING)
-							# This was a graceful shutdown. Clean
-							# up and return.
-							VirtualDomain_Cleanup_Statefile
-							return $OCF_SUCCESS
-							;;
-						$OCF_SUCCESS)
-							# Domain is still running, keep
-							# waiting (until shutdown_timeout
-							# expires)
-							sleep 1
-							;;
-						*)
-							# Something went wrong. Bail out and
-							# resort to forced stop (destroy).
-							break;
-					esac
-					NOW=$(date +%s)
-				done
+			if ocf_is_true $OCF_RESKEY_force_stop; then
+				# if force stop, don't bother attempting graceful shutdown.
+				break;
 			fi
+
+			ocf_log info "Issuing graceful shutdown request for domain ${DOMAIN_NAME}."
+
+			if [ -n "$OCF_RESKEY_snapshot" ]; then
+				virsh save $DOMAIN_NAME "$OCF_RESKEY_snapshot/${DOMAIN_NAME}.state"
+				if [ $? -eq 0 ]; then
+					needshutdown=0
+				else
+					ocf_log error "Failed to save snapshot state of ${DOMAIN_NAME} on stop"
+				fi
+			fi
+
+			# issue the shutdown if save state didn't shutdown for us
+			if [ $needshutdown -eq 1 ]; then
+				# Issue a graceful shutdown request
+				virsh $VIRSH_OPTIONS shutdown ${DOMAIN_NAME}
+			fi
+
+			# The "shutdown_timeout" we use here is the operation
+			# timeout specified in the CIB, minus 5 seconds
+			shutdown_timeout=$(( $NOW + ($OCF_RESKEY_CRM_meta_timeout/1000) -5 ))
+			# Loop on status until we reach $shutdown_timeout
+			while [ $NOW -lt $shutdown_timeout ]; do
+				VirtualDomain_Status
+				status=$?
+				case $status in
+					$OCF_NOT_RUNNING)
+						# This was a graceful shutdown. Clean
+						# up and return.
+						VirtualDomain_Cleanup_Statefile
+						return $OCF_SUCCESS
+						;;
+					$OCF_SUCCESS)
+						# Domain is still running, keep
+						# waiting (until shutdown_timeout
+						# expires)
+						sleep 1
+						;;
+					*)
+						# Something went wrong. Bail out and
+						# resort to forced stop (destroy).
+						break;
+				esac
+				NOW=$(date +%s)
+			done
 			;;
 		$OCF_NOT_RUNNING)
 			ocf_log info "Domain $DOMAIN_NAME already stopped."
