* validate-all * removed unused code * misc cleanups
CVS patchset: 7370
CVS date: 2005/08/18 04:40:57

--HG--
extra : convert_revision : db3cc76c1da12f1e974ea84fc4a2060952bbc888

diff --git a/heartbeat/WinPopup.in b/heartbeat/WinPopup.in
--- a/heartbeat/WinPopup.in
+++ b/heartbeat/WinPopup.in
@@ -24,24 +24,22 @@
 
 #######################################################################
 
-ARGS="$0 $*"
-
 us=`uname -n`
 
 usage() {
-  echo "Usage: $0 {start|stop|status|monitor}"
-  echo "$Id: WinPopup.in,v 1.2 2005/07/15 09:51:56 sunjd Exp $"
+  echo "Usage: $0 {start|stop|status|monitor|validate-all|meta-data}"
+  echo "$Id: WinPopup.in,v 1.3 2005/08/18 04:40:57 sunjd Exp $"
 }
 
 meta_data() {
 	cat <<END
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
-<resource-agent name="WinPopup" version="0.9">
+<resource-agent name="WinPopup">
 <version>1.0</version>
 
 <longdesc lang="en">
-Resource script for WinPopup. It sends sends WinPopups message to a 
+Resource script for WinPopup. It sends WinPopups message to a 
 sysadmin's workstation whenever a takeover occurs.
 </longdesc>
 <shortdesc lang="en">WinPopup resource agent</shortdesc>
@@ -49,7 +47,7 @@ sysadmin's workstation whenever a takeover occurs.
 <parameters>
 <parameter name="hostfile" unique="0">
 <longdesc lang="en">
-The subject of the email.
+The file containing the hosts to send WinPopup messages to.
 </longdesc>
 <shortdesc lang="en">Host file</shortdesc>
 <content type="string" default="" />
@@ -61,6 +59,7 @@ The subject of the email.
 <action name="stop" timeout="30" />
 <action name="status" depth="0" timeout="10" interval="10" start-delay="10" />
 <action name="monitor" depth="0" timeout="10" interval="10" start-delay="10" />
+<action name="validate-all" timeout="5" />
 <action name="meta-data" timeout="5" />
 </actions>
 </resource-agent>
@@ -78,7 +77,7 @@ sendWinPopup() {
     done
   else
     ocf_log err "Workstation file $hostfile missing or corrupt!"
-    return 2
+    return $OCF_ERR_ARGS
   fi
 
   return $?
@@ -112,22 +111,79 @@ WinPopupStop () {
 WinPopupStatus () {
 	echo "Do nothing ... "
 
-	return 0
+	return $OCF_SUCCESS
+}
+
+# A not reliable IP address checking function, which only picks up those _obvious_ violations...
+#
+# It accepts IPv4 address in dotted quad notation, for example "192.168.1.1"
+#
+# 100% confidence whenever it reports "negative", 
+# but may get false "positive" answer. 
+# 
+CheckIP() {
+  ip="$1"
+  case $ip in
+    *[^0-9.]*) #got invalid char
+	false;;
+    .*|*.) #begin or end by ".", which is invalid
+	false;;
+    *..*) #consecutive ".", which is invalid
+	false;;
+    *.*.*.*.*) #four decimal dots, which is too many
+	false;;
+    *.*.*.*) #exactly three decimal dots, candidate, evaluate each field
+	local IFS=.
+	set -- $ip
+	if
+	    ( [ $1 -le 254 ] && [ $2 -le 254 ] && [ $3 -le 254 ] && [ $4 -le 254 ] )
+	then
+	    true
+	fi	   
+	;;
+    *) #less than three decimal dots
+	false;;
+  esac
+  return $? # This return is unnecessary, this comment too :)
+}
+
+WinPopupValidateAll () {
+  if [ ! -s "$hostfile" ] ; then
+    ocf_log err "Workstation file $hostfile missing or corrupt!"
+    return $OCF_ERR_ARGS
+  fi
+
+  # What kind of hostfiles are valid? 
+  # We stick to the definition that, a hostfile is valid if and only if it 
+  # contains at least one valid host to send WinPopup message to.
+
+#  have_valid_host=no
+  for host in `cat $hostfile`; do
+	nmblookup $host 2>&1 | grep -q "failed to find name $host\>"
+	if [ $? -ne 0 ]; then
+#	  have_valid_host=yes
+	  return $OCF_SUCCESS
+	fi
+	# $host is not a netbios name, an IP address maybe?
+	if CheckIP "$host"; then
+#	  have_valid_host=yes
+	  return $OCF_SUCCESS
+	fi
+  done
+
+  ocf_log err "Workstation file $hostfile contains no valid host!"
+  return $OCF_ERR_CONFIGURED
 }
 
 if
-  ( [ $# -eq 0 ] || [ $# -gt 1 ] )
+  ( [ $# -ne 1 ] )
 then
   usage
-  exit 1
+  exit $OCF_ERR_ARGS
 fi
 
 # See how the environment virables were set.
-if [ ! -z "$OCF_RESKEY_hostfile" ]; then
-  hostfile=$OCF_RESKEY_hostfile
-else
-  hostfile="hosts"
-fi
+hostfile=${OCF_RESKEY_hostfile:-hosts}
 
 case "$1" in
   meta-data)
@@ -145,6 +201,9 @@ case "$1" in
   status|monitor)
 	WinPopupStatus
 	;;
+  validate-all)
+	WinPopupValidateAll
+	;;
   usage)
 	usage
 	exit $OCF_SUCCESS
@@ -156,4 +215,3 @@ case "$1" in
 esac
 
 exit $?
-
