Add migration support to Xen RA.
--HG--
extra : convert_revision : 26d5068a03195c9d8a850b5526b06824dabe8ae6

diff --git a/heartbeat/Xen.in b/heartbeat/Xen.in
--- a/heartbeat/Xen.in
+++ b/heartbeat/Xen.in
@@ -126,6 +126,41 @@ Xen_Stop() {
   fi
 }
 
+Xen_Migrate_From {
+  target_node="$OCF_RESKEY_CRM_meta_migrate_to"
+  if 
+    Xen_Status
+  then
+    ocf_log info "$DOMAIN_NAME: Starting xm migrate to $target_node"
+    xm migrate --live $DOMAIN_NAME $target_node
+    rc=$?
+    if
+      [ $rc -ne 0 ]
+    then
+      ocf_log err "$DOMAIN_NAME: xm migrate to $target_node failed: $rc"
+      return $OCF_ERR_PERM
+    else 
+      ocf_log err "$DOMAIN_NAME: xm migrate to $target_node succeeded."
+      return $OCF_SUCCESS
+    fi
+  else
+    ocf_log err "$DOMAIN_NAME: migrate_from: Not active locally!"
+    return $OCF_ERR_PERM
+  fi
+}
+
+Xen_Migrate_To {
+  if 
+    Xen_Status
+  then
+    ocf_log info "$DOMAIN_NAME: Active locally, migration successful"
+    return $OCF_SUCCESS
+  else
+    ocf_log err "$DOMAIN_NAME: Not active locally, migration failed!"
+    return $OCF_ERR_PERM
+  fi
+}
+
 Xen_Validate_All() {
   return $OCF_SUCCESS
 }
@@ -142,6 +177,10 @@ case $1 in
   start)		Xen_Start
 			;;
   stop)			Xen_Stop
+			;;
+  migrate_to)		Xen_Migrate_To
+			;;
+  migrate_from)		Xen_Migrate_From
 			;;
   monitor)		Xen_Monitor
 			;;
