(Done by Sun Xun <xunsun@cn.ibm.com>) * validate-all * check for service status at the beginning of xup_start() and xup_stop() * dont require OCF instance parameters when doing "meta-data", "usage"
CVS patchset: 7327
CVS date: 2005/08/12 05:50:01

--HG--
extra : convert_revision : bd54ea61fdc51d917b92c042dbd6bc3a1539cd06

diff --git a/heartbeat/Xinetd.in b/heartbeat/Xinetd.in
--- a/heartbeat/Xinetd.in
+++ b/heartbeat/Xinetd.in
@@ -4,7 +4,7 @@
 #
 #	Copyright (C) 2003 Charlie Brooks
 #
-#  WARNING:  tested ONLY on Red Hat 7.3 at this time.
+# WARNING:	Tested ONLY on Red Hat 7.3 and Fedora Core 2/4 at this time.
 #
 # Author:	Charlie Brooks <ha@HBCS.Org>
 # Description:	given parameters of a service name and start|stop|status,
@@ -31,7 +31,7 @@ meta_data() {
 	cat <<END
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
-<resource-agent name="Xinetd" version="0.9">
+<resource-agent name="Xinetd">
 <version>1.0</version>
 
 <longdesc lang="en">
@@ -56,6 +56,7 @@ The service name managed by xinetd.
 <action name="restart" timeout="40" />
 <action name="status" depth="0" timeout="10" interval="10" start-delay="10" />
 <action name="monitor" depth="0" timeout="10" interval="10" start-delay="10" />
+<action name="validate-all" timeout="5" />
 <action name="meta-data" timeout="5" />
 </actions>
 </resource-agent>
@@ -73,15 +74,20 @@ hup_inetd () {
       if ! kill -HUP `cat $XPIDFILE`; then
           ocf_log err "Could not SigHUP xinetd superdaemon!"
           ocf_log err "perhaps we are booting after a system crash"
-          exit 2
+          exit $OCF_ERR_GENERIC
       fi
     else
        ocf_log info "xinetd superdaemon PID file $XPIDFILE not found!"
        ocf_log info "perhaps we are currently booting the system."
-fi
+    fi
 }
 
 xup_start () {
+  if [ "running" = "`xup_status`" ]; then
+    ocf_log info "Service $service already started"
+    exit $OCF_SUCCESS
+  fi
+
   ocf_log "info" "$0: enabling in $RCFILE"
   if gawk '!/disable/' $RCFILE > $RCFILE.xup
     then
@@ -99,6 +105,11 @@ xup_start () {
 }
 
 xup_stop () {
+  if [ "stopped" = "`xup_status`" ]; then
+    ocf_log info "Service $service already stopped"
+    exit $OCF_SUCCESS
+  fi
+
   ocf_log "info" "$0: disabling in $RCFILE"
   if gawk '!/disable/;/{/{printf "\tdisable\t\t\t= yes\n"}' $RCFILE >$RCFILE.xup
     then
@@ -116,7 +127,7 @@ xup_stop () {
 }
 
 xup_usage () {
-        echo "Usage: $0 {start|stop|restart|status|monitor|meta-data}"
+        echo "Usage: $0 {start|stop|restart|status|monitor|validate-all|meta-data}"
 	return 0
 }
 
@@ -130,18 +141,284 @@ xup_status () {
 	fi
 }
 
+#
+#	Check if the arg is a valid integer
+#
+CheckInteger() {
+#	Examples of valid integer: "1080", "1", "0080", "0", "0000"
+#	Examples of invalid integer: "1080bad", ""
+  case "$1" in
+    "") #empty string 
+	false;;
+    *[^0-9]*) #got invalid char
+	false;;
+    *) #no invalid char, and has at least one digit, so is a good integer
+	true;;
+  esac
+}
+
+#
+#	Check if the arg is a valid umask
+#
+CheckUmask() {
+#	Examples of valid umask: "100", "1", "000", "0"
+#	Examples of invalid umask: "108", "bad", "1111" ""
+  case "$1" in
+    [0-7])
+	true;;
+    [0-7][0-7])
+	true;;
+    [0-7][0-7][0-7])
+	true;;
+    *)
+	false;;
+  esac
+}
+
+# Check (part of) the attributes based on xinetd.conf(5) and xinetd source code
+#	confparse.c
+#	parsers.c
+#	attr.h
+check_attributes () {
+  # Empty these attributes before validating them 
+  unset socket_type wait server user protocol port group instances \
+	type flags disable nice umask 
+  export $*
+  if [ $? -ne 0 ]; then
+	return $OCF_ERR_GENERIC
+  fi
+
+  case $disable in
+	"")	disable=no # Default to no.
+		;;
+	yes|no)	;;
+	*)	ocf_log err "Invalid value for disable [$disable] in $RCFILE, yes|no please"
+		exit $OCF_ERR_CONFIGURED
+		;;
+  esac
+
+  case $socket_type in
+	"") 	socket_type=dgram
+		# Default value for socket_type is dgram.
+		;;
+	stream|dgram|raw|seqpacket)
+		;;
+	*)	ocf_log err "Invalid socket type $socket_type in $RCFILE"
+		exit $OCF_ERR_CONFIGURED
+		;;
+  esac
+
+  case $wait in # Wait has no default value.
+	yes|no)	;;
+	*)	ocf_log err "Invalid waid [$wait] in $RCFILE, yes|no please"
+		exit $OCF_ERR_CONFIGURED
+	    	;;
+  esac
+
+  case $type in
+  # Default value for type is RPC or INTERNAL, determined at compile time.
+  # It may be a list in $RCFILE, however we only capture the first one.
+	""|RPC|INTERNAL|UNLISTED|SPECIAL|TCPMUX|TCPMUXPLUS)
+		;;
+	*)	ocf_log err "Invalid service type [$type] in $RCFILE"
+		exit $OCF_ERR_CONFIGURED
+		;;
+  esac
+
+  if [ ! -z $type -a "INTERNAL" != "$type" ]; then
+  # Type is explicitly set to EXTERNAL, hence server and user are necessary.
+	case $server in
+	    "")	ocf_log err "Please specify server in $RCFILE"
+		exit $OCF_ERR_CONFIGURED
+		;;
+	    /*)	if [ -x $server ]; then
+			: OK
+	 	else
+			ocf_log err "Server $server is not executable"
+			exit $OCF_ERR_CONFIGURED
+		fi
+		;;
+	    *)	ocf_log err "Server $server is not of obsolute path"
+		exit $OCF_ERR_CONFIGURED
+		;;
+	esac 
+
+	case $user in
+	    "")	ocf_log err "Please specify user in $RCFILE"
+		exit $OCF_ERR_CONFIGURED
+		;;
+	    *)	getent passwd $user >/dev/null 2>&1
+		if [ $? -ne 0 ]; then
+			ocf_log err "User $user does not exist!"
+			exit $OCF_ERR_CONFIGURED
+		fi
+		;;
+	esac
+
+	# Protocol is necessary when type is MUX
+	if [ $type = "TCPMUX" -o $type ="TCPMUXPLUS" ]; then
+	    case $protocol in
+		"")	ocf_log err "Please specify protocol in $RCFILE"
+			exit $OCF_ERR_CONFIGURED
+			;;
+		*)	get protocols $protocol >/dev/null 2>&1
+			if [ $? -ne 0 ]; then
+			    ocf_log err "Invalid protocol [$protocol] in $RCFILE"
+			    exit $OCF_ERR_CONFIGURED
+			fi
+			;;
+  	    esac
+	fi
+  fi
+
+  case $group in
+	"")	;; # OK to be empty, the group for $user is used
+	 *)	getent group $group >/dev/null 2>&1
+	if [ $? -ne 0 ]; then
+		ocf_log err "Group $group does not exist!"
+		exit $OCF_ERR_CONFIGURED
+	fi
+	;;
+  esac
+
+  case $flags in
+  # Default value for flags is REUSE.
+  # It may be a list in $RCFILE, however we only capture the first one.
+	"")	flags=RESUME
+		;;
+	REUSE|INTERCEPT|NORETRY|IDONLY|NAMEINARGS|NODELAY|KEEPALIVE|NOLIBWRAP|SENSOR|IPv4|IPv6)	;;
+	*)	ocf_log err "Invalid flags [$flags] in $RCFILE"
+		exit $OCF_ERR_CONFIGURED
+		;;
+  esac
+
+  case $instances in
+	""|[Uu][Nn][Ll][Ii][Mm][Ii][Ti][Ee][Dd])	;;
+	*)	if CheckInteger $instances; then
+		    : OK
+		else
+		    ocf_log err "Invalid instances [$instances] in $RCFILE, non-negative integer expected"
+		    exit $OCF_ERR_CONFIGURED
+		fi
+		;;
+  esac
+
+  case $nice in
+	"")	;;
+	*)	local foo=`echo $nice | sed s/^-//`
+		if CheckInteger $foo; then
+		    : OK
+		else
+		    ocf_log err "Invalid nice [$nice] in $RCFILE, integer expected"
+		    exit $OCF_ERR_CONFIGURED
+		fi
+		;;
+  esac
+
+  if [ ! -z $umask ]; then
+	if CheckUmask $umask; then
+	    : OK
+	else
+	    ocf_log err "Invalid umask [$umask] in $RCFILE"
+	    exit $OCF_ERR_CONFIGURED
+	fi
+  fi
+}
+
+xup_validate_all () {
+# Parse the $RCFILE for necessary attributes, assume $RCFILE does not
+# contain "include" or "includedir" directives.
+  space="[ \t]*"
+  leading_space="^$space"
+  trailing_space="$space$"
+  comment="$space\#"
+
+  # Strip comments, delete blank lines.
+  stripped=`sed -e "/^$comment/d" -e "/=$trailing_space/d" -e "/$leading_space$/d" $RCFILE`
+ 
+  stripped=`echo $stripped`
+  # At this stage, stripped="service <service-name> { attribute-list }".
+  case $stripped in
+	*#*)
+	ocf_log err "Descriptor file $RCFILE contains extra \"#\", which is forbidden"
+	exit $OCF_ERR_CONFIGURED
+	;;
+
+	service*)
+	case $stripped in
+	    *[^\	\ +-]=*)
+		ocf_log err "Attribute needs a space before operator ="
+		exit $OCF_ERR_CONFIGURED
+		;;
+	    *[^\	\ ][+-]=*)
+		ocf_log err "Attribute needs a space before operator [+-]="
+		exit $OCF_ERR_CONFIGURED
+		;;
+	    *)	;;
+	esac
+
+	# Strip leading "service" keyword, remove spaces surrounding "=".
+	stripped=`echo $stripped | sed -e "s/^service//" -e "s/-=/ /g" \
+			-e "s/+=/=/g" -e "s/$space=$space/=/g"`
+	# At this stage, stripped=" <service-name> { attribute-list }",
+	# note that the leading space before <service-name> is significant.
+	case $stripped in
+	    " "*)
+	    stripped=`echo $stripped | sed -e "s/$leading_space[^ \t]\+$space//"`
+	    # At this stage, stripped="{ attribute-list }"
+	    case $stripped in
+		{*})
+		stripped=`echo $stripped | sed -e "s/^{//" -e "s/}$//"`
+		# At this stage, stripped=<attribute-list>
+#  		    echo $stripped
+		check_attributes "$stripped"
+		;;
+
+		*)
+		ocf_log err "Attrbute list should be contained in {}"
+		exit $OCF_ERR_CONFIGURED
+		;;
+	    esac
+	    ;;
+
+	    *)
+	    ocf_log err "Service name should follow the service key word"
+	    exit $OCF_ERR_CONFIGURED
+	    ;;
+	esac
+	;;
+
+	*)
+	ocf_log err "Service key word is necessary in $RCFILE"
+	exit $OCF_ERR_CONFIGURED
+	;;
+  esac
+}
 if
-  ( [ $# -eq 0 ] || [ $# -gt 1 ] )
+  ( [ $# -ne 1 ] )
 then
   xup_usage
-  exit 1
+  exit $OCF_ERR_ARGS
 fi
+
+# These operations do not require OCF instance parameters to be set
+case "$1" in
+  meta-data)
+	meta_data
+	exit $OCF_SUCCESS
+	;;
+  usage)
+	xup_usage
+	exit $OCF_SUCCESS
+	;;
+  *)	;;
+esac
 
 if 
   [ -z "$OCF_RESKEY_service" ]
 then
-  xup_usage
-  exit 1
+  ocf_log err "Please set OCF_RESKEY_service to the service managed by Xinetd"
+  exit $OCF_ERR_ARGS
 fi
 
 service=$OCF_RESKEY_service
@@ -150,17 +427,12 @@ PIDFILE=$VARRUN/xup$service
 
 # Make sure the OCF_RESKEY_service is a valid xinetd service name
 if ! [ -f $RCFILE ]; then
-    ocf_log "err" "Service descriptor /etc/xinetd.d/$service not found!"
-    xup_usage
-    exit 1
+    ocf_log err "Service descriptor $RCFILE not found!"
+    exit $OCF_ERR_ARGS
 fi
 
 # See how we were called.
 case "$1" in
-  meta-data)
-	meta_data
-	exit $OCF_SUCCESS
-	;;
   start)
 	xup_start
 	;;
@@ -174,9 +446,8 @@ case "$1" in
   status|monitor)
 	xup_status
 	;;
-  usage)
-	xup_usage
-	exit $OCF_SUCCESS
+  validate-all)
+	xup_validate_all
 	;;
   *)
 	xup_usage
