My bad. Apparently "export -n" isn't as universal as I expected. In paricular it fails on Solaris (I _love_ Solaris). The behaviour under Solaris' /bin/sh is that variables are not automatically reexported. Thus we test to see if CFLAGS is being exported and only run "export -n" in that case. This also avoids any warnings that "export -n" may throw if CFLAGS was not exported. Aditionally, I have added a || true, so that even if "export -n" is called it will not cause configure to bomb out. This is the same behaviour as if this code was not there at all.
CVS patchset: 1163
CVS date: 2002/07/17 08:19:22

--HG--
extra : convert_revision : 72265415cefdfa43e911c055da795431dfc00156

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -5,7 +5,7 @@ dnl automake stuff
 dnl     added by Michael Moerz <e9625136@stud3.tuwien.ac.at> February 2001
 
 dnl Initialiase, with sanity check of a unique file in the hierarchy
-AC_REVISION($Revision: 1.109 $) dnl cvs revision
+AC_REVISION($Revision: 1.110 $) dnl cvs revision
 AC_INIT(heartbeat.spec.in)
 AC_CONFIG_AUX_DIR(.)
 AC_CANONICAL_HOST
@@ -832,8 +832,10 @@ dnl envornment, then the new CFLAGS will also be exported
 dnl to sub processes. This causes a problem when configure
 dnl is run in the libltdl directory. Horms 16th July 2002
 dnl               
-export CFLAGS
-export -n CFLAGS
+
+if export | fgrep " CFLAGS=" > /dev/null; then
+	export -n CFLAGS || true # We don't want to bomb out if this fails
+fi
 
 if test "$GCC" = yes; then
   CFLAGS="$CFLAGS -ggdb3 $CC_WARNINGS"
