Dev: ocft: simplify package installation

diff --git a/tools/ocft/caselib.in b/tools/ocft/caselib.in
--- a/tools/ocft/caselib.in
+++ b/tools/ocft/caselib.in
@@ -47,40 +47,22 @@ agent_install()
 
   for pkg in "$@"; do
     if [ -e /etc/SuSE-release ]; then
-      if ! rpm -ql "$pkg" >/dev/null 2>&1; then
-        echo "${__OCFT__showhost}Installing $pkg ..."
-        zypper -q install -y "$pkg" >/dev/null 2>&1
-        if ! rpm -ql "$pkg" >/dev/null 2>&1; then
-          echo
-          echo "${__OCFT__showhost}ERROR: Install '$pkg' failed."
-          quit 2
-        fi
-        echo "done"
+      if ! zypper -q install -y "$pkg" >/dev/null 2>&1; then
         echo
+        echo "${__OCFT__showhost}ERROR: Install '$pkg' failed."
+        quit 2
       fi
     elif [ -e /etc/debian_version ]; then
-      if ! dpkg -L "$pkg" >/dev/null 2>&1; then
-        echo "${__OCFT__showhost}Installing $pkg ..."
-        apt-get -y install "$pkg" >/dev/null 2>&1
-        if ! dpkg -L "$pkg" >/dev/null 2>&1; then
-          echo
-          echo "${__OCFT__showhost}ERROR: Install '$pkg' failed."
-          quit 2
-        fi
-        echo "done"
+      if ! apt-get -y install "$pkg" >/dev/null 2>&1; then
         echo
+        echo "${__OCFT__showhost}ERROR: Install '$pkg' failed."
+        quit 2
       fi
     elif [ -e /etc/redhat-release ]; then
-      if ! rpm -ql "$pkg" >/dev/null 2>&1; then
-        echo "${__OCFT__showhost}Installing $pkg ..."
-        yum -y install "$pkg" >/dev/null 2>&1
-        if ! rpm -ql "$pkg" >/dev/null 2>&1; then
-          echo
-          echo "${__OCFT__showhost}ERROR: Install '$pkg' failed."
-          quit 2
-        fi
-        echo "done"
+      if ! yum -y install "$pkg" >/dev/null 2>&1; then
         echo
+        echo "${__OCFT__showhost}ERROR: Install '$pkg' failed."
+        quit 2
       fi
     else
       echo "${__OCFT__showhost}ERROR: Cannot detect your OS type."
