Low: Tools: ocft: fix remote shell

diff --git a/tools/ocft/caselib.in b/tools/ocft/caselib.in
--- a/tools/ocft/caselib.in
+++ b/tools/ocft/caselib.in
@@ -1,5 +1,26 @@
-# Author: John Shi
-# jshi@suse.de
+#
+# Copyright (c) 2010 Novell Inc, John Shi
+#           All Rights Reserved.
+#
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of version 2 of the GNU General Public License as
+# published by the Free Software Foundation.
+#
+# This program is distributed in the hope that it would be useful, but
+# WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
+#
+# Further, this software is distributed without any warranty that it is
+# free of the rightful claim of any third person regarding infringement
+# or the like.  Any license provided herein, whether implied or
+# otherwise, applies only to this software file.  Patent licenses, if
+# any, provided herein do not apply to combinations of this program with
+# other software, or any other product whatsoever.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write the Free Software Foundation,
+# Inc., 59 Temple Place - Suite 330, Boston MA 02111-1307, USA.
+
 
 quit()
 {
@@ -148,13 +169,14 @@ backbash_start()
     quit 1
   fi
 
-  if lsof ${host}_r ${host}_w >/dev/null 2>&1; then
+  if lsof $CASES_DIR/${host}_r $CASES_DIR/${host}_w >/dev/null 2>&1; then
     echo "${showhost}ERROR: Connection exist with $host, break this CASE."
     quit 1
   fi
-  if [ ! -p "${host}_r" ] || [ ! -p "${host}_w" ]; then
-    if ! mkfifo ${host}_r ${host}_w >/dev/null 2>&1; then
-      echo "${showhost}ERROR: Could not create pipe file, break this CASE."
+  if [ ! -p "$CASES_DIR/${host}_r" ] || [ ! -p "$CASES_DIR/${host}_w" ]; then
+    rm -f $CASES_DIR/${host}_r $CASES_DIR/${host}_w
+    if ! mkfifo $CASES_DIR/${host}_r $CASES_DIR/${host}_w >/dev/null 2>&1; then
+      echo "${showhost}ERROR: Could not create pipe file: $CASES_DIR/${host}_*, break this CASE."
       quit 1
     fi
   fi
@@ -233,7 +255,7 @@ backbash_stop()
   if [ -n "$wfd" ]; then
     cat >&$wfd <<<'quit 0'
   fi
-  rm -f ${host}_r ${host}_w
+  rm -f $CASES_DIR/${host}_r $CASES_DIR/${host}_w
 }
 
 
@@ -244,7 +266,7 @@ CASES_DIR=/var/lib/@PACKAGE_NAME@/ocft/cases
 atexit_num=0
 
 . $AGENT_ROOT/.ocf-returncodes || {
-  echo "${showhost}ERROR: .ocf-* not found, break this CASE."
+  echo "${showhost}ERROR: .ocf-returncodes not found, break this CASE."
   quit 1
 }
 
