resource-agents: isAlive error logging for file systems
This change adapts two different patch sets, one
contributed by Nick Downs.

It fixes:
- isAlive logging for all file systems
- file naming during isAlive checks for cluster
  file systems

Resolves: rhbz#562237

Signed-off-by: Lon Hohberger <lhh@redhat.com>

diff --git a/rgmanager/src/resources/fs.sh.in b/rgmanager/src/resources/fs.sh.in
--- a/rgmanager/src/resources/fs.sh.in
+++ b/rgmanager/src/resources/fs.sh.in
@@ -620,6 +620,7 @@ isMounted () {
 # 
 isAlive()
 {
+	declare errcode
 	declare mount_point
 	declare file=".writable_test"
 	declare rw
@@ -640,8 +641,10 @@ isAlive()
 	
 	# depth 10 test (read test)
 	ls $mount_point > /dev/null 2> /dev/null
-	if [ $? -ne 0 ]; then
-	       return $NO
+	errcode=$?
+	if [ $errcode -ne 0 ]; then
+		ocf_log err "fs:${OCF_RESKEY_name}: isAlive failed read test on [$mount_point]. Return code: $errcode"
+		return $NO
 	fi
 	
 	[ $OCF_CHECK_LEVEL -lt 20 ] && return $YES
@@ -664,7 +667,11 @@ isAlive()
 			fi
 		done
 		touch $file > /dev/null 2> /dev/null
-		[ $? -ne 0 ] && return $NO
+		errcode=$?
+		if [ $errcode -ne 0 ]; then
+			ocf_log err "fs:${OCF_RESKEY_name}: isAlive failed write test on [$mount_point]. Return code: $errcode"
+			return $NO
+		fi
 		rm -f $file > /dev/null 2> /dev/null
 	fi
 	
